### ISSUE TITLE
pub build fails in security_monkey v0.3.2

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#100]
As in https://github.com/akserg/angular.dart.ui/issues/142 , ```pub build``` fails on v0.3.2.

Seems to even fail with ```code_transformers: '0.2.3+2'```

Fails on the .deb and homebrew version: https://github.com/dart-lang/homebrew-dart/issues/18

Some discussion: http://stackoverflow.com/questions/27308501/since-when-has-the-angular-transformer-required-the-dartsdk-path-be-specified-in

This is a blocking failure and must be corrected ASAP.

**Comment by monkeysecurity** [comment]
If using the .deb package, setting up the symlink corrects the problem:

    ln -s /usr/lib/dart /usr/lib/dart/bin/dart-sdk

If using the homebrew package, it's not so easy.  Adding the dart_sdk location to the angular transformer allows ```pub build``` to build the security_monkey codebase, but it still fails when building the angular dart ui package

    transformers:
     - angular:
        dart_sdk: "/usr/local/opt/dart/libexec"

Output:

    (securitymonkey)➜  dart git:(develop) ✗ pub build
    Loading source assets...
    Loading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformeLoading di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformers... (1.5s)
    Loading angular transformers...
    Error on line 21, column 5 of ../../../.pub-cache/hosted/pub.dartlang.org/angular_ui-0.6.3/pubspec.yaml: Error loading transformer: Invalid arguments(s): sdkDirectory must be provided.
        html_files:
        ^^^^^^^^^^^^^

If you're on a mac, you can download the Dart Editor and perform a ```pub build``` from there.  That way you can avoid the homebrew package until it's fixed.

I really hope these packages (homebrew and deb) are fixed so they can perform a ```pub build``` without the user modifying the codebase or adding symlinks post installation.  It is super hacky at the moment.

**Comment by applesauce49** [comment]
Do you have any suggestions when the pub build appears to fail even after setting the sym link to the dart-sdk?  I keep running the command and it runs for ~minute and then just stops.  When I look in the build directory there is nothing...

Thanks

**Comment by monkeysecurity** [comment]
@applesauce49 You're using the .deb install of the dart tools?  Does ```pub build``` provide any output before it stops?  What is the output of  ```pub --version``` ?  If it's older than v1.8.*, you may want to do a ```sudo apt-get update``` before running ```apt-get install -y dart```

I may upload a .tar file containing the build output.  Others have requested that.  Would that help?

**Comment by applesauce49** [comment]
I've got dart 1.8.5.

I think part of my problem appears to be that I'm using the t1.micro ubuntu instance type at AWS.  as soon as I tried to do the build on my local machine it worked fine.  based on your comment, i can assume it's safe for me to just tar up the results of that and send it to my aws ubuntu instance?

Thanks

**Comment by monkeysecurity** [comment]
The homebrew issue has been fixed with code_transformers 0.2.5.  Huge thanks to @sethladd.

I've updated the pubspec.yaml in commit e66463fa4b3fb4994f4226f129e9f997b84cf1aa in both the master and develop branches.

**Comment by monkeysecurity** [comment]
code_transformers 0.2.5 also removes the requirement to have the symlink in the .deb installs.

**Comment by sethladd** [comment]
To be fair, huge thanks to @pq and @jakemac53
