### ISSUE TITLE
IDs in database are constantly changing 

### ISSUE THREAD

**Issue by steve-heslouin** [Netflix/security_monkey#1002]
Hi, 

I'm using security monkey API such as /api/issues

I noticed that an issue, for example:

```
{u'account': u'my-account', u'justification': None, u'account_type': u'AWS', u'name': u'my.user', u'issue': u'Needs Rotation', u'region': u'universal', u'id': 1142, u'justified_date': u'2018-03-14 12:54:28.421911', u'score': 1, u'item_links': [], u'item_id': 573, u'justified': False, u'fixed': False, u'technology': u'iamuser', u'notes': u'Active Accesskey [***************] last rotated > 90 days ago on 2017-11-06 12:12:33+00:00'}
```
In this example, my.user issue got the ID 1142.

Turns out, for some reasons, after a while, for the same user, same aws key issue, the **id** will change :/ keeping impossible to follow for me what happened between now and 20 min ago, as i need to rely on the fact that **id** and unique and never changed not will ever be reused.

So my question is to know why issues ID are changing and is there any way to actually keep track of them (apart using accesskey for example as unique ID)

Thx

EDIT: nope, **item_id** can be duplicated :/ i have several **identical item_id**, i really dunno how to make good use of your program , why not using classic **uuids**??

**Comment by mikegrima** [comment]
The `item_id` is supposed to refer to the specific item (AWS key in your case)

**Comment by steve-heslouin** [comment]
Hi @mikegrima , and thanks for answering my wonders ;)

I noticed that if a user, let's call it user1 has 2 keys older than 90 days, then the item_id will be the same. The thing is that i got a copy of those item in separate DB, so i can remind my users periodically about their key, before i expire them. So i need to regularly make a diff of your db vs mine in order to check if the issues has disappeared or being resolved, and since those items are duplicate, then i simply can't. I need to parse and use AWS key as unique item_id.

I guess you must have a special reason for that, but there is more and more the idea of letting users fix their own security issues, instead of giving that to security team only and letting them chase ppl, and i wished security monkey would make easier the idea of integrating third parties (slack, hipchat etc..) so we could directly forward kind of issues to users directly so they can resolve them themselves ;)

**Comment by mikegrima** [comment]
@steve-heslouin In your case, the item ID will be the same because the item in question is the IAM user. A user can have multiple keys. If there are multiple keys, the item ID will be the same, since they are still grouped under that IAM user (in this case).

You can make your own customer auditors and alerters, should the built-in ones not meet your use case. We could make definitely make use of a Slack plugin, should you be interested in creating one.
