### ISSUE TITLE
secmonkey is incompatible with cloudformation setup

### ISSUE THREAD

**Issue by lucab** [Netflix/security_monkey#101]
I recently had to monitor several accounts, not managed by me, and provisioned by cloudformation. The owner just took the IAM "SecurityMonkey" role details and translated them into a cloudformation template which sets up all the IAM bits.

Unfortunately, it looks like in its current incarnation secmonkey doesn't work in such scenario, because the AssumeRole fails. This is due to two facts:
 * cloudformation will generate a dynamic role name for you, in the form of `<stackname>-<rolelabel>-<dynrandomID>`
 * we hardcode the role name as "SecurityMonkey" in `sts_connect.py`

I'm currently playing more with cloudformation parameters, but I currently think there is no way for me to specify the name. I've a ticket open with them to see if it is doable, and I'm not noting the issue here in case other users are going the cloudformation path.

**Comment by monkeysecurity** [comment]
Checkout #30.  I have not been able to get this pull request ready to merge, but it looks like they are specifying the name of the IAM Roles:

https://github.com/Netflix/security_monkey/pull/30/files#diff-1b2884798108f7179292b45ea1e5db47R149

Does that help?

**Comment by lucab** [comment]
I think that pull request mostly covers setting up SecurityMonkey machine, not the target account. The usual Get*/List*/Describe policy is missing there, as well as the role named "SecurityMonkey" (that's ok, as you'll normally add that to *another account* to monitor).

What I've experienced today is that, even if at L135 you label your role as "SecurityMonkeyInstanceRole", it will be created as "<stackname>-SecurityMonkeyInstanceRole-<randID>". Unfortunately there is not much we can do here if Amazon mangle the specified rolename with arbitrary prefix+suffix.

**Comment by lucab** [comment]
I just got a confirmation of this on the AWS ticket:
```
This is beacuse CloudFormation names the resource Physical ID with it's stack's information e.g: "test-SecurityMonkey-TF4ADH7OY2SS".

CloudFormation registers each of the resources and by design it will place the StackName and an Identifier behind the name of the Resource. 
```

**Comment by monkeysecurity** [comment]
We could replace the hardcoded role names with a reference to an application config param defined in ```envconfig/config-deploy.py```.

Would that work?

**Comment by lucab** [comment]
Probably not.

First, we should put up a field in web settings to override the hardcoded role name *per AWS account*. But then, I'm not sure if at every cloudformation run, the role name will be updated (randomly). If it is, it's a war already lost. If not, maybe there is hope.

I'll ask tomorrow my colleagues to check for the behaviour...
