### ISSUE TITLE
Setup broken due to python-dateutils 2.7.0 release

### ISSUE THREAD

**Issue by tyron** [Netflix/security_monkey#1010]
## Please make sure that you have checked the boxes: 

- [x] Review the [Quickstart guide](quickstart.md)
- [X] Search for both open and closed issues regarding the problem you are experiencing
- [X] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](iam_aws.md), [GCP](iam_gcp.md), [OpenStack](iam_openstack.md), [GitHub](github_setup.md#access-keys-and-permissions)

## Description of issue:

Setup broken by `python-dateutils` release 2.7.0 (Mar 18).
Security Monkey requires `botocore`. And `botocore` requires `python-dateutil` < 2.7.0.

### Workaround
After creating the `virtualenv`, run:
`pip install "python-dateutil<2.7.0,>=2.1"`

**Comment by mikegrima** [comment]
Need to find which library is causing the issues.

I actually encountered this recently with another project. I resolved it by directly removing the datetuil package -- but that's not directly imported in SM :/

**Comment by mikegrima** [comment]
I just cloned SM into a new directory, created a new virtualenv, and was able to install it without issues.

Are you currently seeing this on the latest develop?

**Comment by tyron** [comment]
Yes, I am seeing on the latest develop. I just created a new Ubuntu 16.04 on AWS and ran all from [3-install-sm.md](https://github.com/Netflix/security_monkey/blob/develop/docs/installation/03-install-sm.md).

Err, not sure what you meant by 

> Need to find which library is causing the issues.

I thought it was `botocore`..? I've seen other projects with issues related, and I found this issue on the `boto3` repo: [Install fails when up-to-date python-dateutil is installed #1485](https://github.com/boto/boto3/issues/1485)

**Comment by mikegrima** [comment]
As in -- I just want to pull in whichever `dateutil` library that `botocore` uses since that is one of the most important libraries in Security Monkey.

This definitely feels like a `botocore` bug that we are downstream affected by.

I'm going to leave this issue open. Once `boto` has resolved this on their end, we'll make whatever updates are required to the `boto3` libraries to fix.

**Comment by Leectan** [comment]
I believe botocore is working just fine, as long as the required packages are installed according to the debug info.

**Comment by mikegrima** [comment]
@tyron Are you still seeing issues? I was not able to replicate.

**Comment by Leectan** [comment]
@mikegrima I have the same issue, not on my docker(sucessful), but I'm testing my ec2 ubuntu server. Botocore require dateutil < 2.7.0.

**Comment by mikegrima** [comment]
Closing until more information is provided.

**Comment by lxkaka** [comment]
I still has the same problem

**Comment by Leectan** [comment]
@lxkaka Please provide some rejected info. If the rejected info said python-dateutil 2.1 is required but 2.7 is installed, then you could do pip install python-dateutil=2.1.
