### ISSUE TITLE
http and https failed to connect to SM instance spun up from AMI.

### ISSUE THREAD

**Issue by Leectan** [Netflix/security_monkey#1016]
## Please make sure that you have checked the boxes: 

- [x] Review the [Quickstart guide](quickstart.md)
- [x] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [x] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](iam_aws.md), [GCP](iam_gcp.md), [OpenStack](iam_openstack.md), [GitHub](github_setup.md#access-keys-and-permissions)

## Description of issue:

<Http and https failed to connect to SM instance that spun up from ubuntu AMI. Verified both port 80 and 443 are opened, FQDN is point to the new DNS that was created in the config.py, sudo service nginx and supervisor are both running, able to SSH into the instance. Any idea what else I could be missing here?? Everything works fine until the instance was made into AMI.>

**Comment by mikegrima** [comment]
`Verified both port 80 and 443 are opened` -- Both on the instance and security groups attached to the instance?

Do you have an ELB set up? What happens when you curl from the localhost on that instance? Do the Security Monkey logs reveal anything?

**Comment by mstair** [comment]
@Leectan and I did some debug on Gitter. Curls on/to http://localhost returned with conn refused too. Verified no iptables or ufw. Also verified that nginx was listening on 443. We moved the nginx ssl port from 443 to 8443 and a localhost curl returned. Its weird...almost like some host firewall is blocking.

**Comment by Leectan** [comment]
This issue is still being debugging, close for now. Will update once debug successful.

**Comment by Leectan** [comment]
This issue is still being debugged, close for now. Will update once debug successful.
