### ISSUE TITLE
Document redis installation

### ISSUE THREAD

**Issue by 0xdabbad00** [Netflix/security_monkey#1021]
## Please make sure that you have checked the boxes: 

- [x] Review the [Quickstart guide](quickstart.md)
- [x] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [x] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](iam_aws.md), [GCP](iam_gcp.md), [OpenStack](iam_openstack.md), [GitHub](github_setup.md#access-keys-and-permissions)

## Description of issue:

It seems redis is now required for Security Monkey's scheduler as of v1.0.0.  I don't see this documented anywhere.  It should be documented how to set this up:
```
yum install redis
systemctl enable redis
systemctl start redis
```

**Comment by mikegrima** [comment]
Is the following documentation insufficient: https://github.com/Netflix/security_monkey/blob/develop/docs/autostarting.md#the-scheduler ?

**Comment by 0xdabbad00** [comment]
That was how I identified that redis needed to be installed.  I think because the docs show how to setup the postgres server, they should also show setting up redis (https://github.com/Netflix/security_monkey/blob/develop/docs/installation/03-install-sm.md).  If the user wants to use an RDS instead of postgres, they can, and if they want to use ElastiCache instead of the local redis they can.

**Comment by mikegrima** [comment]
We added a blurb about this in the Quickstart guide.

Namely, the Redis part is more for production deployments vs. getting things initially up and running.
