### ISSUE TITLE
Documentation Suggestion on Ubuntu 16.04

### ISSUE THREAD

**Issue by fahrishb** [Netflix/security_monkey#1023]
## Please make sure that you have checked the boxes: 

- [x] Review the [Quickstart guide](quickstart.md)
- [x] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [x] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](iam_aws.md), [GCP](iam_gcp.md), [OpenStack](iam_openstack.md), [GitHub](github_setup.md#access-keys-and-permissions)

## Description of issue:
First of all, I can't figure out why I cant call the `systemctl` command using Ubuntu 14.04, so I decided to install security monkey on Ubuntu 16.04. I wrote a small change in the documentation if anyone decides to go with Ubuntu 16.04. However, if anyone knows why the `systemctl` command does not work on ubuntu 14.04 and how to fix them, I would like to know.

**# <Documentation Suggestion on Ubuntu 16.04 LTS.>**

OK I have a few suggestions for the documentation.
1. On [Launch a GCP instance](https://github.com/Netflix/security_monkey/blob/develop/docs/instance_launch_gcp.md), you suggested that we use Ubuntu 14.04 LTS. However, I can't seem to make `systemctl` command to work. So I went on to install SecurityMonkey with Ubuntu 16.04 LTS, in which the `systemctl` command works.

2. If anyone decides to install with Ubuntu 16.04, there are some things that have to be added to fit the environment.
On [Clone security_monkey](https://github.com/Netflix/security_monkey/blob/develop/docs/installation/03-install-sm.md), use this instead:

```
cd /usr/local/src
sudo git clone --depth 1 --branch develop https://github.com/Netflix/security_monkey.git
sudo chown -R `whoami`:www-data /usr/local/src/security_monkey
cd security_monkey
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
virtualenv venv
source venv/bin/activate
pip install --upgrade setuptools
pip install --upgrade pip
pip install --upgrade urllib3[secure]   # to prevent InsecurePlatformWarning
pip install google-compute-engine  # Only required on GCP
pip install cloudaux\[gcp\]
python setup.py develop
```

3. For [Autostarting Security Monkey](https://github.com/Netflix/security_monkey/blob/develop/docs/autostarting.md),
before calling `sudo supervisorctl status`, supervisor has to be reloaded first using the following command `systemctl reload supervisor`
So for example on the command for **Autostarting the API and UI**,
```
sudo chgrp -R www-data /var/log/security_monkey
sudo cp /usr/local/src/security_monkey/supervisor/security_monkey_ui.conf /etc/supervisor/conf.d/security_monkey_ui.conf
sudo systemctl enable nginx
sudo systemctl enable supervisor
sudo systemctl start nginx
sudo systemctl start supervisor
systemctl reload supervisor
sudo supervisorctl status
```

And you will not see any errors.

**Comment by mikegrima** [comment]
@fahrishb Can you submit a PR with your changes?

**Comment by mikegrima** [comment]
`systemctl` is related to systemd, which was introduced in 16.04.

**Comment by mikegrima** [comment]
For some suggestions:
1. `sudo git clone --depth 1 --branch develop https://github.com/Netflix/security_monkey.git`
^^ Would prefer `master` for typical installations, since the `develop` branch is technically unstable.

1. `systemctl reload supervisor`
^^ This should not be required, since you start the `supervisor` service right before. You also need to run this as `sudo`.

**Comment by fahrishb** [comment]
Hi @mikegrima , I've created the PR 
[PR for Issue 1023](https://github.com/Netflix/security_monkey/pull/1024)
