### ISSUE TITLE
[AWS] Roles may not be assumed by root accounts

### ISSUE THREAD

**Issue by fahrishb** [Netflix/security_monkey#1026]
## Please make sure that you have checked the boxes: 

- [x] Review the [Quickstart guide](quickstart.md)
- [x] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [x] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](iam_aws.md), [GCP](iam_gcp.md), [OpenStack](iam_openstack.md), [GitHub](github_setup.md#access-keys-and-permissions)

## Description of issue:

I am trying to integrate my AWS to Security Monkey. I followed the steps on
[iam_aws.md](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md)

but im getting 
`botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRole operation: Roles may not be assumed by root accounts.`

I'm not sure what I'm missing here. If anyone can help that would be great! thanks!

**Comment by mikegrima** [comment]
You can't use `arn:aws:iam::ACCOUNTID:root`.  Please go through the IAM guide to ensure that your `SecurityMonkeyInstanceProfile` has `sts:AssumeRole` permissions on the destination account's `SecurityMonkey` IAM role, which will have an ARN like: `arn:aws:iam::ACCOUNTID:role/SecurityMonkey`.

**Comment by fahrishb** [comment]
I did follow the exact instructions on the IAM guide.

<img width="1058" alt="screen shot 2018-04-07 at 11 12 09" src="https://user-images.githubusercontent.com/22738442/38451130-9619c24c-3a54-11e8-9ca7-c67ed2f1b336.png">

This is the trust relationship on `SecurityMonkey` IAM Role

This is the `Policy Document`
```
{
  "Version": "2008-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::[12_digit_account_ID]:role/SecurityMonkeyInstanceProfile"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```
I feel like there is something important missing in the documentation. 
I installed my SecurityMonkey on GCP and I am trying to connect my AWS into it. 
I tried creating these rules from my AWS root account, and when I got the error, I deleted the rules and logged back in using IAM (non-root) credentials. I still get the same error.

**Comment by fahrishb** [comment]
Ok so I am able to get a non-root account to call the commands. I changed the credentials located in `~/.aws/credentials` to the accesskey and secretkey of the IAM user that is non-root.

But I am getting this error now

`
An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam::118598550704:user/fahrishb is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::118598550704:role/SecurityMonkey
`

Referring to [Issue#732](https://github.com/Netflix/security_monkey/issues/732),

I placed my credentials also in `/etc/boto.cfg` but still getting the same error

**Comment by mikegrima** [comment]
Please ensure that you alter the Trust Relationships of the destination roles to permit your non-root user access. Please see this for additional details: https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md#allow-securitymonkeyinstanceprofile-to-assume-to-the-securitymonkey-role
