### ISSUE TITLE
Database: Missing unique index

### ISSUE THREAD

**Issue by kpcyrd** [Netflix/security_monkey#1028]
It seems we ran into an edgecase by not ensuring there's only one scheduler at any time which caused an inconsistent database that security monkey is not able to recover from by itself. The database allows to have duplicate keys in the custom_fields table which causes incorrect audit issues to be reported. It seems security monkey is not able to recover from this by itself.

This could be prevented with a unique constraint on the foreign key of the account and the name of the custom field.

```
>>>
>>> abc.custom_fields
[<security_monkey.datastore.AccountTypeCustomValues object at 0x7f55fde4aed0>, <security_monkey.datastore.AccountTypeCustomValues object at 0x7f55fde4af50>, <security_monkey.datastore.AccountTypeCustomValues object at 0x7f55fde4afd0>, <security_monkey.datastore.AccountTypeCustomValues object at 0x7f55fd39c0d0>, <security_monkey.datastore.AccountTypeCustomValues object at 0x7f55fd39c190>]
>>> [x.name for x in abc.custom_fields]
[u's3_name', u'role_name', u'canonical_id', u's3_name', u'canonical_id']
>>> [(x.name, x.value) for x in abc.custom_fields]
[(u's3_name', None), (u'role_name', u'MyAuditRole'), (u'canonical_id', None), (u's3_name', None), (u'canonical_id', u'ffxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')]
```

Most of the debugging work for this has been done by @calciol.

**Comment by mikegrima** [comment]
Ouch! Thank's for reporting this! We'll need to do something similar to: #1004

**Comment by mikegrima** [comment]
@kpcyrd This will be slightly more difficult than #1004 in that I will need to pick and choose the value to keep.

In your output, it shows duplicate `canonical_id`s. I think the best that I can do is to keep the duplicated field that is not `null` and delete the rest.

Does this sound reasonable?

**Comment by mikegrima** [comment]
It looks like the model itself is correct, but not applied in the Alembic script: https://github.com/Netflix/security_monkey/blob/develop/migrations/versions/55725cc4bf25_.py#L35-L43

**Comment by mikegrima** [comment]
I'm really glad you found this @kpcyrd ! I found over 300K duplicates in my DB!

**Comment by mikegrima** [comment]
@kpcyrd Please pull in the latest develop and run `monkey db upgrade`. Let me know if you still see any more issues.
