### ISSUE TITLE
Uncaught exception running rule Alert on App: Parser must be a string or character stream, not int

### ISSUE THREAD

**Issue by adolia** [Netflix/security_monkey#1061]
Hi there!

I got an error while trying to run rule with buffer_time > 1 minute
"message": "Uncaught exception running rule Alert on App: Parser must be a string or character stream, not int",
  "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/lib/python2.7/site-packages/elastalert/elastalert.py\", line 1115, in run_all_rules",
    "    num_matches = self.run_rule(rule, endtime, self.starttime)",
    "  File \"/usr/lib/python2.7/site-packages/elastalert/elastalert.py\", line 814, in run_rule",
    "    if not self.run_query(rule, rule[\u0027starttime\u0027], tmp_endtime):",
    "  File \"/usr/lib/python2.7/site-packages/elastalert/elastalert.py\", line 603, in run_query",
    "    data = self.get_hits(rule, start, end, index, scroll)",
    "  File \"/usr/lib/python2.7/site-packages/elastalert/elastalert.py\", line 417, in get_hits",
    "    hits = self.process_hits(rule, hits)",
    "  File \"/usr/lib/python2.7/site-packages/elastalert/elastalert.py\", line 334, in process_hits",
    "    set_es_key(hit[\u0027_source\u0027], rule[\u0027timestamp_field\u0027], rule[\u0027ts_to_dt\u0027](ts))",
    "  File \"/usr/lib/python2.7/site-packages/elastalert/util.py\", line 112, in ts_to_dt",
    "    dt = dateutil.parser.parse(timestamp)",
    "  File \"/usr/lib/python2.7/site-packages/dateutil/parser.py\", line 1182, in parse",
    "    return DEFAULTPARSER.parse(timestr, **kwargs)",
    "  File \"/usr/lib/python2.7/site-packages/dateutil/parser.py\", line 556, in parse",
    "    res, skipped_tokens = self._parse(timestr, **kwargs)",
    "  File \"/usr/lib/python2.7/site-packages/dateutil/parser.py\", line 675, in _parse",
    "    l = _timelex.split(timestr)         # Splits the timestr into tokens",
    "  File \"/usr/lib/python2.7/site-packages/dateutil/parser.py\", line 192, in split",
    "    return list(cls(s))",
    "  File \"/usr/lib/python2.7/site-packages/dateutil/parser.py\", line 61, in __init__",
    "    \u0027{itype}\u0027.format(itype=instream.__class__.__name__))",
    "TypeError: Parser must be a string or character stream, not int"
  ]

Using latest elastalert with elasticsearch 6.2.3

Any idea what is the issue?
Thanks in advance!

**Comment by shadow-maz** [comment]
Hi,
I am facing the same issue. Were you able to resolve this issue?
