### ISSUE TITLE
Ignore changes based on membership in autoscaling groups

### ISSUE THREAD

**Issue by TanyaSavchuk** [Netflix/security_monkey#1068]
## Please make sure that you have checked the boxes: 

- [x] Review the [Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md)
- [x] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [x] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md), [GCP](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md), [OpenStack](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_openstack.md), [GitHub](https://github.com/Netflix/security_monkey/blob/develop/docs/github_setup.md#access-keys-and-permissions)

## Description of issue:

Usage question: how do you get Security Monkey to ignore changes related to environment scaling up or down? For example - ignore creation / deletion of ec2 instances based on membership in autoscaling groups?

**Comment by mikegrima** [comment]
Hello!

The only way currently is to disable the EC2 watchers. 

If you have an environment with ephemeral instances, then it's highly recommended to disable the EC2 watchers, as it will have a lot of churn.

**Comment by mikegrima** [comment]
@TanyaSavchuk : Does this help resolve your issue?

**Comment by ghost** [comment]
@mikegrima: Yes, thank you.
