### ISSUE TITLE
Not able to see aws account details in security monkey dashboard 

### ISSUE THREAD

**Issue by venki541** [Netflix/security_monkey#1069]
## Please make sure that you have checked the boxes: 

- [x] Review the [Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md)
- [x] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [x] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md), [GCP](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md), [OpenStack](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_openstack.md), [GitHub](https://github.com/Netflix/security_monkey/blob/develop/docs/github_setup.md#access-keys-and-permissions)

## Description of issue:

Hi Team,
I have installed security monkey by following the blog https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md, can able to view the dashboard, have added one test account to view the detail.

But i am not able to see any information on Dashboard for the  account what i have configured, can anyone guide on how to fix or is there anything which i am missing in configuration.

**Comment by mikegrima** [comment]
Please review: https://github.com/Netflix/security_monkey/blob/develop/docs/troubleshooting.md#common-issues

**Comment by venki541** [comment]
Hi Mike,
I have loaded  the supervisor worker, scheduler and ui as documented, but i am not able to start these processes under scheduler. I am not able to find the log for this, can you help me out in fixing this.

![supervisor](https://user-images.githubusercontent.com/37206184/40380187-e9f9faa0-5e15-11e8-9465-fa93738d6d73.PNG)

**Comment by mikegrima** [comment]
All instances must be launched with the `SecurityMonkeyInstanceProfile` IAM role as documented in the AWS IAM documentation.
