### ISSUE TITLE
Auditor Settings should be paginated, sortable, and filterable.

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#107]
When using Auditor Settings with a few dozen AWS accounts, the table becomes unwieldy.  The table (and underlying REST calls) should be paginated, column-sortable, and either searchable or filterable.

**Comment by JaguarSecurity** [comment]
What would you says is the realistic limit on the number of accounts that Security Monkey can handle? We have significantly more than a few dozen.

**Comment by monkeysecurity** [comment]
@JaguarSecurity 

In the future we hope to move to an off instance scheduler like an RDS-backed APscheduler or even zookeeper.  That would help scale the watchers horizontally on a number of different boxes, meaning you could monitor many more AWS accounts.  Pull requests would be welcome here.  That would move the performance bottleneck to the RDS datastore, which could then be optimized.

As previously mentioned, I'm comfortable with a single instance/db to monitor a few dozen accounts.  If you're up in the hundreds or thousands of AWS accounts, it would take significant development work (described above) to handle that.  Feel free to contact me (patrick@netflix.com) if you'd like to share your use case or if you have any developers that could assist.  This could help us prioritize.

**Comment by monkeysecurity** [comment]
With v0.3.4, pagination and sorting is complete.
Filtering will be added soon.

**Comment by monkeysecurity** [comment]
Auditor Settings Filtering has fallen off the roadmap. Closing ticket.
