### ISSUE TITLE
security monkey if justify the issues, still score bored  reflecting  same score  please help me fix this

### ISSUE THREAD

**Issue by ghost** [Netflix/security_monkey#1084]
## Please make sure that you have checked the boxes: 

- [x] [Pease review the Troubleshooting doc for additional details regarding your issue.](https://github.com/Netflix/security_monkey/blob/develop/docs/troubleshooting.md)
- [x] Review the [Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md)
- [ ] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [ ] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md), [GCP](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md), [OpenStack](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_openstack.md), [GitHub](https://github.com/Netflix/security_monkey/blob/develop/docs/github_setup.md#access-keys-and-permissions)

## Description of issue:

<Please replace this line with a description of the issue you are experiencing. Please use Markdown to `wrap all code for readability`.>

**Comment by mikegrima** [comment]
Hello! 

Can you please clarify the issue you are experiencing?

**Comment by drewgallis** [comment]
_Justified Score Updating Problems:_
I am experiencing a similar issue! Overall, I think the error is either somewhat related with where the UI is fetching the updated items from the database since when you specifically search for the highscore item outside of the Dashboard, it's score seems to be updating fine. 

_Below are two screenshots showing the area in which the problem is occurring:_
The dashboard high score view is not properly updating its score after justifying changes, while the actual non dashboard (search view) of the item displays the proper score.

**High Score View (The one displaying the wrong score for the specific item):**
![screen shot 2018-06-04 at 09 24 12](https://user-images.githubusercontent.com/21179354/40920073-7dae9a72-67d9-11e8-9a3d-4446cdf3a166.png)

**Non Dashboard View (Displaying the correct score):**
![screen shot 2018-06-04 at 09 25 20](https://user-images.githubusercontent.com/21179354/40920074-7dc5747c-67d9-11e8-9395-dd0f88d4b365.png)

**Comment by drewgallis** [comment]
Figured out issue is in relation to how the **highScoreItem** is being fetched. Right now it is finding it's score by running through a function called _totalScore()_, but this seems to be returning the wrong score. Another alternative option I think may work is using the _unjustifiedScore()_ in the same file since it includes the scores of all unjustified scores, leaving out ones you have justified.

**Files I am referring to:**
_item.dart (has the functions which highScoreItem is calling)_
_dashboard_component.html (where it is being invoked)_
_dashboard_component.dart (dart invokation)_

**Comment by drewgallis** [comment]
#1088 - Pull Request should fix your issue I forked it myself!

**Comment by mikegrima** [comment]
@jaisonkjaws I just merged in #1088 which should address this.

Can you pull down the latest develop and re-build the Dart code?

**Comment by ghost** [comment]
sure i will do and thanks for your update

**Comment by m5systems** [comment]
Hey.  I setup Security Monkey.  I added two accounts.  It seems it to never work with my two AWS accounts.  Both AWS accounts work separately and have the right roles setup but when I add them both only one works anybody know what else I should be doing to make it grabs other accounts.  I have shutdown the database and stopped the processes with no luck.   It gives me this error though:


 [SQL: 'SELECT anon_1.item_id AS anon_1_item_id, anon_1.item_region AS anon_1_item_region, anon_1.item_name AS anon_1_item_name, anon_1.item_arn AS anon_1_item_arn, anon_1.item_latest_revision_complete_hash AS anon_1_item_latest_revision_complete_hash, anon_1.item_latest_revision_durable_hash AS anon_1_item_latest_revision_durable_hash, anon_1.item_tech_id AS anon_1_item_tech_id, anon_1.item_account_id AS anon_1_item_account_id, anon_1.item_latest_revision_id AS anon_1_item_latest_revision_id, anon_1.itemrevision_date_created AS anon_1_itemrevision_date_created, itemaudit_1.id AS itemaudit_1_id, itemaudit_1.score AS itemaudit_1_score, itemaudit_1.issue AS itemaudit_1_issue, itemaudit_1.notes AS itemaudit_1_notes, itemaudit_1.action_instructions AS itemaudit_1_action_instructions, itemaudit_1.background_info AS itemaudit_1_background_info, itemaudit_1.origin AS itemaudit_1_origin, itemaudit_1.origin_summary AS itemaudit_1_origin_summary, itemaudit_1.class_uuid AS itemaudit_1_class_uuid, itemaudit_1.fixed AS itemaudit_1_fixed, itemaudit_1.justified AS itemaudit_1_justified, itemaudit_1.justified_user_id AS itemaudit_1_justified_user_id, itemaudit_1.justification AS itemaudit_1_justification, itemaudit_1.justified_date AS itemaudit_1_justified_date, itemaudit_1.item_id AS itemaudit_1_item_id, itemaudit_1.auditor_setting_id AS itemaudit_1_auditor_setting_id, account_1.id AS account_1_id, account_1.active AS account_1_active, account_1.third_party AS account_1_third_party, account_1.name AS account_1_name, account_1.notes AS account_1_notes, account_1.identifier AS account_1_identifier, account_1.account_type_id AS account_1_account_type_id, technology_1.id AS technology_1_id, technology_1.name AS technology_1_name \nFROM (SELECT item.id AS item_id, item.region AS item_region, item.name AS item_name, item.arn AS item_arn, item.latest_revision_complete_hash AS item_latest_revision_complete_hash, item.latest_revision_durable_hash AS item_latest_revision_durable_hash, item.tech_id AS item_tech_id, item.account_id AS item_account_id, item.latest_revision_id AS item_latest_revision_id, itemrevision.date_created AS itemrevision_date_created \nFROM item JOIN itemrevision ON item.latest_revision_id = itemrevision.id JOIN account ON account.id = item.account_id JOIN account ON account.id = item.account_id \nWHERE account.name IN (%(name_1)s) AND itemrevision.active = true AND account.active = true ORDER BY itemrevision.date_created DESC \n LIMIT %(param_1)s OFFSET %(param_2)s) AS anon_1 LEFT OUTER JOIN (issue_item_association AS issue_item_association_1 JOIN itemaudit AS itemaudit_1 ON itemaudit_1.id = issue_item_association_1.super_issue_id) ON anon_1.item_id = issue_item_association_1.sub_item_id LEFT OUTER JOIN account AS account_1 ON account_1.id = anon_1.item_account_id LEFT OUTER JOIN technology AS technology_1 ON technology_1.id = anon_1.item_tech_id ORDER BY anon_1.itemrevision_date_created DESC'] [parameters: {'name_1': 'NONP', 'param_1': 1000000000, 'param_2': 0}] (Background on this error at: http://sqlalche.me/e/f405)
 [SQL: 'SELECT anon_1.item_id AS anon_1_item_id, anon_1.item_region AS anon_1_item_region, anon_1.item_name AS anon_1_item_name, anon_1.item_arn AS anon_1_item_arn, anon_1.item_latest_revision_complete_hash AS anon_1_item_latest_revision_complete_hash, anon_1.item_latest_revision_durable_hash AS anon_1_item_latest_revision_durable_hash, anon_1.item_tech_id AS anon_1_item_tech_id, anon_1.item_account_id AS anon_1_item_account_id, anon_1.item_latest_revision_id AS anon_1_item_latest_revision_id, anon_1.itemrevision_date_created AS anon_1_itemrevision_date_created, itemaudit_1.id AS itemaudit_1_id, itemaudit_1.score AS itemaudit_1_score, itemaudit_1.issue AS itemaudit_1_issue, itemaudit_1.notes AS itemaudit_1_notes, itemaudit_1.action_instructions AS itemaudit_1_action_instructions, itemaudit_1.background_info AS itemaudit_1_background_info, itemaudit_1.origin AS itemaudit_1_origin, itemaudit_1.origin_summary AS itemaudit_1_origin_summary, itemaudit_1.class_uuid AS itemaudit_1_class_uuid, itemaudit_1.fixed AS itemaudit_1_fixed, itemaudit_1.justified AS itemaudit_1_justified, itemaudit_1.justified_user_id AS itemaudit_1_justified_user_id, itemaudit_1.justification AS itemaudit_1_justification, itemaudit_1.justified_date AS itemaudit_1_justified_date, itemaudit_1.item_id AS itemaudit_1_item_id, itemaudit_1.auditor_setting_id AS itemaudit_1_auditor_setting_id, account_1.id AS account_1_id, account_1.active AS account_1_active, account_1.third_party AS account_1_third_party, account_1.name AS account_1_name, account_1.notes AS account_1_notes, account_1.identifier AS account_1_identifier, account_1.account_type_id AS account_1_account_type_id, technology_1.id AS technology_1_id, technology_1.name AS technology_1_name \nFROM (SELECT item.id AS item_id, item.region AS item_region, item.name AS item_name, item.arn AS item_arn, item.latest_revision_complete_hash AS item_latest_revision_complete_hash, item.latest_revision_durable_hash AS item_latest_revision_durable_hash, item.tech_id AS item_tech_id, item.account_id AS item_account_id, item.latest_revision_id AS item_latest_revision_id, itemrevision.date_created AS itemrevision_date_created \nFROM item JOIN itemrevision ON item.latest_revision_id = itemrevision.id JOIN account ON account.id = item.account_id JOIN account ON account.id = item.account_id \nWHERE account.name IN (%(name_1)s) AND itemrevision.active = true AND account.active = true ORDER BY itemrevision.date_created DESC \n LIMIT %(param_1)s OFFSET %(param_2)s) AS anon_1 LEFT OUTER JOIN (issue_item_association AS issue_item_association_1 JOIN itemaudit AS itemaudit_1 ON itemaudit_1.id = issue_item_association_1.super_issue_id) ON anon_1.item_id = issue_item_association_1.sub_item_id LEFT OUTER JOIN account AS account_1 ON account_1.id = anon_1.item_account_id LEFT OUTER JOIN technology AS technology_1 ON technology_1.id = anon_1.item_tech_id ORDER BY anon_1.itemrevision_date_created DESC'] [parameters: {'name_1': 'NONP', 'param_1': 1000000000, 'param_2': 0}] (Background on this error at: http://sqlalche.me/e/f405)
 [SQL: 'SELECT anon_1.item_id AS anon_1_item_id, anon_1.item_region AS anon_1_item_region, anon_1.item_name AS anon_1_item_name, anon_1.item_arn AS anon_1_item_arn, anon_1.item_latest_revision_complete_hash AS anon_1_item_latest_revision_complete_hash, anon_1.item_latest_revision_durable_hash AS anon_1_item_latest_revision_durable_hash, anon_1.item_tech_id AS anon_1_item_tech_id, anon_1.item_account_id AS anon_1_item_account_id, anon_1.item_latest_revision_id AS anon_1_item_latest_revision_id, anon_1.itemrevision_date_created AS anon_1_itemrevision_date_created, itemaudit_1.id AS itemaudit_1_id, itemaudit_1.score AS itemaudit_1_score, itemaudit_1.issue AS itemaudit_1_issue, itemaudit_1.notes AS itemaudit_1_notes, itemaudit_1.action_instructions AS itemaudit_1_action_instructions, itemaudit_1.background_info AS itemaudit_1_background_info, itemaudit_1.origin AS itemaudit_1_origin, itemaudit_1.origin_summary AS itemaudit_1_origin_summary, itemaudit_1.class_uuid AS itemaudit_1_class_uuid, itemaudit_1.fixed AS itemaudit_1_fixed, itemaudit_1.justified AS itemaudit_1_justified, itemaudit_1.justified_user_id AS itemaudit_1_justified_user_id, itemaudit_1.justification AS itemaudit_1_justification, itemaudit_1.justified_date AS itemaudit_1_justified_date, itemaudit_1.item_id AS itemaudit_1_item_id, itemaudit_1.auditor_setting_id AS itemaudit_1_auditor_setting_id, account_1.id AS account_1_id, account_1.active AS account_1_active, account_1.third_party AS account_1_third_party, account_1.name AS account_1_name, account_1.notes AS account_1_notes, account_1.identifier AS account_1_identifier, account_1.account_type_id AS account_1_account_type_id, technology_1.id AS technology_1_id, technology_1.name AS technology_1_name \nFROM (SELECT item.id AS item_id, item.region AS item_region, item.name AS item_name, item.arn AS item_arn, item.latest_revision_complete_hash AS item_latest_revision_complete_hash, item.latest_revision_durable_hash AS item_latest_revision_durable_hash, item.tech_id AS item_tech_id, item.account_id AS item_account_id, item.latest_revision_id AS item_latest_revision_id, itemrevision.date_created AS itemrevision_date_created \nFROM item JOIN itemrevision ON item.latest_revision_id = itemrevision.id JOIN account ON account.id = item.account_id JOIN account ON account.id = item.account_id \nWHERE account.name IN (%(name_1)s) AND itemrevision.active = true AND account.active = true ORDER BY itemrevision.date_created DESC \n LIMIT %(param_1)s OFFSET %(param_2)s) AS anon_1 LEFT OUTER JOIN (issue_item_association AS issue_item_association_1 JOIN itemaudit AS itemaudit_1 ON itemaudit_1.id = issue_item_association_1.super_issue_id) ON anon_1.item_id = issue_item_association_1.sub_item_id LEFT OUTER JOIN account AS account_1 ON account_1.id = anon_1.item_account_id LEFT OUTER JOIN technology AS technology_1 ON technology_1.id = anon_1.item_tech_id ORDER BY anon_1.itemrevision_date_created DESC'] [parameters: {'name_1': 'NONP', 'param_1': 1000000000, 'param_2': 0}] (Background on this error at: http://sqlalche.me/e/f405)
 [SQL: 'SELECT anon_1.item_id AS anon_1_item_id, anon_1.item_region AS anon_1_item_region, anon_1.item_name AS anon_1_item_name, anon_1.item_arn AS anon_1_item_arn, anon_1.item_latest_revision_complete_hash AS anon_1_item_latest_revision_complete_hash, anon_1.item_latest_revision_durable_hash AS anon_1_item_latest_revision_durable_hash, anon_1.item_tech_id AS anon_1_item_tech_id, anon_1.item_account_id AS anon_1_item_account_id, anon_1.item_latest_revision_id AS anon_1_item_latest_revision_id, anon_1.itemrevision_date_created AS anon_1_itemrevision_date_created, itemaudit_1.id AS itemaudit_1_id, itemaudit_1.score AS itemaudit_1_score, itemaudit_1.issue AS itemaudit_1_issue, itemaudit_1.notes AS itemaudit_1_notes, itemaudit_1.action_instructions AS itemaudit_1_action_instructions, itemaudit_1.background_info AS itemaudit_1_background_info, itemaudit_1.origin AS itemaudit_1_origin, itemaudit_1.origin_summary AS itemaudit_1_origin_summary, itemaudit_1.class_uuid AS itemaudit_1_class_uuid, itemaudit_1.fixed AS itemaudit_1_fixed, itemaudit_1.justified AS itemaudit_1_justified, itemaudit_1.justified_user_id AS itemaudit_1_justified_user_id, itemaudit_1.justification AS itemaudit_1_justification, itemaudit_1.justified_date AS itemaudit_1_justified_date, itemaudit_1.item_id AS itemaudit_1_item_id, itemaudit_1.auditor_setting_id AS itemaudit_1_auditor_setting_id, account_1.id AS account_1_id, account_1.active AS account_1_active, account_1.third_party AS account_1_third_party, account_1.name AS account_1_name, account_1.notes AS account_1_notes, account_1.identifier AS account_1_identifier, account_1.account_type_id AS account_1_account_type_id, technology_1.id AS technology_1_id, technology_1.name AS technology_1_name \nFROM (SELECT item.id AS item_id, item.region AS item_region, item.name AS item_name, item.arn AS item_arn, item.latest_revision_complete_hash AS item_latest_revision_complete_hash, item.latest_revision_durable_hash AS item_latest_revision_durable_hash, item.tech_id AS item_tech_id, item.account_id AS item_account_id, item.latest_revision_id AS item_latest_revision_id, itemrevision.date_created AS itemrevision_date_created \nFROM item JOIN itemrevision ON item.latest_revision_id = itemrevision.id JOIN account ON account.id = item.account_id JOIN account ON account.id = item.account_id \nWHERE account.name IN (%(name_1)s) AND itemrevision.active = true AND account.active = true ORDER BY itemrevision.date_created DESC \n LIMIT %(param_1)s OFFSET %(param_2)s) AS anon_1 LEFT OUTER JOIN (issue_item_association AS issue_item_association_1 JOIN itemaudit AS itemaudit_1 ON itemaudit_1.id = issue_item_association_1.super_issue_id) ON anon_1.item_id = issue_item_association_1.sub_item_id LEFT OUTER JOIN account AS account_1 ON account_1.id = anon_1.item_account_id LEFT OUTER JOIN technology AS technology_1 ON technology_1.id = anon_1.item_tech_id ORDER BY anon_1.itemrevision_date_created DESC'] [parameters: {'name_1': 'NONP', 'param_1': 1000000000, 'param_2': 0}] (Background on this error at: http://sqlalche.me/e/f405
