### ISSUE TITLE
New installation -securitymonkeyui not running and also data not populating on GUI

### ISSUE THREAD

**Issue by ghost** [Netflix/security_monkey#1087]
Hello Team,
          Am setting up security monkey first time to integrate my production infra. I have followed all the instructions given at Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md.  UI is coming up and am able to login. However data is not populating though i have added the AWS accounts. 
From supervisorctl command i can see it is trying to make up the UI component but it is not. Below is the exceptions 

/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_SQLAlchemy-1.0-py2.7.egg/flask_sqlalchemy/__init__.py:30: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_SQLAlchemy-1.0-py2.7.egg/flask_sqlalchemy/__init__.py:30: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/psycopg2-2.7.4-py2.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
[2018-06-11 11:05:23 +0000] [16079] [INFO] Starting gunicorn 19.7.1
[2018-06-11 11:05:23 +0000] [16079] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-11 11:05:23 +0000] [16079] [ERROR] Retrying in 1 second.
[2018-06-11 11:05:24 +0000] [16079] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-11 11:05:24 +0000] [16079] [ERROR] Retrying in 1 second.
[2018-06-11 11:05:25 +0000] [16079] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-11 11:05:25 +0000] [16079] [ERROR] Retrying in 1 second.
[2018-06-11 11:05:26 +0000] [16079] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-11 11:05:26 +0000] [16079] [ERROR] Retrying in 1 second.
[2018-06-11 11:05:27 +0000] [16079] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-11 11:05:27 +0000] [16079] [ERROR] Retrying in 1 second.
[2018-06-11 11:05:28 +0000] [16079] [ERROR] Can't connect to ('127.0.0.1', 5000)
/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_SQLAlchemy-1.0-py2.7.egg/flask_sqlalchemy/__init__.py:30: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Flask_SQLAlchemy-1.0-py2.7.egg/flask_sqlalchemy/__init__.py:30: ExtDeprecationWarning: Importing flask.ext.sqlalchemy._compat is deprecated, use flask_sqlalchemy._compat instead.
  from flask.ext.sqlalchemy._compat import iteritems, itervalues, xrange, \
/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/psycopg2-2.7.4-py2.7-linux-x86_64.egg/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
[2018-06-11 11:05:31 +0000] [16107] [INFO] Starting gunicorn 19.7.1
[2018-06-11 11:05:31 +0000] [16107] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-11 11:05:31 +0000] [16107] [ERROR] Retrying in 1 second.
[2018-06-11 11:05:32 +0000] [16107] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-11 11:05:32 +0000] [16107] [ERROR] Retrying in 1 second.
[2018-06-11 11:05:33 +0000] [16107] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-11 11:05:33 +0000] [16107] [ERROR] Retrying in 1 second.
[2018-06-11 11:05:34 +0000] [16107] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-11 11:05:34 +0000] [16107] [ERROR] Retrying in 1 second.
[2018-06-11 11:05:35 +0000] [16107] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-11 11:05:35 +0000] [16107] [ERROR] Retrying in 1 second.
[2018-06-11 11:05:36 +0000] [16107] [ERROR] Can't connect to ('127.0.0.1', 5000)

Rest all componets are up and running:

sudo supervisorctl status

securitymonkeyscheduler          RUNNING   pid 16080, uptime 6:36:16
securitymonkeyui                 RUNNING   pid 4140, uptime 0:00:04
securitymonkeyworkers            RUNNING   pid 16078, uptime 6:36:16

NOTE:
1. Am using single AWS instance with 3 GB RAM to install all the components.
2. Below the version of components

OS : Ubuntu 16.04.4 LTS \n \l - 64 bit ( This is AWS instance of t2.small)

3. Used the latest version as per the quickstart guide
4. Installed entire tool via non-root user and in virtual env

Can somebody guide me how to fix this issue?

**Comment by drewgallis** [comment]
@ashok1301 
Seems like your api port 5000 is being _blocked/used by another service_ based on what you are receiving. I would recommend running your api on a different port or making sure your firewall settings allow for your API to run on port 5000. If that isn't the case and you aren't running locally you can check your AWS IAM roles/Security Group permissions to make sure you are allow TCP access to ports are properly configured.

**Comment by ghost** [comment]
Hello drewgallis,
       Thanks for your reply.  I have cross verified above mentioned things, and looks fine.
1.  venv) sentinels@securitymonkey1:/var/log/supervisor$ netstat -anp|grep 5000
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      3864/python     
(venv) sentinels@securitymonkey1:/var/log/supervisor$ ps -eaf|grep 3864
sentine+  3864     1  0 Jun21 ?        00:00:09 /usr/local/src/security_monkey/venv/bin/python /usr/local/src/security_monkey/venv/bin/monkey run_api_server
sentine+  3870  3864  0 Jun21 ?        00:00:00 /usr/local/src/security_monkey/venv/bin/python /usr/local/src/security_monkey/venv/bin/monkey run_api_server
sentine+  3871  3864  0 Jun21 ?        00:00:00 /usr/local/src/security_monkey/venv/bin/python /usr/local/src/security_monkey/venv/bin/monkey run_api_server
sentine+  3872  3864  0 Jun21 ?        00:00:00 /usr/local/src/security_monkey/venv/bin/python /usr/local/src/security_monkey/venv/bin/monkey run_api_server
sentine+  3873  3864  0 Jun21 ?        00:00:00 /usr/local/src/security_monkey/venv/bin/python /usr/local/src/security_monkey/venv/bin/monkey run_api_server
sentine+  3874  3864  0 Jun21 ?        00:00:00 /usr/local/src/security_monkey/venv/bin/python /usr/local/src/security_monkey/venv/bin/monkey run_api_server
sentine+  3875  3864  0 Jun21 ?        00:00:00 /usr/local/src/security_monkey/venv/bin/python /usr/local/src/security_monkey/venv/bin/monkey run_api_server
sentine+  3876  3864  0 Jun21 ?        00:00:00 /usr/local/src/security_monkey/venv/bin/python /usr/local/src/security_monkey/venv/bin/monkey run_api_server
sentine+  3877  3864  0 Jun21 ?        00:00:00 /usr/local/src/security_monkey/venv/bin/python /usr/local/src/security_monkey/venv/bin/monkey run_api_server
sentine+  3878  3864  0 Jun21 ?        00:00:00 /usr/local/src/security_monkey/venv/bin/python /usr/local/src/security_monkey/venv/bin/monkey run_api_server
sentine+  3879  3864  0 Jun21 ?        00:00:00 /usr/local/src/security_monkey/venv/bin/python /usr/local/src/security_monkey/venv/bin/monkey run_api_server
sentine+  3880  3864  0 Jun21 ?        00:00:00 /usr/local/src/security_monkey/venv/bin/python /usr/local/src/security_monkey/venv/bin/monkey run_api_server
sentine+  3881  3864  0 Jun21 ?        00:00:00 /usr/local/src/security_monkey/venv/bin/python /usr/local/src/security_monkey/venv/bin/monkey run_api_server
sentine+  4144  3251  0 11:47 pts/1    00:00:00 grep --color=auto 3864

2.  Since it is staging account, Am installing all components on single AWS instance which has 8 GB RAM. There is no iptables enabled as well.
3. securitymonkeyui process exiting very frequently , which is observed from superviserctl console. error log clearly says 
---------------
[2018-06-22 11:44:27 +0000] [3901] [INFO] Starting gunicorn 19.7.1
[2018-06-22 11:44:27 +0000] [3901] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-22 11:44:27 +0000] [3901] [ERROR] Retrying in 1 second.
[2018-06-22 11:44:28 +0000] [3901] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-22 11:44:28 +0000] [3901] [ERROR] Retrying in 1 second.
[2018-06-22 11:44:29 +0000] [3901] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-22 11:44:29 +0000] [3901] [ERROR] Retrying in 1 second.
[2018-06-22 11:44:30 +0000] [3901] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-22 11:44:30 +0000] [3901] [ERROR] Retrying in 1 second.
[2018-06-22 11:44:31 +0000] [3901] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2018-06-22 11:44:31 +0000] [3901] [ERROR] Retrying in 1 second.
[2018-06-22 11:44:32 +0000] [3901] [ERROR] Can't connect to ('127.0.0.1', 5000)
------------
4.  Because of above issues, am unable to integrate my staging account with security monkey.
5. Please suggest if any checklist since it is greenfield deployment and am struggling last 1 week to integrate at least 1 account.

--
BR,
Ashok

**Comment by ghost** [comment]
One more observations is
1. Am performing the supervise restart as root users
2.Rest all the things followed exactly mentioned as quickinstall guide.

**Comment by drewgallis** [comment]
Sounds like instance is performing fine, since it is a supervisor issue it is most likely a configuration error. Have you tried running the non automated configuration `monkey run_api_server` standalone and then running `monkey find_changes` to try to manually find an audit changes on your AWS Account you have added?

**Comment by boodera** [comment]
Same issue I'm facing. No data is shown in dashboard UI. I checked if any other service is running in the AWS instance. I rechecked the roles and policies applied to the instance. 
I tried giving Admin access and then fetching data using `monkey find_changes -a- <ID>` but still no data.

**Comment by mikegrima** [comment]
@boodera Please follow the [troubleshooting guide](https://github.com/Netflix/security_monkey/blob/develop/docs/troubleshooting.md), configure proper logs, and provide details on the error messages that you are seeing.
