### ISSUE TITLE
404 errors in logs, cannot find packages directory

### ISSUE THREAD

**Issue by slacking42** [Netflix/security_monkey#109]
Hi I have been working at this for a while.. 

I have everything up and running however I am not getting a login screen in the web ui

I check the logs and saw this 

2015/02/17 19:35:09 [error] 3051#0: *2 open() "/usr/local/src/security_monkey/security_monkey/static/packages/web_components/dart_support.js" failed (2: No such file or directory), client: 1.1.1.1, server: , request: "GET /packages/web_components/dart_support.js HTTP/1.1", host: "FQDN.us-wes-1.compute.amazonaws.com", referrer: "FQDN.us-west-1.compute.amazonaws.com/"
2015/02/17 19:35:09 [error] 3051#0: *1 open() "/usr/local/src/security_monkey/security_monkey/static/packages/browser/dart.js" failed (2: No such file or directory), client: 1.1.1.1, server: , request: "GET /packages/browser/dart.js HTTP/1.1", host: "FQDN.us-wes-1.compute.amazonaws.com", referrer: "FQDN.us-west-1.compute.amazonaws.com/"
2015/02/17 19:35:09 [error] 3051#0: *1 open() "/usr/local/src/security_monkey/security_monkey/static/packages/web_components/webcomponents.min.js" failed (2: No such file or directory), client: 1.1.1.1, server: , request: "GET /packages/web_components/webcomponents.min.js HTTP/1.1", host: "FQDN.us-wes-1.compute.amazonaws.com", referrer: "FQDN.us-west-1.compute.amazonaws.com/"
2015/02/17 19:35:09 [error] 3051#0: *1 open() "/usr/local/src/security_monkey/security_monkey/static/packages/web_components/dart_support.js" failed (2: No such file or directory), client: 1.1.1.1, server: , request: "GET /packages/web_components/dart_support.js HTTP/1.1", host: "FQDN.us-wes-1.compute.amazonaws.com", referrer: "FQDN.us-west-1.compute.amazonaws.com/"

so I check the directories where it is supposed to be and i see a symlink .. that goes to nowhere

ubuntu@ip-1.1.1.1:/usr/local/src/security_monkey/security_monkey/static$ pwd
/usr/local/src/security_monkey/security_monkey/static

ubuntu@ip-1.1.1.1:/usr/local/src/security_monkey/security_monkey/static$ ls
css  fonts  ico  images  js  main.dart  packages  select2-3.4.5  theme.css  ui.html  views

ubuntu@ip-1.1.1.1:/usr/local/src/security_monkey/security_monkey/static$ ls -l packages
lrwxrwxrwx 1 root root 11 Feb 17 19:31 packages -> ../packages

ubuntu@ip-1.1.1.1:/usr/local/src/security_monkey/security_monkey$ ls
alerter.py   auditor.pyc  constants.py   datastore.pyc   exceptions.py   __init__.pyc  reporter.py   scheduler.pyc  tests       watcher.pyc
alerter.pyc  auditors     constants.pyc  decorators.py   exceptions.pyc  monitors.py   reporter.pyc  static         views       watchers
auditor.py   common       datastore.py   decorators.pyc  __init__.py     monitors.pyc  scheduler.py  templates      watcher.py

Has anyone else seen this?

Where is this "packages" directory that I should be seeing? can i copy it to the appropriate directory to resolve this? or does it need to be symlinked?

TIA

**Comment by monkeysecurity** [comment]
Couple things:
- The login/register page is served up by flask, and shouldn't rely on packages.
- The ```packages``` directory is one of the folders generated when you run ```pub build``` in the ```security_monkey/dart``` folder.  It should *not* be a symlink.  After the ```pub build```, the output should be copied with ```cp -R``` from ```security_monkey/dart/build/web``` to ```security_monkey/security_monkey/static/```.


You may want to rerun pub build and cp -r the files again.

Docker images are available as well:
https://github.com/Netflix-Skunkworks/zerotodocker/

I have a pending pull request that updates the dockers to the latest versions:
https://github.com/Netflix-Skunkworks/zerotodocker/pull/28

**Comment by slacking42** [comment]
awesome thanks, ill take a stab at this in the am and comment back, I appreciate the quick response

**Comment by slacking42** [comment]
ran the pub build again and ended up wit the same symlinks as before.. I don't think we are going to try  the docker, I would like to get this built up for prod if possible..

the output from the build is here (Easier to read)

http://pastebin.com/RRinR9zm

Thanks again

**Comment by monkeysecurity** [comment]
That is really odd.  (Following output is from the develop branch, but master is similar)

    securitymonkey/dart/build/web$ ls
    css  fonts  ico  images  js  main.dart.html_reference  main.dart.js  packages  select2-3.4.5  ui.html  views
    securitymonkey/dart/build/web$ ls -al | grep packages
    drwxr-xr-x 10 www-data www-data    4096 Feb 18 00:34 packages

I don't know what would cause yours to have symlinks.

I could upload a .tar or .zip with the contents of the static folder if you would like?

**Comment by slacking42** [comment]
that would be amazing if you could!  I really appreciate it

**Comment by monkeysecurity** [comment]
Ok - ETA is Friday.

**Comment by slacking42** [comment]
perfect thanks

**Comment by monkeysecurity** [comment]
I've attached a tar file to the latest release:

https://github.com/Netflix/security_monkey/releases/tag/lsv0.3.4
https://github.com/Netflix/security_monkey/releases/download/lsv0.3.4/static.tar

Download ```static.tar``` to ```security_monkey/static/static.tar``` and then extract it with ```tar -xvf static.tar```.

    ➜  tar -xvf static.tar
    ...
    ➜  ls
    css                      ico                      js                       main.dart.js             select2-3.4.5            ui.html
    fonts                    images                   main.dart.html_reference packages                 static.tar               views
    ➜  ls -al
    total 12528
    drwxr-xr-x  14 user  2119906183      476 Feb 20 13:27 .
    drwx------  34 user  2119906183     1156 Feb 20 13:27 ..
    drwxr-xr-x  10 user  2119906183      340 Feb 20 13:24 css
    drwxr-xr-x   6 user  2119906183      204 Feb 20 13:24 fonts
    drwxr-xr-x   5 user  2119906183      170 Feb 20 13:24 ico
    drwxr-xr-x   8 user  2119906183      272 Feb 20 13:24 images
    drwxr-xr-x   6 user  2119906183      204 Feb 20 13:24 js
    -rw-r--r--   1 user  2119906183       11 Feb 20 13:24 main.dart.html_reference
    -rw-r--r--   1 user  2119906183  1800633 Feb 20 13:24 main.dart.js
    drwxr-xr-x  10 user  2119906183      340 Feb 20 13:24 packages
    drwxr-xr-x  10 user  2119906183      340 Feb 20 13:24 select2-3.4.5
    -rw-r--r--   1 user  2119906183  4597760 Feb 20 13:26 static.tar
    -rw-r--r--   1 user  2119906183     5228 Feb 20 13:24 ui.html
    drwxr-xr-x  13 user  2119906183      442 Feb 20 13:24 views
    ➜  cd packages
    ➜  (packages)  ls -al
    total 0
    drwxr-xr-x  10 user  2119906183  340 Feb 20 13:24 .
    drwxr-xr-x  14 user  2119906183  476 Feb 20 13:27 ..
    drwxr-xr-x   3 user  2119906183  102 Feb 20 13:24 angular
    drwxr-xr-x  22 user  2119906183  748 Feb 20 13:24 angular_ui
    drwxr-xr-x   4 user  2119906183  136 Feb 20 13:24 browser
    drwxr-xr-x   3 user  2119906183  102 Feb 20 13:24 csslib
    drwxr-xr-x   3 user  2119906183  102 Feb 20 13:24 intl
    drwxr-xr-x   3 user  2119906183  102 Feb 20 13:24 security_monkey
    drwxr-xr-x   4 user  2119906183  136 Feb 20 13:24 unittest
    drwxr-xr-x   8 user  2119906183  272 Feb 20 13:24 web_components

**Comment by monkeysecurity** [comment]
Please reopen if you run into problems.

**Comment by slacking42** [comment]
awesome! thanks for the assistance
