### ISSUE TITLE
Adding a user via the web ui

### ISSUE THREAD

**Issue by phillycheeze** [Netflix/security_monkey#1092]
## Description of issue:

Not possible to add users via the web UI. I see referenced in other issues and in documentation that it is possible to create users via the web interface. When I go to Settings -> Users, there is no way to create or even edit a user. in the `user_role_component` file, I don't see any markup that this seems to be the case. 

I'd like to edit a user, but there doesn't seem to be a way to update a user's password via the command line tool.

**Comment by drewgallis** [comment]
@phillycheeze
To edit/change an existing user's password you would call the creation of the user again by using the command line interface:
` monkey create_user "you@youremail.com" "Role"`
It should then re-prompt you to change the current password to a new! 
**Note: make sure you use the same email and role**

**Comment by phillycheeze** [comment]
@drewgallis Awesome, that is indeed what I needed. Thanks!
