### ISSUE TITLE
My securitymonkey server getting this on watcher menu, Due to an open issue. You must restart the scheduler on the scheduler instance after altering a watcher configuration

### ISSUE THREAD

**Issue by ghost** [Netflix/security_monkey#1093]
![sm 2018-06-27 20-42-45](https://user-images.githubusercontent.com/39819589/41983379-8b8a03e6-7a4b-11e8-902d-fc4b7621d74f.png)

I want to avoid this on watcher menu and automate watcher time update process

**Comment by ghost** [comment]
why close the issue

**Comment by mikegrima** [comment]
Because it's being tracked elsewhere, as per the documentation on the page describes.
