### ISSUE TITLE
SecurityMonkey doesn't provide detailed information

### ISSUE THREAD

**Issue by rafaljanicki** [Netflix/security_monkey#1094]
## Please make sure that you have checked the boxes: 

- [x] [Pease review the Troubleshooting doc for additional details regarding your issue.](https://github.com/Netflix/security_monkey/blob/develop/docs/troubleshooting.md)
- [x] Review the [Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md)
- [x] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing

## Description of issue:

Hello,

I'm not sure which update broke it as it might have been either v1.0.0 -> v1.1.0 or v1.1.0 -> v1.1.3, but I don't have detailed information on issues anymore. I have also confirmed that I'm not the only one based on Gitter's messages. I'm going to reuse @ollytheninja 's screenshots from the Gitter (I hope you don't mind!).

Before:
![image](https://user-images.githubusercontent.com/7746477/42231884-15820aee-7eed-11e8-9a23-e2d25ee23fd1.png)

After:
![image](https://user-images.githubusercontent.com/7746477/42231892-1a7a37e2-7eed-11e8-9fb9-05f989eec7b1.png)

I can also confirm that everything was working correctly on v1.0.0. In my infrastructure, I'm using the Docker approach, so it's probably not the configuration issues.
Let me know if I can provide more details to help debug the issue.

**Comment by rafaljanicki** [comment]
I've checked the changes in related code and I believe this might be the reason: https://github.com/Netflix/security_monkey/commit/573f8f19ff0f14f9d37e2349aa0299b7112026e3#diff-8169662c9a73fa6bbdd63664d294fd1cR200 . However, my knowledge on SM's code is too small to be sure of that

**Comment by mikegrima** [comment]
Unfortunately, the new issue system is half-baked at the moment.

I don't have any cycles this quarter to work on this. Please feel free to debug and submit PRs to help fix.

**Comment by kur3us** [comment]
I'm seeing this too. I have a Security Group with 12 issues, and SM says the same thing for each one, so I can't select which ones I want to justify and which ones I don't. The ports and CIDRs aren't shown. Egress/Ingress aren't shown.

**Comment by tyron** [comment]
Yeah, I'm having the same issue. If I want to know that issues are on a particular item, the best way is to use the Search page. The Notes column still display the issues. 
But justifying any is not possible as you don't know which is which.

**Comment by jcmcken** [comment]
Same issue here

**Comment by cByst** [comment]
Is this fixed? Or does anyone know a safe commit to build off that doesn't have this issue?

**Comment by ollytheninja** [comment]
From my investigation today, it appears there are two issues:
1. Notes aren't shown because the API returns a sub-item for **every single** issue
  can be fixed by displaying any notes as well as a link to the sub-item
  line 89 and 123 of `dart/lib/component/itemdetails/intemdetails.html`
2. The API appears to always return the item itself as the sub-item instead of the sub item
  Haven't found the relevant code for that yet but going to test the fix for 1. now and open a PR if it does

**Comment by jibsonline** [comment]
@ollytheninja 

How do I apply this patch? 

I updated 

```
/usr/local/src/security_monkey/static/packages/security_monkey/component/itemdetails/itemdetails.html
/usr/local/src/security_monkey/dart/lib/component/itemdetails/itemdetails.html
```
But my dashboard has not been updated with the changes

**Comment by jibsonline** [comment]
I am also facing the same issue. I see issues. But cant figure out the breach behind each

![image](https://user-images.githubusercontent.com/1730931/46076427-25a5ee80-c1ab-11e8-8949-94252607931f.png)

**Comment by mikegrima** [comment]
@jibsonline To be clear, these are not "breaches". These are potential issues that may or may not be a problematic configuration in your environment.

**Comment by jibsonline** [comment]
@mikegrima sorry about the terminology used. 

How do I understand details of each issue mentioned so I can fix it?

The only link in each row above is "jibu.chacko" on click of which nothing happens

**Comment by Ph4rell** [comment]
Issue #1094 still here ! got the same problem, i tried the commit of @ollytheninja and it doesn't work ! Insteade of the regular related note, i've got the name of the AWS account like @jibsonline.

**Comment by martwana** [comment]
Is there a timeline for this to be fixed, or a timeline for 2.0 to be released? 

I've spent a decent amount of time getting this up and running, and I cant see the descriptions of the issues it highlights. I'd hate for it to have been a waste of time

**Comment by kaylacrowder** [comment]
I agree with @martwana. I'd hate for this implementation to have been a waste of time. Should we be rolling back to a previous version? I can't seem to get a solid understanding of the specific things security monkey is checking for, nor do the items being flagged have details. Is there a timeline for a fix?

**Comment by hrzbrg** [comment]
@ollytheninja I verified that your patch https://github.com/ollytheninja/security_monkey/commit/8bdb202221b53892e11967b36bf9d2c5fa656691 works fine on the current develop branch and restores functionality. Do you maybe want to hand it in as a PR?

**Comment by ollytheninja** [comment]
Hi everyone, unfortunately I haven't had any time to contribute to this any further. I've just raised PR #1162 which contains my fix.
From previous conversation on gitter.im - v1.1.3 is affected as well as develop, if you go back to v1.1.0 you should be alright @kaylacrowder @martwana
