### ISSUE TITLE
Getting an Nginx 404 error when following the Quick Start guide

### ISSUE THREAD

**Issue by kur3us** [Netflix/security_monkey#1095]
## Description of issue:

Looking in `/var/log/security_monkey/security_monkey.error.log`, I see this:
`2018/07/11 02:37:15 [error] 19645#19645: *3 "/usr/local/src/security_monkey/static/ui.html" is not found (2: No such file or directory)`

And that makes sense, because in the Quick Start guide, it says to do this:
```
# Copy the compiled Web UI to the appropriate destination
sudo mkdir -p /usr/local/src/security_monkey/security_monkey/static/
sudo /bin/cp -R /usr/local/src/security_monkey/dart/build/web/* /usr/local/src/security_monkey/security_monkey/static/
```

Notice there are 2 security_monkey directories, but the web server is looking for only 1.

**Comment by kur3us** [comment]
If I move the static directory one level up, the UI works.

**Comment by sankarsarath** [comment]
thank you

**Comment by mikegrima** [comment]
Can you submit a PR to reflect your changes?

**Comment by kur3us** [comment]
I'm not sure which way is correct. The Docker config file and most of the documentation has security_monkey/security_monkey. But someone made a change to the nginx config file in May that removed the second security_monkey. (commit 504b9c0). Maybe that change should be reverted instead of changing everything else.

**Comment by abacao** [comment]
I have encountered this problem but I have used the following path in nginx + ubuntu:

> /usr/local/src/security_monkey/security_monkey/static

**Comment by mstair** [comment]
Documentation updated with correct path, can close

**Comment by mikegrima** [comment]
Thanks @mstair !
