### ISSUE TITLE
Add ExternalId as option for assuming role

### ISSUE THREAD

**Issue by dgreene-r7** [Netflix/security_monkey#1100]
## Please make sure that you have checked the boxes: 

- [X] [Please review the Troubleshooting doc for additional details regarding your issue.](https://github.com/Netflix/security_monkey/blob/develop/docs/troubleshooting.md)
- [X] Review the [Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md)
- [X] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [X] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md), [GCP](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md), [OpenStack](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_openstack.md), [GitHub](https://github.com/Netflix/security_monkey/blob/develop/docs/github_setup.md#access-keys-and-permissions)

## Description of issue:

There is currently no way of providing an `ExternalId` to calls to `sts::AssumeRole` even though [it's good practice to establish a trusted relationship between accounts via an `ExternalId`](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html).

Without digging too deep in the code this seems like it should be pretty straightforward: add the field to the model, generate a migration, and update calls to `sts.assume_role` to include the `ExternalId` kwarg.

**Comment by mikegrima** [comment]
Do you envision this being similar to the account "Assume Role" settings in the database, or as a variable in the configuration?

I'm guessing it would be the former?

**Comment by dgreene-r7** [comment]
Yeah, the former for sure.

**Comment by dgreene-r7** [comment]
I'm working on a PR for this. Should have something shortly.

**Comment by mikegrima** [comment]
You'll also need to submit a PR to CloudAux (https://github.com/Netflix-Skunkworks/cloudaux).
