### ISSUE TITLE
Docker containers no longer build due to dart v2

### ISSUE THREAD

**Issue by jsharpe** [Netflix/security_monkey#1107]
## Please make sure that you have checked the boxes: 

- [x] [Pease review the Troubleshooting doc for additional details regarding your issue.](https://github.com/Netflix/security_monkey/blob/develop/docs/troubleshooting.md)
- [x] Review the [Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md)
- [x] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [x] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md), [GCP](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md), [OpenStack](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_openstack.md), [GitHub](https://github.com/Netflix/security_monkey/blob/develop/docs/github_setup.md#access-keys-and-permissions)

## Description of issue:

docker containers fail to build as unittest is incompatible with dart sdk 2 but dart_stable debian repo now defaults to install dart v2.

**Comment by mikegrima** [comment]
We'll probably need to do what we did here: https://github.com/Netflix/security_monkey/blob/develop/docker/nginx/Dockerfile#L19-L25 and place it into the regular Dockerfile.

**Comment by mikegrima** [comment]
Or... Are you seeing this somewhere else?

**Comment by jsharpe** [comment]
No its in docker/nginx/Dockerfile that I had the problem, but specifically on the release tags.

**Comment by zpritcha** [comment]
@jsharpe can you build off the `develop` branch? this was fixed in https://github.com/Netflix/security_monkey/pull/1104 but hasn't been released yet
