### ISSUE TITLE
Not able to hit webpage with public dns of AWS EC2, nginx and security monkey started

### ISSUE THREAD

**Issue by GopiKannanJP** [Netflix/security_monkey#1110]
## Please make sure that you have checked the boxes: 

- [~] [Pease review the Troubleshooting doc for additional details regarding your issue.](https://github.com/Netflix/security_monkey/blob/develop/docs/troubleshooting.md)
- [~] Review the [Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md)
- [~ ] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing - did all still not able to fix
- [~] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md), [GCP](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md), [OpenStack](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_openstack.md), [GitHub](https://github.com/Netflix/security_monkey/blob/develop/docs/github_setup.md#access-keys-and-permissions)

Follow exactly as of installation guide from https://github.com/Netflix/security_monkey/tree/develop/docs/installation 

This site can’t be reached
ec2-XX-XXX-XXX-XXX.compute-1.amazonaws.com took too long to respond.

**Comment by mikegrima** [comment]
On first glance, this sounds like a security group issue.

How are you accessing AWS hosted resources? Are these publicly accessible instances (**NOT** recommended for Security Monkey), or do you have a Direct Connect or some VPN tunnel into the VPC?

**Comment by GopiKannanJP** [comment]
Instance is launched in private subnet of vpc 

Connected to instance via Bastion and did the installation

security group config: 
HTTP | TCP | 80 | 0.0.0.0/0 |  
All TCP | TCP | 0 - 65535 | 0.0.0.0/0 |  
PostgreSQL | TCP | 5432 | 0.0.0.0/0 |  
Custom TCP Rule | TCP | 8000 | 0.0.0.0/0 |  
SSH | TCP | 22 | 0.0.0.0/0 |  
HTTPS | TCP | 443 | 0.0.0.0/0

**Comment by mikegrima** [comment]
I think then you would want to access the instance via the private DNS name vs. the public one. A private VPC subnet can still give public IPs, but they won't be routable to your instance.

Can you access your instance via its private IP?

The public DNS part of the instructions is an artifact from back in the EC2 classic days and should be removed from the docs.

**Comment by GopiKannanJP** [comment]
Not able to hit the page even via private IP. But ngnix and security monkey starts without any failure. 
i have an similar setup where i was able to setup security monkey via ec2 classic and hitting result page with public dns. But not sure what might be causing issue while setting up in private subnet.

**Comment by GopiKannanJP** [comment]
i have an similar setup where i was able to setup security monkey via ec2 classic and hitting result page with public dns. But not sure what might be causing issue while setting up in private subnet.

**Comment by mikegrima** [comment]
Are you able to reach SM via your bastion? It seems that there might be some networking issues in your VPC.

**Comment by GopiKannanJP** [comment]
I was able to fix it through couple of changes in nginx -> /var/nginx/sites-enabled/securitymonkey.conf and ading an alb at front of instance launched in private subnet. 
1.But after that fix i was able to hit page but it gets redirected to anonymous user page instead of redirecting to login page / registration page, so how do can i fix this part.
2.As well as please suggest me how could i implement SM for production to maintain HA do you have any specific doc that says where exactly i can seggregate set of commands to be run on UI instance,schedular instance and worker instance
3. How does this instances - UI,Schedular,Worker communicate btwn each other. 

Appreciate your help...

**Comment by mikegrima** [comment]
What changes did you make to your NGINX configuration?

I would also suggest re-reading the quickstart guide https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md, as many of these questions should be answered there.

There is a section about running in Production and setting up the proper components.

**Comment by mikegrima** [comment]
@GopiKannanJP Are you still experiencing issues?

**Comment by GopiKannanJP** [comment]
Nope @mikegrima the changes that were made in nginx conf is with port change to 80 from 443. Tweaked the conf little bit and was able to succeed.

**Comment by erick2k1995** [comment]
I have exactly the same problem, I have everything configured as the guide does not give me error but when I access with the public DNS I can not, then the solution is to replace port 80 with 443?
