### ISSUE TITLE
Not able to use search config box to search for known issues

### ISSUE THREAD

**Issue by jaguilar42** [Netflix/security_monkey#1113]
## Please make sure that you have checked the boxes: 

- [x] [Pease review the Troubleshooting doc for additional details regarding your issue.](https://github.com/Netflix/security_monkey/blob/develop/docs/troubleshooting.md)
- [x] Review the [Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md)
- [x] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [x] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md), [GCP](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md), [OpenStack](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_openstack.md), [GitHub](https://github.com/Netflix/security_monkey/blob/develop/docs/github_setup.md#access-keys-and-permissions)

## Description of issue:
Hello,
I'm not able to search for audit issues in the web UI but I dont have any error logs that are not http 200 codes. So, I'm really not sure where to start looking for fixing this issue. 

![screen shot 2018-09-24 at 3 35 31 pm](https://user-images.githubusercontent.com/21365108/45982142-d5952380-c014-11e8-9742-2ebebe88c5fc.png)
![screen shot 2018-09-24 at 3 36 13 pm](https://user-images.githubusercontent.com/21365108/45982144-d928aa80-c014-11e8-92a6-47a0045a6051.png)

**Comment by mikegrima** [comment]
Are you running the latest develop branch? I do recall this being fixed.

It is also working for me internally.

**Comment by jaguilar42** [comment]
Yes I'm on version 1.1.3

I've dockerized it so I'm wondering if the security_monkey_api would be the one making this call.

**Comment by mikegrima** [comment]
I didn't push that release out yet (this is my bad).

You have to go by the latest git commit in develop, which is much farther ahead of that release.

**Comment by jaguilar42** [comment]
This would be running in prod, so I can't run the latest dev. When will the next release or are you able to send out a small release that fixes this issue?

**Comment by mikegrima** [comment]
In general, we've been doing very loose, rolling releases. If you need the fixes in production, for the time being, you will need pull in the latest develop branch.

I would have to dedicate some time to getting a release out. I do intend on dedicating some time this quarter to fixing some Security Monkey bugs and working on the 2.0 version.

The 2.0 version will fix a number of problems that should make pushing out releases much easier.

**Comment by jaguilar42** [comment]
Great, thanks. We'll go ahead and close this issue.
