### ISSUE TITLE
Check only for ingress Internet Access

### ISSUE THREAD

**Issue by jibsonline** [Netflix/security_monkey#1115]
Right now the Auditor rule "Internet Accessible" shows security groups which has `egress` to 0.0.0.0/0. Which in our case is not a breach. If I disable the rule will it stop showing groups which has `ingress` open to 0.0.0.0/0 as well?

In short `egress` to 0.0.0.0/0 is not a breach but `ingress` open to 0.0.0.0/0 is a breach. How do I configure this? 

Will `ingress` open to 0.0.0.0/0  show up in "Unknown Access"?

**Comment by mikegrima** [comment]
I recall that this was fixed.  Which version of SM are you running?

**Comment by mikegrima** [comment]
Actually, I remember now -- you can disable this check:

1. Go to Settings > Audit Issue Scores.
1. Click on the '+' button
1. Under Technology, select `securitygroup`
1. For Method, select `check_internet_accessible_egress (SecurityGroupAuditor)`
1. Finally, check `Disabled`, and click Save.

**Comment by jibsonline** [comment]
@mikegrima That solved it. Thanks

**Comment by mikegrima** [comment]
I'm going to add a section to the user guide and troubleshooting doc so that this is more clear.

**Comment by mikegrima** [comment]
Addressed in #1116
