### ISSUE TITLE
Feature Request: User Management System exposed via Web UI with roles.

### ISSUE THREAD

**Issue by JaguarSecurity** [Netflix/security_monkey#114]
The ability to manage SM users from the GUI. Add, delete, etc.
The ability to disable the sign up page

**Comment by monkeysecurity** [comment]
User registration can be disabled with a config option:

    SECURITY_REGISTERABLE = True

I agree that SM needs a user management and role system with admins/users.

**Comment by JaguarSecurity** [comment]
Thanks

**Comment by Blackbaud-FrankKurzawa** [comment]
SECURITY_REGISTERABLE is not conducive to a secure workflow to add users. The ability to confirm users after signup  before they get access would be much more helpful.

**Comment by Blackbaud-FrankKurzawa** [comment]
+1 for a role system with admins/users. Additionally defining roles in a way that would limiting which AWS accounts any given user could see or modify.

**Comment by rbeede** [comment]
I'd like to see the SECURITY_REGISTERABLE = False added to the Quick Start guide under "Productionalizing Security Monkey"

It'd also be nice if setting SECURITY_REGISTERABLE would not only disable that but also hide the Register link on the main login page.   If someone browses to the register HTML form they should be told registration is disabled.


Perhaps a better option would be to extract out user management to the web server engine level instead.   It'd be nice if I could tie my LDAP authentication into it instead or any other mechanism I choose that my web server supports.

**Comment by monkeysecurity** [comment]
User Management has was merged in PR #317.

SSO was added in PR #354.

@rbeede - I'll accept a PR for the quickstart guide to set `SECURITY_REGISTERABLE = False`.

Closing this issue now.
