### ISSUE TITLE
IP Protocol & Port Number Equal to -1 

### ISSUE THREAD

**Issue by markofu** [Netflix/security_monkey#115]
Hey Patrick,

Not sure where the issue is on this as I don't have access to this particular AWS account but I see some configurations equal to "-1" and I'm unsure as to why. If you feel this isn't an issue, please close but some clarification would be awesome. 

Thanks as always!

m

```
  {
               "from_port": null,
               "ip_protocol": "-1",
               "to_port": null,
               "owner_id": "ACCNTNUMBER",
               "name": null,
               "group_id": "sg-8c2357e9",
               "cidr_ip": null
          },
          {
               "from_port": "-1",
               "ip_protocol": "icmp",
               "to_port": "-1",
               "owner_id": "ACCNTNUMBER",
               "name": null,
               "group_id": "sg-5edbc932",
               "cidr_ip": null
          },
          {
               "from_port": "-1",
               "ip_protocol": "icmp",
               "to_port": "-1",
               "owner_id": "ACCNTNUMBER",
               "name": null,
               "group_id": "sg-5fdbc933",
               "cidr_ip": null
          }
```

**Comment by monkeysecurity** [comment]
Hey @markofu,

AWS does a couple funky things here.

- Instead of using JSON integers, they use strings.  ```"-1"``` instead of just ```-1```.
- The value ```-1``` is sometimes being used by AWS as a wildcard.

    "ip_protocol": "-1",

That means all protocols (TCP, UDP, ICMP, etc) are allowed from ```ACCNTNUMBER/sg-8c2357e9"

    "from_port": "-1",
    "ip_protocol": "icmp",
    "to_port": "-1",

In this situation, the ICMP protocol doesn't deal in ports, and so AWS returns -1.

Having said all of this, I don't believe you can type -1 into the console and have AWS treat it as a wildcard.

I'm hoping to be able to add a new tab to the web UI that will take the JSON and show it in a more human-friendly form.

**Comment by markofu** [comment]
Thanks @monkeysecurity, I was unaware of what "-1" meant so thanks.

In the _icmp_ case, that makes total sense (i.e. as to why it would be "-1").

> I'm hoping to be able to add a new tab to the web UI that will take the JSON and show it in a more human-friendly form.

Sweet, sounds good, thx!
