### ISSUE TITLE
Issue with pub build

### ISSUE THREAD

**Issue by rjchua** [Netflix/security_monkey#1152]
Hello, 

I'm trying to install Security Monkey and following the instruction from (https://e64-security-monkey.readthedocs.io/en/latest/quickstart.html#launch-an-ubuntu-instance)
I'm already in compiling web-app from the Dart code

# Build the Web UI
$ cd /usr/local/src/security_monkey/dart
$ sudo /usr/lib/dart/bin/pub build

when i execute the pub build here's the output 
[Dart 2 has a new build system. Learn how to migrate from pub build and
pub serve: https://webdev.dartlang.org/dart-2]

Can't continue from here. Is anyone here experience this?
Here's my verion
ubuntu@ip-172-31-35-51:/usr/local/src/security_monkey/security_monkey/static$ /usr/lib/dart/bin/dart --version
Dart VM version: 2.1.0 (Unknown timestamp) on "linux_x64"
ubuntu@ip-172-31-35-51:/usr/local/src/security_monkey/security_monkey/static$ /usr/lib/dart/bin/pub --version
Pub 2.1.0

Thanks Much for the help!

RJC

**Comment by SecMonkeyStuff** [comment]
You are using the old installation guide.
Try this one:
https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md

**Comment by mikegrima** [comment]
@rjchua @SecMonkeyStuff is correct -- please rely on the Quickstart documentation here.

**Comment by rjchua** [comment]
Thanks Much for the help guys @SecMonkeyStuff @mikegrima ..will try to follow this one. Will let you know

Cheers!
