### ISSUE TITLE
register page generates 500 error

### ISSUE THREAD

**Issue by markofu** [Netflix/security_monkey#116]
Hey Patrick,

I don't see a record of this anywhere in your issues list.

When someone registers as a new user, the https connection appears to timeout and generates a _500_ error.

Looking at the _securitymonkey-deploy.log_ file, I can see the following errors (note: this is two different registrations with second being a _repro_)

```
2015-02-25 13:37:20,244 ERROR: Exception on /register [POST] [in /usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py:1423]
  File "/usr/local/lib/python2.7/dist-packages/Flask_Security-1.7.4-py2.7.egg/flask_security/views.py", line 122, in register
2015-02-25 14:35:46,660 ERROR: Exception on /register [POST] [in /usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py:1423]
  File "/usr/local/lib/python2.7/dist-packages/Flask_Security-1.7.4-py2.7.egg/flask_security/views.py", line 122, in register
```

Line 122 in _views.py_ refers to the login function -

```
            login_user(user)
```

with the login function being

```
def login():
    """View function for login view"""

    form_class = _security.login_form

    if request.json:
        form = form_class(MultiDict(request.json))
    else:
        form = form_class()

    if form.validate_on_submit():
        login_user(form.user, remember=form.remember.data)
        after_this_request(_commit)

        if not request.json:
            return redirect(get_post_login_redirect(form.next.data))

    if request.json:
        return _render_json(form, include_auth_token=True)

    return _security.render_template(config_value('LOGIN_USER_TEMPLATE'),
                                     login_user_form=form,
                                     **_ctx('login'))
```

nginx configuration looks ok -

```
    location /register {
        proxy_read_timeout 120;
        proxy_pass  http://127.0.0.1:5000;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

The user is always created and the new user can login without a problem but I can't figure out where the 500 error is coming from.

Any thoughts?

**Comment by monkeysecurity** [comment]
I just ran through a user registration and did not have an issue.  I have, however, seen this before and was unable to track it down.

Could you share part of your ```env-config/config-deploy.py``` file with me?

    SECURITY_REGISTERABLE = True
    SECURITY_CONFIRMABLE = True
    SECURITY_RECOVERABLE = True

Specifically, I'm wondering if you have SECURITY_CONFIRMABLE enabled.

**Comment by monkeysecurity** [comment]
#64 is a related Registration issue, and is another bug that I haven't seen in a long time.  Not sure if setting CONFIRMABLE fixed this, or if a version of flask security fixed it.

Currently on ```Flask-Security==1.7.4```.

**Comment by markofu** [comment]
Thanks @monkeysecurity :)

I changed 

```
SECURITY_CONFIRMABLE = From
```

to

```
SECURITY_CONFIRMABLE = True
```

and restarted _supervisor_. The _register_ page now works perfectly (I did have to add a _confirm_ route  in the _nginx_ configration so I didn't generate a 404 page from the _confirm_ url).

Thx again!
