### ISSUE TITLE
"Audit Issues" and "Auditor Settings" empty on new install and lacking docs

### ISSUE THREAD

**Issue by cjbehm** [Netflix/security_monkey#117]
Following through the documentation to setup Security Monkey, I believe I have a working install but running a search for "Audit Issues" and the "Auditor Settings" are both empty.

A plain search for Items returns 204 items.

I don't know if this is a bug, a setup issue or a lack of documentation on how the Auditor Settings and Audit Items are supposed to work. Ultimately I couldn't find any documentation about the Audit component other than a few brief comments in the changelogs.

**Comment by monkeysecurity** [comment]
There definitely seems to be a lack of user documentation.  PR's are welcome.

![Issues Table](http://securitymonkey.readthedocs.org/en/latest/_images/issues_page.png)

The web UI has a dropdown box you can use to switch to the "Audit Issues" table.  After changing the value in the dropdown, and hitting ```Search```, do any issues appear?

If you still have no issues, you can manually invoke the auditor from the command line:

    export SECURITY_MONKEY_SETTINGS=`pwd`/env-config/config-deploy.py
    /apps/python/bin/python manage.py audit_changes

Watch stdout for any errors.  It should complete pretty quickly.  How long have you had your instance up?

Once you have Issues, then the AuditorSettings tab (Under Settings) should be filled.

You could also check the relevant log files for any errors, exceptions, or tracebacks.

**Comment by cjbehm** [comment]
The command runs fine (no errors messages) but searching for Audit Issues is empty as is the Auditor Settings.

When run, there are log lines such as:

Creating/Assigning Auditor Settings in account [...] and tech iamrole
Done Creating/Assigning Auditor Settings in account [...] and tech iamrole

And actual issues getting noted like:

Adding issue: s3/us-east-1/[...]/[...]
   ACL - Friendly Account Access. -- [...]

Since it's been running, these are followed by "Not adding issue because it was already seen", but none of the Audit Issue portions are populated (Items are).

I had an old (quite old) version running before and pulled it forward. That ran but also had no Audit Issues. I left it alone overnight and nothing had changed.

At that point I figured I'd just wipe it out and start fresh, since we're not actively using it for production purposes yet. This is a completely new instance and it's been running for 4 to 5 hours.

**Comment by monkeysecurity** [comment]
It seems like Issues are being saved to the database.  If you have navicat, or are familiar with psql, you could verify this.

If the issues are in the database, we need to determine if the REST API is returning them.  Hit this URL in your browser after replacing YOUR_SECURITY_MONKEY with your FQDN.

https://YOUR_SECURITY_MONKEY/api/1/issues?accounts=&count=25&enabledonly=true&names=&page=1&regions=&technologies=

https://YOUR_SECURITY_MONKEY/api/1/issues?accounts=&count=25&names=&page=1&regions=&technologies=

https://YOUR_SECURITY_MONKEY/api/1/issues

If issues are in your database, but are not appearing in the results of these REST calls, then there must be something wrong with the API code: https://github.com/Netflix/security_monkey/blob/master/security_monkey/views/item_issue.py#L33

If issues are in your database, and they are appearing when hitting the REST calls, then there must be something wrong with the compiled code in your security_monkey/static folder. You could replace the contents of the static folder with those in the static.tar attached to the last release:  https://github.com/Netflix/security_monkey/releases/tag/lsv0.3.4

If these steps help, please let me know so I can guide others away from hitting this same thing.

**Comment by cjbehm** [comment]
The first URI returns no results (a JSON response with no items). The 2nd and 3rd URIs return JSON objects with actual item structures.

Checking the auditorsettings table with psql, it has zero rows, so I'm guessing that it's supposed to have rows as part of the setup/db migration process?

**Comment by monkeysecurity** [comment]
I think @Qmando discovered the bug in commit f56023a733e4dfc0f8590812e4502fe75ee23550.

I'll work on pushing out a hotfix to all branches.

**Comment by jimmysharrrison** [comment]
I think I have this same issue

secmonkey=> select * from auditorsettings;
 id | tech_id | account_id | disabled | issue_text 
----+---------+------------+----------+------------
(0 rows)

**Comment by monkeysecurity** [comment]
Please verify my latest commit to auditor.py corrected this issue for you.

**Comment by cjbehm** [comment]
Yup, pulled the latest version and after re-running audit_changes, the audit related tables were all populated.

Auditor Settings and the Reports all appear to be working as expected now.

Thanks!

**Comment by hridyeshpant** [comment]
i did setup using https://github.com/Netflix-Skunkworks/zerotodocker/wiki/Security-Monkey
but facing same issue when clicking "Audit Issue" , nothings is coming. 
Does Docker version don't have these fix?
 
also below hit are returning results 
https://YOUR_SECURITY_MONKEY/api/1/issues?accounts=&count=25&enabledonly=true&names=&page=1&regions=&technologies=

https://YOUR_SECURITY_MONKEY/api/1/issues?accounts=&count=25&names=&page=1&regions=&technologies=

https://YOUR_SECURITY_MONKEY/api/1/issues

**Comment by hridyeshpant** [comment]
i could see the fixed is not present in latest version of docker images 0.3.4 (./security_monkey/build/lib.linux-x86_64-2.7/security_monkey/auditor.py when open this file inside the container) 
https://github.com/markofu/security_monkey/commit/433c3b11935c1f4a663d292f5b29d6894e9cfb71

**Comment by hridyeshpant** [comment]
i update the file security_monkey/auditor.py with latest version inside the container and run the command , its working and showing the audit issue .
Can some please let me know when this fix is available in docker image ?

**Comment by hridyeshpant** [comment]
Created security_monkey-scheduler docker images from v0.3.5 code base of security_monkey.
https://hub.docker.com/r/hpant/security_monkey-scheduler/
