### ISSUE TITLE
securitymonkeyworkers is not running 

### ISSUE THREAD

**Issue by bharathsat** [Netflix/security_monkey#1181]
Hello Team,

I have configured security monkey and started supervisor for all UI, scheduler, and worker, Scheduler and UI is started running but worker went to FATAL state and its not starting if i try to start.

```
security_monkey]# supervisorctl
securitymonkeyscheduler          RUNNING   pid 19966, uptime 0:52:24
securitymonkeyui                 RUNNING   pid 14588, uptime 2:34:14
securitymonkeyworkers            FATAL     Exited too quickly (process log may have details)
supervisor>


```
Can you please help out how can i fix this problem.

**Comment by bharathsat** [comment]
i wants to know the supervisor configuration for watcher. Why exactly we are using "startsecs=60", if we reduced it to somewhere around 3 will it be ok?.

Is it worker needs 60sec to stay on running state?
and what it dose in the 60sec?
can you please give me the brief explanation about worker and what it dose.

Thanks in advance, and your answers are highly appreciated.

**Comment by mikegrima** [comment]
Hello:

You will need to review the logs to know what specifically is failing.

The 60 second wait is to ensure that all the dependent services are running. Please review Quickstart guide and troubleshooting docs for more details.

**Comment by aaronkjones** [comment]
For me this was due to the ownership of the logs directory.
Executing the following worked:
```
(venv) root@securitymonkey:/usr/local/src/security_monkey# supervisorctl status
securitymonkeyui                 STARTING
securitymonkeyworkers            FATAL     Exited too quickly (process log may have details)
```

`chown -R www-data:www-data /var/log/security_monkey/`
`supervisorctl restart all`

```
(venv) root@securitymonkey:/usr/local/src/security_monkey# supervisorctl restart all
securitymonkeyui: stopped
securitymonkeyui: started
securitymonkeyworkers: started
```

**Comment by ybulent** [comment]
UI and worker shouldn't be on the same server.
I had the same problem. it is either UI or worker on each server.
