### ISSUE TITLE
Really high scores for attached IAM managed policy

### ISSUE THREAD

**Issue by mentormate-vassil-vassilev** [Netflix/security_monkey#1201]
Hi, there seems to be a problem with the scoring of the issues found or I am missing something fundamentally. We are using the develop branch. I already did my homework and checked all opened and closed issues. I also looked at the code, but maybe I don't fully understand the scoring logic.
We have a newly added AWS account and we are getting really high scores for an issue in the attached managed policy for IAM users. The policy is the same for all users:
```
"ManagedPolicies": [
    {
      "name": "IAMUserChangePassword",
      "arn": "arn:aws:iam::aws:policy/IAMUserChangePassword"
    }
  ]
```
And by high I mean really high. From the code I can tell that the score is summed, but still this seems to not be working correctly.
![image](https://user-images.githubusercontent.com/19669935/56349861-239c8f00-61d2-11e9-970a-f12dd9872ac8.png)

Please advice what does this mean - is this a bug or an expected behavior. How can I fix it?

Thanks!

**Comment by mikegrima** [comment]
The scoring system in SM is broken. Unfortunately, we will not be fixing it as we have moved Security Monkey into maintenance mode.
