### ISSUE TITLE
Error al ejecutar Pub build

### ISSUE THREAD

**Issue by erick2k1995** [Netflix/security_monkey#1213]
Good evening when executing usr / local / src / security_monkey / dart $ / usr / lib / dart / bin / pub build, I get the following message Dart 2 has a new build system. Learn how to migrate from pub build and
pub serve: https://webdev.dartlang.org/dart-2 ", does anyone have any idea how to make the migration?
![image](https://user-images.githubusercontent.com/52808488/61257569-47bb2e00-a737-11e9-81ae-70d1a5f0564b.png)

**Comment by mikegrima** [comment]
This is related to Google removing the Dart 1 code from their repos.

This is being tracked in #1206

**Comment by erick2k1995** [comment]
Thank you very much worked!
