### ISSUE TITLE
Syntax error on dart compile

### ISSUE THREAD

**Issue by zerojuan** [Netflix/security_monkey#126]
I'm using the latest version of Dart (1.9.1) and the compiled javascript results to a syntax error on line 49502 of main.dart.js.

`49502: ...a,Nf,JCx,OGh,YWs,pHq,LPx]}parseReflectionData(dart)`

is missing a semicolon before parseReflectionData:

`49502: ...a,Nf,JCx,OGh,YWs,pHq,LPx]};parseReflectionData(dart)`

**Comment by pbkracker** [comment]
Filed a bug against dart/dart2js:

https://code.google.com/p/dart/issues/detail?id=23042

**Comment by monkeysecurity** [comment]
Until the dart issue is closed, users may manually add this semi-colon, or download the pre-compiled dart output from here:

https://github.com/Netflix/security_monkey/releases/download/lsv0.3.4/static.tar

**Comment by floitschG** [comment]
I'm sorry for that.
It is fixed in bleeding edge (and has been for some time). I just forgot to cherry-pick it into 1.9.
I will see if we can make a 1.9.1 bugfix release (or similar).

**Comment by monkeysecurity** [comment]
I pre-compiled the output with dart 1.8.5 and attached a .tar.gz to the latest release:

https://github.com/Netflix/security_monkey/releases/tag/v0.3.5

Thanks @floitschG for getting this into ~1.9.1.
