### ISSUE TITLE
How to run SecMonkey locally

### ISSUE THREAD

**Issue by valencialexi** [Netflix/security_monkey#1260]
## Please make sure that you have checked the boxes: 

- [x ] [Pease review the Troubleshooting doc for additional details regarding your issue.](https://github.com/Netflix/security_monkey/blob/develop/docs/troubleshooting.md)
- [x ] Review the [Quickstart guide](https://github.com/Netflix/security_monkey/blob/develop/docs/quickstart.md)
- [x ] [Search for both open and closed issues](https://github.com/Netflix/security_monkey/issues?&q=is%3Aissue+) regarding the problem you are experiencing
- [x ] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md), [GCP](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md), [OpenStack](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_openstack.md), [GitHub](https://github.com/Netflix/security_monkey/blob/develop/docs/github_setup.md#access-keys-and-permissions)

## Description of issue:
Hi, I am new to Security Monkey and Dart Flutter. Is there a tutorial on how to setup/run the source code locally? I am planning to use VS Code WSL2. Thanks in advance!

**Comment by mikegrima** [comment]
Hello:

Security Monkey is not really supported anymore. We have developed a new tool to replace it internally that I would love to open source in the next few months (based on AWS Config). In fact, I should just archive this repo. The best info I can provide is to re-review the docs on setting it up, and I would advise relying on AWS Config (for AWS).
