### ISSUE TITLE
No content showing after installing Security Monkey

### ISSUE THREAD

**Issue by peterdu77** [Netflix/security_monkey#129]
Hi There,

I've tried installing SecurityMonkey several times on both Ubuntu 12.04 and 14.04. Each time, everything installs successfully but when i browse to https://<FQDN> , i only get the TOP NAV with no content below it. Tried going directly to https://<FQDN>/register and was presented with the register form but once submitting, i'm redirected back to https://<FQDN> again with on TOP NAV visible.

Using Chrome on OS X.

All relevant services are running and supervisor output:
securitymonkey                   RUNNING    pid 12013, uptime 0:09:20
securitymonkeyscheduler          FATAL      Exited too quickly (process log may have details)

No errors in log files.

Thanks for your help.

**Comment by monkeysecurity** [comment]
Please see #126

**Comment by peterdu77** [comment]
Thanks! That worked.
