### ISSUE TITLE
Reports to show Instance

### ISSUE THREAD

**Issue by cshears79** [Netflix/security_monkey#131]
Security Monkey is really helping to get our arms around the security gaps in our present AWS environment... But, one piece we seem to always be wondering is what Instance or Instances the violations apply to. So, a feature request/enhancement, please add Instances to the reports where applicable to save time cross checking and validating several hundred VMs. :+1:

**Comment by monkeysecurity** [comment]
Hi @cshears79.

What types of instance checks would you be interested in?  So far, security_monkey has remained a tool that only talks to the AWS API's, and does not actively interrogate instances or perform vuln scanning.  Later this week I'll be pushing v0.3.6 to master, which will report the instances attached to each security_group.

FYI - We've seen difficulties with the boto (really, the AWS API) calls related to instances in our larger accounts.  We have enough instances that these calls often time out or error out.

We would definitely welcome a pull request to see the types of checks you're interested in.

**Comment by cshears79** [comment]
@monkeysecurity, thanks for the quick reply, much appreciated!

You hit the nail on the head with instances attached to each security_group. That will go a long way in helping connect the dots from the reports. I'll pull down the latest code once released and let you know if that closes the gap for us. In large accounts, I can certainly see timeout issues being a problem/reality... we'll keep using SM and as we mature in using it, maybe kick off a pull request. Thanks again!

**Comment by monkeysecurity** [comment]
I believe this was addressed in v0.3.6 (commit 56e6308d9eece55ef042bf084cf7b373217c24e7 by @lucab back in Feb 2015)  Closing ticket.
