### ISSUE TITLE
Attempting to delete an account still results in a Foreign Key Constraint Error

### ISSUE THREAD

**Issue by Blackbaud-FrankKurzawa** [Netflix/security_monkey#141]
Issue #12 reported this problem and it was closed in December as "Fixed". However I just installed the latest Security Monkey and I'm getting the identical error when I attempt to delete an account:
IntegrityError: (IntegrityError) update or delete on table "account" violates foreign key constraint "item_account_id_fkey" on table "item"
DETAIL:  Key (id)=(3) is still referenced from table "item".
 'DELETE FROM account WHERE account.id = %(id_1)s' {'id_1': 3}

**Comment by monkeysecurity** [comment]
Hmmm so I guess we should cascade the deletes from the account down to all the items.  

The item table already cascades deletes down to revisions, issues, and comments.
The revision table already cascades deletes down to revision comments.

Let me try and push out a fix today.

**Comment by monkeysecurity** [comment]
This should be corrected in develop/master with the latest hotfix:

9473cd8fc2651632754ac96d316b62e00b999f70
