### ISSUE TITLE
Ignore certain IAM policy ARNs

### ISSUE THREAD

**Issue by echiu64** [Netflix/security_monkey#148]
AWS has some stock (unremovable) IAM managed policies that can be easily ignored by ARN:
e.g. ```arn:aws:iam::aws:policy/AmazonGlacierReadOnlyAccess``` Where "aws" is the value where the account number normally goes. Can we get an easy way to ignore this policy?

Perhaps policies should be ignored by default if they are not attached to anything?

**Comment by monkeysecurity** [comment]
When you have multiple accounts, these are somewhat annoying to deal with in security_monkey.

I like your suggestion of ignoring them if they are not attached to anything.

**Comment by systeminsightsbuild** [comment]
Agreed, ignoring AWS managed policies that are not used would eliminate a vast amount of noise.

**Comment by monkeysecurity** [comment]
I just merged @llange's PR so you can now add an ARN prefix to the ignore list and have security_monkey ignore AWS managed policies.
