### ISSUE TITLE
blank page after clicking + to add account (Web UI not compatible with Firefox/Safari/IE)

### ISSUE THREAD

**Issue by byteplumber** [Netflix/security_monkey#16]
Hi,
I click settings, then the + to add an account, and the page goes blank. The menu bar is still present, but no other content. The URI changes to #/createaccount

I've restarted the scheduler, and reinstalled the app. Nothing seems to be working. It shows that I am signed in and me (not anon).

Thanks,
eric

**Comment by monkeysecurity** [comment]
The UI now appears to work in Safari and Firefox with https://github.com/Netflix/security_monkey/commit/c2c6ced26d2fc11ca43aaeb2fe8f105bed18aa4c
