### ISSUE TITLE
flask failure when trying to create db. 

### ISSUE THREAD

**Issue by slacking42** [Netflix/security_monkey#168]
Initially i got a similar error with the flask-wtf, then I ran pip install flask-wtf as seen below.. then I got the "ImportError: No module named passlib.context"

ubuntu@ip-xx-xx-xx-xx:/usr/local/src/security_monkey$ sudo !!
sudo pip install flask-wtf
Requirement already satisfied (use --upgrade to upgrade): flask-wtf in /usr/local/lib/python2.7/dist-packages/Flask_WTF-0.9.5-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): Flask in /usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg (from flask-wtf)
Downloading/unpacking WTForms>=1.0.5,<2.0 (from flask-wtf)
  Downloading WTForms-1.0.5-py27-none-any.whl (142kB): 142kB downloaded
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages/Werkzeug-0.9.4-py2.7.egg (from Flask->flask-wtf)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/local/lib/python2.7/dist-packages/Jinja2-2.7.2-py2.7.egg (from Flask->flask-wtf)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages/itsdangerous-0.23-py2.7.egg (from Flask->flask-wtf)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/local/lib/python2.7/dist-packages/MarkupSafe-0.18-py2.7-linux-x86_64.egg (from Jinja2>=2.4->Flask->flask-wtf)
Installing collected packages: WTForms
Successfully installed WTForms
Cleaning up...
ubuntu@ip-xx-xx-xx-xx:/usr/local/src/security_monkey$ sudo -E python manage.py db upgrade
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    from security_monkey import app, db
  File "/usr/local/src/security_monkey/security_monkey/__init__.py", line 68, in <module>
    from security_monkey.datastore import User, Role
  File "/usr/local/src/security_monkey/security_monkey/datastore.py", line 32, in <module>
    from flask.ext.security import UserMixin, RoleMixin
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/exthook.py", line 81, in load_module
    reraise(exc_type, exc_value, tb.tb_next)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Security-1.7.4-py2.7.egg/flask_security/__init__.py", line 15, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/usr/local/lib/python2.7/dist-packages/Flask_Security-1.7.4-py2.7.egg/flask_security/core.py", line 18, in <module>
    from passlib.context import CryptContext
ImportError: No module named passlib.context
ubuntu@ip-xx-xx-xx-xx:/usr/local/src/security_monkey$

Am I missing something? a module perhaps,  I saw a couple errors pop up on the initial install but it seemed to finish alright.

**Comment by slacking42** [comment]
did pip install of flask-wtf, passlib, blinker, then alembic

then the db build was able to run.

**Comment by monkeysecurity** [comment]
craziness.  Can you paste the output from a "pip freeze" ?

(Right now, I have no clue what the error could be.)

**Comment by slacking42** [comment]
here you go 

Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/freeze.py", line 66, in run
    dependency_links.extend(dist.get_metadata_lines('dependency_links.txt'))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1369, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1361, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1470, in _get
    stream = open(path, 'rb')
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/python_dateutil-2.2-py2.7.egg/EGG-INFO/dependency_links.txt'

Storing debug log for failure in /home/ubuntu/.pip/pip.log

**Comment by monkeysecurity** [comment]
ha, try "sudo pip freeze"

It should output all of the libraries you have installed to your security_monkey virtualenv and their exact versions.

**Comment by slacking42** [comment]
here you go.. like I said I had to manually install the other modules by hand 

 sudo pip freeze
APScheduler==2.1.2
BeautifulSoup==3.2.1
Cheetah==2.4.4
Flask==0.10.1
Flask-Login==0.2.10
Flask-Mail==0.9.0
Flask-Migrate==1.3.1
Flask-Principal==0.4.0
Flask-RESTful==0.2.5
Flask-SQLAlchemy==1.0
Flask-Script==0.6.3
Flask-Security==1.7.4
Flask-WTF==0.9.5
Jinja2==2.7.2
Landscape-Client==14.12
M2Crypto==0.22.3
Mako==1.0.1
MarkupSafe==0.18
PAM==0.4.2
Paste==1.7.5.1
PyYAML==3.10
SQLAlchemy==0.9.2
Sphinx==1.2.2
Twisted-Core==13.2.0
Twisted-Names==13.2.0
Twisted-Web==13.2.0
WTForms==1.0.5
Werkzeug==0.9.4
alembic==0.7.6
aniso8601==0.82
apt-xapian-index==0.45
argparse==1.2.1
arrow==0.4.2
bcdoc==0.12.2
blinker==1.3
boto==2.36.0
boto3==0.0.11
botocore==0.97.0
bottle==0.12.3
chardet==2.0.1
cloud-init==0.7.5
colorama==0.2.5
configobj==4.7.2
dnspython==1.11.1
docutils==0.12
dpath==1.3.2
gunicorn==18.0
html5lib==0.999
ipaddr==2.1.11
ipython==1.2.0
itsdangerous==0.23
jmespath==0.6.1
jsonpatch==1.3
jsonpointer==1.0
meld3==0.6.10
mock==1.0.1
nose==1.3.0
oauth==1.0.1
passlib==1.6.2
pika==0.9.13
prettytable==0.7.2
psycopg2==2.5.2
py-bcrypt==0.4
pyOpenSSL==0.13
pycurl==7.19.3
pyserial==2.6
python-apt==0.9.3.5ubuntu1
python-dateutil==2.2
python-debian==0.1.21-nmu2ubuntu2
python-memcached==1.53
requests==2.2.1
security-monkey==0.3.6
six==1.5.2
ssh-import-id==3.21
supervisor==3.0b2
urllib3==1.7.1
wheel==0.24.0
wsgiref==0.1.2
zope.interface==4.0.5

**Comment by slacking42** [comment]
while I have you here.. is there any documentation to export DB from a standalone to the RDS db?

**Comment by monkeysecurity** [comment]
http://postgresguide.com/utilities/backup-restore.html

That URL should help you backup your DB and restore it to a new instance.  I typically use Navicat on OS X to play with the DB, but command line stuff is good too.

I'll play with your python issue.  It may be a good idea to create a new virtualenv.

(From the security_monkey directory)
    $ virtualenv venv
    $ source venv/bin/activate
    $ sudo python setup.py install

**Comment by slacking42** [comment]
perfect thanks, FYI this is a new install of SecMonkey I just want to be able to move the data we have to the new server using the RDS instance
