### ISSUE TITLE
SNS ignore list is by ARN but objects are saved by Name

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#171]
https://github.com/Netflix/security_monkey/blob/master/security_monkey/watchers/sns.py#L69

**Comment by mikegrima** [comment]
It looks like Boto only returns the topic ARN.  I'll throw in some parsing logic to get just the name.

**Comment by mikegrima** [comment]
Submitted PR: #209

I have tested it on my local development environment, and have confirmed that the fix works.

My concern is that this will ignore all SNS topics of this name in all accounts and regions.  Should the scope for this be later refined in the future?
