### ISSUE TITLE
Release on GitHub for 0.3.7?

### ISSUE THREAD

**Issue by moritzheiber** [Netflix/security_monkey#179]
[According to a PR](https://github.com/Netflix/security_monkey/pull/170) and [the ChangeLog](http://securitymonkey.readthedocs.org/en/latest/changelog.html) 0.3.7 was released a few weeks ago. However, it doesn't seem to have been tagged and is therefore not available from GitHub.

I would like to get 0.3.7 tagged/released on GitHub as well. Thanks!

**Comment by monkeysecurity** [comment]
Hey @moritzheiber,

The master branch has the code.  I'll get the js compiled and push the tags so you can download the release.  Thanks for letting me know.

**Comment by moritzheiber** [comment]
Just a subtle reminder that 0.3.7 is still hasn't seen a release on GitHub yet ;)

**Comment by monkeysecurity** [comment]
Hey @moritzheiber - I just pushed up v0.3.8 with static files.

https://github.com/Netflix/security_monkey/releases/tag/v0.3.8

Sorry about missing 0.3.7.  Let me know if v0.3.8 won't work for you.
