### ISSUE TITLE
SG check empty users

### ISSUE THREAD

**Issue by huntergregal** [Netflix/security_monkey#183]
I am trying to edit the iam_group auditor to alert on when a security group contains no users in it. currently I have in iam_group.py 

    def check_empty_users(self, iamgroup_item):
        """
        alert when an IAM Group has no users in it.
        """
        users = self.iamgroup_item.config.get('users', {})
        if rows not in users:
            self.add_issue(1, 'No users in security group', iamobj_item)

but it does not seem to be working. I may just be missing how the auditor functions work

**Comment by monkeysecurity** [comment]
Hey @huntergregal - The `rows` variable is not defined.

	def check_empty_users(self, iamgroup_item):
	    """
	    alert when an IAM Group has no users in it.
	    """
	    users = self.iamgroup_item.config.get('users', {})
	    if not users:
	        self.add_issue(1, 'No users in security group', iamobj_item)

I changed the if-clause a bit; this should work.

I'd love a PR when you're ready.

**Comment by huntergregal** [comment]
I got it. I also added your new if statement. It's much cleaner:

    def check_empty_users(self, iamgroup_item):
        """
        alert when an IAM Group has no users in it.
        """
        users = iamgroup_item.config.get('users', {})
        if not users:
          self.add_issue(1, 'No users in security group', iamgroup_item)

**Comment by monkeysecurity** [comment]
Neat! Does it work?

**Comment by huntergregal** [comment]
Yup! Also added a check for IAM groups with no group policies assigned. Figured why not, uses the same logic. Final code:


    def check_empty_users(self, iamgroup_item):
        """
        alert when an IAM Group has no users in it.
        """
        users = iamgroup_item.config.get('users', {})
        if not users:
            self.add_issue(1, 'No users in IAM group', iamgroup_item)

    def check_empty_group_policies(self, iamgroup_item):
       """
       alert when an IAM Group has no Group Policies attached.
       """
       grouppolicies = iamgroup_item.config.get('grouppolicies', {})
       if not grouppolicies:
           self.add_issue(1, 'No group policies attached to IAM group', iamgroup_item)


Thanks for your help!
