### ISSUE TITLE
Support for AutoScaling?

### ISSUE THREAD

**Issue by huntergregal** [Netflix/security_monkey#184]
How difficult would i be to create a module for polling and auditing autoscaling configurations?

I plan on creating this but am not sure where to start.

There will need to be a new watcher for autoscaling and a new auditor. Is the best way to start by creating a new watcher based off of the others but trying to poll for autoscale configs?

No rush, any help would be appreciated. 

Thanks

**Comment by monkeysecurity** [comment]
Shouldn't be too difficult.

You could start off with a new watcher and leave the auditor for later.  Look at sns/sqs/ses for some simple examples.

I'll help you out if you get stuck.

What kind of audit checks do you have in mind?

**Comment by huntergregal** [comment]
I'm looking to alert on AutoScaling groups that have no instances assigned to them.  My lack of AWS API knowledge is causing me some trouble. Using the other watchers as a rough template I so far have

=======================================================================
from security_monkey.watcher import Watcher
from security_monkey.watcher import ChangeItem
from security_monkey.constants import TROUBLE_REGIONS
from security_monkey.exceptions import InvalidARN
from security_monkey.exceptions import InvalidAWSJSON
from security_monkey.exceptions import BotoConnectionIssue
from security_monkey import app

import json
import re
from boto.sns import regions


class AutoScaling(Watcher):
    index = 'AutoScaling'
    i_am_singular = 'AutoScaling Topic Policy'
    i_am_plural = 'AutoScaling Topic Policies'

    def __init__(self, accounts=None, debug=False):
        super(AutoScaling, self).__init__(accounts=accounts, debug=debug)

    def slurp(self):
        """
        :returns: item_list - list of AutoScaling Item's.
        :returns: exception_map - A dict where the keys are a tuple containing the
            location of the exception and the value is the actual exception

        """
        self.prep_for_slurp()

        item_list = []
        exception_map = {}
        for account in self.accounts:
            for region in regions():
                try:
                    (autoscaling, topics) = self.get_all_topics_in_region(account, region)
                except Exception as e:
                    if region.name not in TROUBLE_REGIONS:
                        exc = BotoConnectionIssue(str(e), 'autoscaling', account, region.name)
                        self.slurp_exception((self.index, account, region.name), exc, exception_map)
                    continue

                app.logger.debug("Found {} {}".format(len(topics), AutoScaling.i_am_plural))
                for topic in topics:
                    arn = topic['TopicArn']

                    if self.check_ignore_list(arn):
                        continue

                    item = self.build_item(arn=arn,
                                           conn=autoscaling,
                                           region=region.name,
                                           account=account,
                                           exception_map=exception_map)
                    if item:
                        item_list.append(item)
        return item_list, exception_map

    def get_all_topics_in_region(self, account, region):
        from security_monkey.common.sts_connect import connect
        autoscaling = connect(account, 'autoscaling', region=region)
        app.logger.debug("Checking {}/{}/{}".format(AutoScaling.index, account, region.name))
        topics = []
        marker = None
        while True:
            topics_response = self.wrap_aws_rate_limited_call(
                autoscaling.get_all_topics,
                next_token=marker
            )
            current_page_topics = topics_response['ListTopicsResponse']['ListTopicsResult']['Topics']
            topics.extend(current_page_topics)
            if topics_response[u'ListTopicsResponse'][u'ListTopicsResult'][u'NextToken']:
                marker = topics_response[u'ListTopicsResponse'][u'ListTopicsResult'][u'NextToken']
            else:
                break
        return autoscaling, topics

    def _get_topic_subscriptions(self, autoscaling, arn):
        # paginate over each topic subscription
        token = None
        all_subscriptions = []
        while True:
            subscriptions = self.wrap_aws_rate_limited_call(
            subscriptions = self.wrap_aws_rate_limited_call(
                autoscaling.get_all_subscriptions_by_topic,
                arn,
                next_token=token
            )
            all_subscriptions.extend(
                subscriptions['ListSubscriptionsByTopicResponse']['ListSubscriptionsByTopicResult']['Subscriptions']
            )
            token = subscriptions['ListSubscriptionsByTopicResponse']['ListSubscriptionsByTopicResult']['NextToken']
            if token is None:
                break
        return all_subscriptions

    def _get_autoscaling_policy(self, attrs, account, region, arn, exception_map):
        try:
            json_str = attrs['GetTopicAttributesResponse']['GetTopicAttributesResult']['Attributes']['Policy']
            return json.loads(json_str)
        except:
            self.slurp_exception((self.index, account, region, arn), InvalidAWSJSON(json_str), exception_map)
            raise

    def _get_autoscaling_name(self, arn, account, region, exception_map):
        try:
            return re.search('arn:aws:autoscaling:[a-z0-9-]+:[0-9]+:([a-zA-Z0-9-]+)', arn).group(1)
        except:
            self.slurp_exception((self.index, account, region, arn), InvalidARN(arn), exception_map)
            raise

    def build_item(self, arn=None, conn=None, region=None, account=None, exception_map={}):
        config = {}

        try:
            attrs = self.wrap_aws_rate_limited_call(
                conn.get_topic_attributes,
                arn
            )

            config['subscriptions'] = self._get_topic_subscriptions(conn, arn)
            config['policy'] = self._get_autoscaling_policy(attrs, account, region, arn, exception_map)
            config['name'] = self._get_autoscaling_name(arn, account, region, exception_map)
        except:
            return None
        return AutoScalingItem(region=region, account=account, name=config['name'], config=config)


class AutoScalingItem(ChangeItem):
    def __init__(self, region=None, account=None, name=None, config={}):
        super(AutoScalingItem, self).__init__(
            index=AutoScaling.index,
            region=region,
            account=account,
            name=name,
            new_config=config)

=======================================================================

However running " python manage.py find_changes -a all -m AutoScaling" Is throwing the error "'Problem Connecting to autoscaling/Dev-Test/us-east-1:\nThe connection_type supplied (autoscaling) is not implemented.'
Adding ('AutoScaling', u'Dev-Test', u'us-east-1') to the exceptions list. Exception was: 'Problem Connecting to autoscaling/Dev-Test/us-east-1:\nThe connection_type supplied (autoscaling) is not implemented.'"

I have also added the new watcher to "monitors.py" with the None attribute for an auditor for now

**Comment by huntergregal** [comment]
I am still getting "Problem Connecting to autoscale/Dev-Test/sa-east-1:\n'module' object has no attribute 'autoscale'" But am not sure why.

->security_monkey.common.sts_connect   

 if connection_type == 'autoscale':
        if 'region' in args:
            region = args['region']
            del args['region']
        else:
            region = 'us-east-1'

        return boto.ec2.autoscale.connect_to_region(
            region,
            aws_access_key_id=role.credentials.access_key,
            aws_secret_access_key=role.credentials.secret_key,
            security_token=role.credentials.session_token,
            **args)

--> security_monkey_watchers.autoscale
            for region in regions:
                app.logger.debug("Checking {}/{}/{}".format(self.index, account, region.name))

                try:
                    rec2 = connect(account, 'autoscale', region=region)
                    autoscale_groups = self.wrap_aws_rate_limited_call(
                        rec2.get_all_groups
                    )
                    # Retrieve account tags to later match assigned EIP to instance
                    tags = self.wrap_aws_rate_limited_call(
                        rec2.get_all_tags
                    )

Trying to copy the ELB watcher but use the AWS API to get all current Autoscaling groups. I want to check each group for assigned instances (but that will be the auditor's job...need to get the watcher working first)

**Comment by huntergregal** [comment]
Okay. I'm really close. I just can't get the right API call to get the autoscale group details. 

I'm looking for this JSON output from the describe autoscaling group CLI command - > http://docs.aws.amazon.com/cli/latest/reference/autoscaling/describe-auto-scaling-groups.html

Then I can just check if instances has content. 

Currently I'm using 

 60             for region in regions:
 61                 try:
 62                     autoscale = connect(account, 'autoscale')
 63                     autoscale_groups = self.wrap_aws_rate_limited_call(
 64                         autoscale.get_all_groups
 65                     )
 66                     # Retrieve account tags to later match assigned EIP to instance
 67                     tags = self.wrap_aws_rate_limited_call(
 68                         autoscale.get_all_tags
 69                     )
 70                 except Exception as e:
 71                     if region.name not in TROUBLE_REGIONS:
 72                         exc = BotoConnectionIssue(str(e), self.index, account, region.name)
 73                         self.slurp_exception((self.index, account, region.name), exc, exception_map)
 74                     continue


autoscale.get_all_groups just returns [AutoScaleGroup<test>] But I need more details like in the link above.


Any ideas? I'm slowly learning the inning workings of security monkey :)

**Comment by monkeysecurity** [comment]
This looks promising.

To play with the AutoScaleGroup object, I typically do this:

    from ipython import embed
    embed()

Which will drop you into an interactive shell when it reaches that bit of code.  (Run `python manage.py find_changes -m autoscaling`, adjusting for the spelling you chose for the index.)

Then you can use ipython to run `dir` against the object and use tab completion to see what instance variables, properties, and methods are available.

If you have forked security_monkey and pushed your autoscaling code up to your own repo, let me know and I'll use that to play.

**Comment by huntergregal** [comment]
Thank you so much! You are a gentlemen and a scholar.

The ability to tab complete the API functions is exactly what I needed. I did not know about being able to use ipython to embed a shell...that's going to be super handy in the future.

 And currently it's in a private fork but I may consider opening it once I get all the features I want in it

**Comment by huntergregal** [comment]
Watcher is working :) Time to start on the auditor. The hard part was checking autoscale group for launch configs then for security groups designations in the launch config.

ipython embed() was a life saver. 

Thanks monkeysecurity!
