### ISSUE TITLE
security_monkey should support saml authentication

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#202]
security_monkey currently relies on flask-security to create users.  security_monkey should optionally allow this to be replaced/augmented with single sign-on through SAML. security_monkey should be able to obtain a list of groups to be used for authorization checks.

**Comment by monkeysecurity** [comment]
Fulfilled by #354. (Using idp/oauth2 instead of saml)

**Comment by cstewart87** [comment]
@monkeysecurity - are there still plans to add SAML support in addition to idp/oauth2?
