### ISSUE TITLE
Upgrade procedure documentation

### ISSUE THREAD

**Issue by DataSquid** [Netflix/security_monkey#205]
Hi,

We have an existing install I'm looking into upgrading to the latest release.  The documentation doesn't explicitly cover this scenario, or I've missed it.  I'm inferring from the docs that I just treat like a new deploy minus the setup of the DB, and running "sudo -E python manage.py db upgrade" should cover off any upgrade path.  Is that accurate?  And applicable for both PostgreSQL and RDS deploys?

Thanks.

**Comment by monkeysecurity** [comment]
Hey @DataSquid - Follow these directions and let me know if you run into any problems.

If these work for you, I'll add them to the documentation.

1) backup your env-config/config-deploy.py
2) Stop security_monkey and the scheduler using sudo supervisorctl.
3) mv your current security_monkey folder to a new name like security_monkey_backup
4) git clone git@github.com:Netflix/security_monkey.git into the folder where the old version was installed.
5) activate your python virtualenv and run python setup.py install
6) export SECURITY_MONKEY_SETTINGS=/path/to/env-config/config-deploy.py
7) Upgrade the DB: python manage.py db upgrade
8) Start the new security_monkey: sudo supervisorctl followed by start securitymonkey and start securitymonkeyscheduler
9) check the logs for errors and report back!

**Comment by DataSquid** [comment]
FYI Shortly after this I saw Pull Request #207 re. upgrading so I've held off upgrading unit I see if it gets committed/rejected.

**Comment by DataSquid** [comment]
Done!  Procedure worked as hoped.  Couple of notes:

- Mustn't forget to restore the config-deploy.py before install
- Needed to downgrade Dart as per issue #259 
- Needed to build web-app as per quickstart, copy it to static/
