### ISSUE TITLE
IAM Policy "SecurityMonkeyReadOnly" is Missing Redshift

### ISSUE THREAD

**Issue by stewarda** [Netflix/security_monkey#219]
Hey guys
The documentation provides an IAM policy that does not include Redshift. This results in an error when pulling in data. The correct policy should be:

    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Action": [
                    "cloudwatch:Describe*",
                    "cloudwatch:Get*",
                    "cloudwatch:List*",
                    "ec2:Describe*",
                    "elasticloadbalancing:Describe*",
                    "iam:List*",
                    "iam:Get*",
                    "route53:Get*",
                    "route53:List*",
                    "rds:Describe*",
                    "redshift:Describe*",
                    "s3:GetBucketAcl",
                    "s3:GetBucketCORS",
                    "s3:GetBucketLocation",
                    "s3:GetBucketLogging",
                    "s3:GetBucketPolicy",
                    "s3:GetBucketVersioning",
                    "s3:GetLifecycleConfiguration",
                    "s3:ListAllMyBuckets",
                    "sdb:GetAttributes",
                    "sdb:List*",
                    "sdb:Select*",
                    "ses:Get*",
                    "ses:List*",
                    "sns:Get*",
                    "sns:List*",
                    "sqs:GetQueueAttributes",
                    "sqs:ListQueues",
                    "sqs:ReceiveMessage"
                ],
                "Effect": "Allow",
                "Resource": "*"
            }
        ]
    }

**Comment by monkeysecurity** [comment]
Instead of `redshift:Describe*`, does it work with `redshift:DescribeClusters` ?

We've moved away from using wildcards and the docs should probably reflect that.

Could you test with this policy:

    "Action": [
        "ec2:describeaddresses",
        "ec2:describedhcpoptions",
        "ec2:describeinternetgateways",
        "ec2:describekeypairs",
        "ec2:describeregions",
        "ec2:describeroutetables",
        "ec2:describesecuritygroups",
        "ec2:describesubnets",
        "ec2:describetags",
        "ec2:describevpcs",
        "elasticloadbalancing:describeinstancehealth",
        "elasticloadbalancing:describeloadbalancerattributes",
        "elasticloadbalancing:describeloadbalancerpolicies",
        "elasticloadbalancing:describeloadbalancers",
        "iam:getgroup",
        "iam:getgrouppolicy",
        "iam:getloginprofile",
        "iam:getpolicyversion",
        "iam:getrole",
        "iam:getrolepolicy",
        "iam:getservercertificate",
        "iam:getuser",
        "iam:getuserpolicy",
        "iam:listaccesskeys",
        "iam:listentitiesforpolicy",
        "iam:listgrouppolicies",
        "iam:listgroups",
        "iam:listinstanceprofilesforrole",
        "iam:listmfadevices",
        "iam:listpolicies",
        "iam:listrolepolicies",
        "iam:listroles",
        "iam:listservercertificates",
        "iam:listsigningcertificates",
        "iam:listuserpolicies",
        "iam:listusers",
        "redshift:DescribeClusters",
        "rds:describedbsecuritygroups",
        "route53:listhostedzones",
        "route53:listresourcerecordsets",
        "s3:getbucketacl",
        "s3:getbucketcors",
        "s3:getbucketlocation",
        "s3:getbucketlogging",
        "s3:getbucketpolicy",
        "s3:getbucketversioning",
        "s3:getlifecycleconfiguration",
        "s3:listallmybuckets",
        "ses:getidentitydkimattributes",
        "ses:getidentitynotificationattributes",
        "ses:getidentityverificationattributes",
        "ses:listidentities",
        "ses:listverifiedemailaddresses",
        "ses:sendemail",
        "sns:gettopicattributes",
        "sns:listsubscriptionsbytopic",
        "sns:listtopics",
        "sqs:getqueueattributes",
        "sqs:listqueues",
        "sqs:receivemessage"
    ],

If you don't see errors with that, we'll update the quickstart

**Comment by stewarda** [comment]
I'll give it a whirl. Thanks!

**Comment by monkeysecurity** [comment]
Pushed to develop:

2bd5f8097a12d199a91ba5b10547164853c8483c
