### ISSUE TITLE
SQS Audit Check Invalid ARN, prevents other checks running

### ISSUE THREAD

**Issue by stewarda** [Netflix/security_monkey#220]
Hey guys
When trying to audit my first account I was unable to audit SQS due to the following error:

    Asked to audit 1 Objects
    methods: [<bound method SQSAuditor.check_sqsqueue_crossaccount of <security_monkey.auditors.sqs.SQSAuditor object at 0x7f03f9b81b90>>]
    "Given an invalid ARN: [u'arn:aws:sns:sa-east-1:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:us-east-1:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:eu-west-1:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:us-west-2:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:ap-southeast-1:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:ap-northeast-1:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:us-west-1:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:ap-southeast-2:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:eu-central-1:123456789010:glassdoor-cloudtrail-notifications']"
    Traceback (most recent call last):
      File "manage.py", line 141, in <module>
        manager.run()
      File "/usr/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 397, in run
        result = self.handle(sys.argv[0], sys.argv[1:])
      File "/usr/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 376, in handle
        return handle(app, *positional_args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/commands.py", line 145, in handle
        return self.run(*args, **kwargs)
      File "manage.py", line 48, in find_changes
        sm_find_changes(accounts, monitors)
      File "/apps/security_monkey/security_monkey/scheduler.py", line 53, in find_changes
        _find_changes(accounts, monitor, debug)
      File "/apps/security_monkey/security_monkey/scheduler.py", line 80, in _find_changes
        au.audit_these_objects(items_to_audit)
      File "/apps/security_monkey/security_monkey/auditor.py", line 113, in audit_these_objects
        method(item)
      File "/apps/security_monkey/security_monkey/auditors/sqs.py", line 87, in check_sqsqueue_crossaccount
        raise InvalidARN(topic_arn)
    security_monkey.exceptions.InvalidARN: "Given an invalid ARN: [u'arn:aws:sns:sa-east-1:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:us-east-1:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:eu-west-1:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:us-west-2:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:ap-southeast-1:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:ap-northeast-1:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:us-west-1:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:ap-southeast-2:123456789010:glassdoor-cloudtrail-notifications', u'arn:aws:sns:eu-central-1:123456789010:glassdoor-cloudtrail-notifications']"

The audit would stop and so no information was pulled in for other checks such as security groups

Initially I was using a wildcard instead of a region to allow consolidation of Cloudtrail logs from multiple accounts into a central account, but that did not work. I then modified the IAM policy to specify each region (as above) for a single account and had the same problem. Ultimately I deleted the policy, ran the audit and was then able to flag the the queue in the ignore list. 
Based on this:
Issue 1 - What was invalid in the arn ?
Issue 2 - Is there anyway to ignore the exception for that check and carry on with the audit ?

**Comment by monkeysecurity** [comment]
Hey @stewarda.  I believe @Qmando also had this issue recently.  I suspect the "invalid ARN" is because it is expecting a single ARN and your policy provides a list.

The SQS auditor should be updated to be able to handle lists.

While we're working on a fix, you may want to comment out the line `raise InvalidARN(topic_arn)` and add `pass` in its place.

    try:
        account_numbers.append(str(re.search('arn:aws:sns:[a-z-]+-\d:([0-9-]+):', topic_arn).group(1)))
    except:
        # raise InvalidARN(topic_arn)
        pass

If you could add the policy attached to this Queue, it would greatly assist in the debugging.  Feel free to comment out account numbers or other sensitive data; I'm mostly interested in the format.  

like this:

    {
      "Version": "2008-10-17",
      "Id": "",
      "Statement": [
        {
          "Resource": "arn:aws:sns:*:012345678912:blah",
          "Effect": "Allow",
          "Sid": "",
          "Action": "SQS:SendMessage",
          "Condition": {
            "StringEquals": {
              "aws:SourceArn": "arn:aws:sns:*:012345678912:blah"
            }
          },
          "Principal": {
            "AWS": "*"
          }
        }
      ]
    }

**Comment by Qmando** [comment]
I also temporarily fixed this by also commenting out the exception and adding pass. This line has a similar check, which you may also want to comment out just in case: https://github.com/Netflix/security_monkey/blob/master/security_monkey/auditors/sns.py#L87

**Comment by monkeysecurity** [comment]
Reproduced this and upgrading it to a major blocker.  Will have a hotfix out by end of day.

**Comment by monkeysecurity** [comment]
Pushed up a commit to a new branch:

427ab1efbc3c3d2045c56ec8a1f06081da34eb81 on branch hotfix/issue_220_sqs_invalid_arn_check.

I'll test it a bit before merging it in.  It works well so far, but I may want to further abstract the ARN parsing.  The SNS auditor likely has the same problems.

**Comment by stewarda** [comment]
Sorry for the delay, this is a snippet of the policy. It was used for Cloudtrail to allow multiple accounts to write to a single S3 bucket (all regions within the account hence the wildcard)

{
  "Version": "2008-10-17",
  "Id": "arn:aws:sqs:us-west-2:737575273253:myqueue",
  "Statement": [
    {
      "Sid": "Sid123456789",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "SQS:SendMessage",
      "Resource": "arn:aws:sqs:us-west-2:1234567890:myqueue",
      "Condition": {
        "ArnEquals": {
          "aws:SourceArn": [
            "arn:aws:sns:*:1234567890:mynotification",
            "arn:aws:sns:*:2345678901:mynotification",
          ]
        }
      }
    }
  ]
}

**Comment by monkeysecurity** [comment]
The changes have been merged to develop and master.  I'll bump the version number tomorrow and update the changelog too.

SQS and SNS were both updated.  A new ARN class assists with the parsing of ARNs or other identifiers that are often used in their place (like `aws:sourceowner:<account_number>`).  It also helps extract ARN's from the potentially complicated condition section of an SQS/SNS policy.

As an S3 ARN doesn't typically include the account number, security_monkey is flagging any S3 ARN found within the condition section of an SQS queue or an SNS topic.  At some point in the near future I'll update the data model to allow security_monkey to auto detect if the S3 bucket is friendly or unknown.

It can also deal with a policy like the one @stewarda provided where multiple ARNs are provided in a list.

All exception raising has been removed from the SQS/SNS auditor and replaced with logging and/or adding an issue.

Please pull down the latest and reopen this issue if you find any scenario it does not properly handle.
