### ISSUE TITLE
Risk Scoring Improvement

### ISSUE THREAD

**Issue by markofu** [Netflix/security_monkey#231]
Change the risk scoring from numbers out of 10 to High/Medium/Low.

The latter system is easier to understand at a glance and, additionally, easier to prioritise.

**Comment by monkeysecurity** [comment]
User-configurable issue scoring might (?) be neat as well.

**Comment by markofu** [comment]
I can definitely see the value in that but it'd be nice to have that capability restricted to something role-based. I'm not sure I'd like engineers simply changing the severity because they don't agree with it :) Thoughts?

**Comment by monkeysecurity** [comment]
closing as a duplicate of #157. (general auditor rewrite)
