### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by brian-olson** [Netflix/security_monkey#237]
Is there a way to add, list, or delete user accounts for Security Monkey? I'm not seeing anything in the documentation other than how to register as a user via the web ui. Since there is no confirmation of new accounts I've disabled registration but now need a method to register new accounts on the server itself as well as to list the current users. Thanks!

**Comment by ollytheninja** [comment]
See #114

**Comment by brian-olson** [comment]
Heya @ollytheninja - I was hoping there might be an API or even a direct db query until the Web UI is completed.

**Comment by monkeysecurity** [comment]
Hey @ollytheninja - would #317 close this issue or are they different things?

**Comment by ollytheninja** [comment]
I think it would

**Comment by monkeysecurity** [comment]
Closing issue as this has been merged in thanks to @ollytheninja .
