### ISSUE TITLE
security_monkey should separate SG ingress/egress audit checks

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#239]
Users have requested that the audit checks for security group ingress and egress rules be separated to help them focus on fixing their ingress rules before analyzing their egress rules.

Should be a pretty simple modification.

**Comment by moritzheiber** [comment]
:+1:

**Comment by AlexClineBB** [comment]
:+1:

**Comment by monkeysecurity** [comment]
Closed by #323
