### ISSUE TITLE
SNS watcher only accepts alphanumeric (plus hyphen) in names.  Underscores are not allowed.

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#240]
https://github.com/Netflix/security_monkey/blob/develop/security_monkey/watchers/sns.py#L128

The regex should be extended to also allow underscores.

**Comment by monkeysecurity** [comment]
Maybe try and find a reference in the AWS docs describing the allowed characters in the SNS name.

**Comment by mikegrima** [comment]
[screen shot 2015-10-29 at 9 04 55 am](https://cloud.githubusercontent.com/assets/11035926/10824077/26fd1fc2-7e1c-11e5-8adb-7c269d4230d0.png)

**Comment by monkeysecurity** [comment]
merged in.
