### ISSUE TITLE
Invalid ARNs not handled consistently

### ISSUE THREAD

**Issue by ghost** [Netflix/security_monkey#248]
s3 auditor just logs ARNs it couldn't parse
SNS and SQS auditors make it an issue

**Comment by mikegrima** [comment]
@OllyTheNinja-Xero Are you referring to this: 
https://github.com/Netflix/security_monkey/blob/master/security_monkey/auditors/s3.py#L118-L123 ?

**Comment by OllyTheNinja-Xero** [comment]
Yes and https://github.com/Netflix/security_monkey/blob/master/security_monkey/auditors/s3.py#L125-L129

**Comment by mikegrima** [comment]
Cool -- I can make a quick PR for it (or you can) -- up to you.

**Comment by monkeysecurity** [comment]
@mikegrima - Has this been taken care of yet?

**Comment by mikegrima** [comment]
@monkeysecurity Forgot about it... Doing it now.

**Comment by mikegrima** [comment]
Will skip lines https://github.com/Netflix/security_monkey/blob/master/security_monkey/auditors/s3.py#L125-L129, since it appears that the `inspect_policy_allow_all()` method handles that (as indicated in the comment).

Making a quick patch for the other lines, however.

**Comment by mikegrima** [comment]
Sent PR: #324 

At some point, we may want to include similar auditing for IAM Root account checks, like I have implemented in the ElasticSearch auditor: https://github.com/Netflix/security_monkey/blob/develop/security_monkey/auditors/elasticsearch_service.py#L105-L128

**Comment by monkeysecurity** [comment]
I believe this is fixed. Closing.
