### ISSUE TITLE
SNS policy check fails on non ARN Principal

### ISSUE THREAD

**Issue by ghost** [Netflix/security_monkey#257]
SNS topic policies can have ARN, Federation and Service however the auditor only recognizes ARNs and fails with 'Auditor could not parse ARN'

Should add issue that specifies what Principal and Principal type it is unhappy with.
Not sure what score it should have or whether it should match against a known list of Federations and Services

**Comment by monkeysecurity** [comment]
Could you give an example of federation or service principals?

Would it be something like `"principal": "lambda.amazonaws.com"` ?

I was under the impression the principal field in a resource policy was only for IAM ARNs and that any resource ARNs would need to be specified somewhere under the conditions section.

**Comment by mikegrima** [comment]
@monkeysecurity Principals can indeed be services.  Perhaps we should permit `*.amazonaws.com` as valid?  I'm not aware of AWS services that are more than 3 domain levels deep, so we could scope it to that for future AWS service additions.

**Comment by monkeysecurity** [comment]
Fixed with PR #328
