### ISSUE TITLE
Who preformed an action

### ISSUE THREAD

**Issue by shayb01** [Netflix/security_monkey#258]
Hi,
I just installed Security Monkey and started to get alerts.
I cant find which user account performed an action.

Is there a way to tell Security Monkey to add the name of the user who performed an action.
Example:
Security Group was changed, i can see the diff JSON and to understand what has been changed but i can't tell which user performed the action

**Comment by monkeysecurity** [comment]
Hey @shayb01 - Good question.

So security_monkey asks the AWS API's what things look like, but it doesn't currently have information on who changed something.

CloudTrail is your best bet for finding out who changed something.  We've talked about having CloudTrail integrate with security_monkey for a while but haven't coded anything up in a releasable form.
