### ISSUE TITLE
Encrypted DB

### ISSUE THREAD

**Issue by travissc** [Netflix/security_monkey#26]
There is a ton of valuable data in the postgres db.  Any plans on adding encryption?

**Comment by monkeysecurity** [comment]
We can rely on AWS's RDS encryption for this:

http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html

**Comment by kevgliss** [comment]
@monkeysecurity you might be able to implement something like this (http://sqlalchemy-utils.readthedocs.org/en/latest/data_types.html?highlight=encrypted#sqlalchemy_utils.types.encrypted.EncryptedType)  relatively easily... Of coarse I would only recommend this on columns that you don't need query on... maybe just the raw json?

**Comment by monkeysecurity** [comment]
FYI - security_monkey does query on the raw JSON field in the "Search Config" box in the web UI.
