### ISSUE TITLE
Installation Documentation Updates

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#274]
Feedback from a recent install:
1. AWS no longer allows "Custom Policy" as a choice on the policy selection screen (after the role type selection). Need to create policy first before beginning with the role creation so that my policy shows up under "Customer Managed Policies"
2. Change chmod instructions to say "400" instead of "600"
3. In compiling the web app one has to run "get" before "build"
   
   sudo /usr/lib/dart/bin/pub get 
4. Inconsistency with log file naming. We have .error.log and .access.log but, -deploy.log. Why?
5. When you provide the screenshot of the user being able to reach the security monkey server, make sure it is https://. Based on the recommendations :80 is not open.
6. For most instructions to be executed on the command line you have provided the actual commands. 

But, the following seems to be in text. Easy to miss if people are just copy-pasting your command line instructions. (I did :P)
"Copy security_monkey/supervisor/security_monkey.conf to /etc/supervisor/conf.d/security_monkey.conf and make sure it points to the locations where you cloned the security monkey repo"

Will update these on Friday.

**Comment by mikegrima** [comment]
Updated 2, 3.
