### ISSUE TITLE
not reading s3

### ISSUE THREAD

**Issue by mugzy** [Netflix/security_monkey#285]
I have Security Monkey setup and working great except s3.  I noticed there were no S3 issues being generated so I checked the logs.

Here is what I found:

Adding ('s3', u'Account 1') to the exceptions list. Exception was: 'Problem Connecting to s3/Account 1/None:\ntimed out' [in /usr/local/src/security_monkey/security_monkey/watcher.py:161]

Any ideas?

**Comment by monkeysecurity** [comment]
Woa. That's interesting.  So that exception is happening somewhere in the try/except clause from lines 126 to 129:

https://github.com/Netflix/security_monkey/blob/master/security_monkey/watchers/s3.py#L125

```
            try:
                s3conn = connect(account, 's3', calling_format=OrdinaryCallingFormat())
                all_buckets = self.wrap_aws_rate_limited_call(
                    s3conn.get_all_buckets
                )
            except Exception as e:
                exc = BotoConnectionIssue(str(e), 's3', account, None)
                self.slurp_exception((self.index, account), exc, exception_map)
                continue
```

If you manually call the s3 watcher, I'm assuming you get the same error?

`python manage.py find_changes -m s3 -a "Account 1"`

I'm not sure why it would be timing out on that technology but not on the others.  

If you open a python shell, does this work?

```
>>> import boto3
>>> s3 = boto3.resource('s3')
>>> for bucket in s3.buckets.all():
        print(bucket.name)
```

(So far, I'm not exactly sure what could be causing this.)

**Comment by mugzy** [comment]
The boto3 call in the python shell works fine.

The direct run of the watcher resulted in the exception below and took at least 5-10min to timeout.

'Problem Connecting to s3/Account 1/None:\ntimed out'
Adding ('s3', u'Account 1') to the exceptions list. Exception was: 'Problem Connecting to s3/Account 1/None:\ntimed out'
Asked to audit 0 Objects
methods: [<bound method S3Auditor.check_acl of <security_monkey.auditors.s3.S3Auditor object at 0x7f11bb246650>>, <bound method S3Auditor.check_policy of <security_monkey.auditors.s3.S3Auditor object at 0x7f11bb246650>>]

Thanks!

**Comment by monkeysecurity** [comment]
Is there anything unusual about your account?  Do you have a really large number of s3 buckets?  Are you in the civilian AWS cloud or in something like govcloud?  Are you in one of the newer AWS regions?

Could you do a `pip freeze | grep boto` and make sure they're modern versions?

**Comment by mugzy** [comment]
16 buckets
Not in any of the new regions
Normal civilian AWS account

boto==2.38.0
boto3==1.2.1
botocore==1.3.7

**Comment by finalriposte** [comment]
It's a long shot but any chance you are using proxies?  I know that I have issues between the way boto worked versus botocore handle proxies - boto reads the proxies from boto.cfg, botocore gets it from environment settings.

**Comment by mugzy** [comment]
That was it!  I added the proxy to the .cfg and it all works now.  Thanks for such a great tool!
