### ISSUE TITLE
Missing quote in Policy

### ISSUE THREAD

**Issue by DataSquid** [Netflix/security_monkey#287]
The current JSON for SecurityMonkeyReadOnly at http://securitymonkey.readthedocs.org/en/latest/quickstart.html is missing the closing quote in the line

    "es:Describe*,

**Comment by monkeysecurity** [comment]
Thanks - will get this updated soon.  I believe @mikegrima has updated with the exact permissions so wildcards are not required as well.

**Comment by mikegrima** [comment]
PR #293 submitted for this issue.

**Comment by monkeysecurity** [comment]
https://github.com/Netflix/security_monkey/pull/293 was merged
