### ISSUE TITLE
Development with Vagrant

### ISSUE THREAD

**Issue by cstewart87** [Netflix/security_monkey#288]
I'm trying to setup a dev environment through Vagrant.  I have Nginx and a PostgreSQL DB running in my vagrant VM and a synced_folder setup for my security_monkey code.

Question is, is there any way to run the development API server (https://github.com/Netflix/security_monkey/blob/master/docs/dev_setup_ubuntu.rst#start-the-security-monkey-api) through my Vagrant VM?  It always starts at 127.0.0.1:5000, but that page doesn't load anything.

**Comment by monkeysecurity** [comment]
I'm not familiar with Vagrant. You should be able to pass the host and port to runserver or run-api-server.  Looks like this Q was from a while ago, so I'm going to close it.
