### ISSUE TITLE
Issue starting SecMonkey Import Error: Cryptography

### ISSUE THREAD

**Issue by jimmysharrrison** [Netflix/security_monkey#294]
I was trying to update security monkey, and hit the cannot import send_email error listed in another issue so I backed up my folder and tried a fresh git clone.  When I try to start security monkey through the supervisor it stalls and goes fatal.  The error logs have this traceback:

ImportError: No module named cryptography
Traceback (most recent call last):
  File "/usr/local/src/security_monkey/manage.py", line 22, in <module>
    from security_monkey.scheduler import run_change_reporter as sm_run_change_reporter
  File "/usr/local/src/security_monkey/security_monkey/scheduler.py", line 15, in <module>
    from security_monkey.monitors import all_monitors, get_monitor
  File "/usr/local/src/security_monkey/security_monkey/monitors.py", line 12, in <module>
    from security_monkey.watchers.iam.iam_ssl import IAMSSL
  File "/usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py", line 28, in <module>
    from cryptography import x509
ImportError: No module named cryptography

**Comment by monkeysecurity** [comment]
Hey @jimmysharrrison - In v0.3.8 we replaced the M2Crypto dependency with a dependency on the Cryptography package.

https://github.com/Netflix/security_monkey/blob/master/docs/changelog.rst#v038-2015-08-28

You should be able to manually run `pip install cryptography==1.0.2` or do a `python setup.py develop` or do a `pip install -r requirements.txt` to have your virtualenv pickup the new dependencies.

FYI - there are upgrade instructions in this issue (that should probably be pushed to the docs)
https://github.com/Netflix/security_monkey/issues/205

**Comment by jimmysharrrison** [comment]
FYI I managed to get security monkey running without errors, turns out I couldn't install the cryptography package because I was missing libffi-dev.  Anyone that runs into this issues should make sure they have python-dev and libffi-dev installed.  I am still getting 404's from nginx however.
