### ISSUE TITLE
Adding new audit rules

### ISSUE THREAD

**Issue by rakeshkotha** [Netflix/security_monkey#297]
Hi Guys,

Is there an api to add new set of audit rules? i am running on the latest version of the security monkey.

**Comment by jozzas** [comment]
Assuming you are already picking up the required detail with a watcher, you'll need to write an auditor in Python to generate audit items based on the collected data. Adding an auditor wasn't too challenging when I did it. Have a look at the auditors folder and see how you go.

**Comment by monkeysecurity** [comment]
I wonder how difficult it would be to allow users to plug in the rulesets from projects like Scout2 or CloudSploit:

https://github.com/iSECPartners/Scout2
https://github.com/cloudsploit/scans

I think that'd be pretty neat, and I'd love the inter-project collaboration.  I wonder if the other projects would appreciate that.

**Comment by syphon7** [comment]
It would be great if we could use their rulesets in sec monkey

**Comment by monkeysecurity** [comment]
closing as a duplicate of #157. (general auditor rewrite)

**Comment by monkeysecurity** [comment]
Spoke with the author of Scout2 (Loic).

The re-architecture will have a new audit system. We're hoping to implement pluggable audit plugins in a format that can be shared between the libraries.  We have not yet sketched out an architecture or anything.
