### ISSUE TITLE
monitoring other (instead of AWS) platforms by using security monkey

### ISSUE THREAD

**Issue by westlifezs** [Netflix/security_monkey#298]
Hello security monkey team,

thanks for answering my previous question regarding security monkey setup.
We like the security monkey features very much.
Besides AWS, we also want to monitor other platforms including openstack, local DC, etc.
If I want to further extend security monkey's function to monitor openstack, then could you please point me to a starting point? 
Is there any existing APIs/modules that I can rely upon within security monkey repo?
I can pull data from our cloud and translate into any format that security monkey support.
We want to utilize security monkey front end to present results based on the data we collected at our environment.

Any comments will be highly appreciated!

Su
 

PS: This is definitely a question instead of an issue. but I do not know why I cannot change the label to question. It will be great if someone could help to change the label appropriately.

**Comment by mikegrima** [comment]
Hello @westlifezs 

It should be possible to audit other technologies, but we have not done this yet.  At the top of my head, you would need to implement your own auditor and watcher.

For a "getting started" point, please refer to the Contributing instructions: https://github.com/Netflix/security_monkey/blob/master/docs/contributing.rst

Please feel free to submit PR's!

**Comment by westlifezs** [comment]
thank you very much for your info.
I briefly read auditor.py and watcher.py under securitymonkey folder.
It appears to me that watcher is monitoring the config change over time and auditor is checking if there is anything like "policy violation". I can do both through our own data source. 
My question is, what can of data format should I feed into security monkey front end to have it displayed?
I have been trying to understand the code but I still have not found the answer.

thanks in advance!

Su

**Comment by westlifezs** [comment]
basically we want to encapsulate our auditor and watcher and present violated policies directly to security monkey UI. The reason we want to this because we want to make policy as an input rather than hard coded it into the auditor as we have lots of policies need to be checked at our local environment. Could you let us know how to present the policy violation result directly to security monkey UI?

Thanks,

**Comment by westlifezs** [comment]
this question has been answered by Patrick.
For someone who may want to know details at a later time, please find the answer from Patrick Kelley:

"The UI can be extended.  It's an angular app written in dart.

Currently the web UI displays Items, their attached ItemRevisions, and all policy violations are saved as an ItemAudit entry, attached to the Item.  Under settings, there is support to enable or disable a specific policy violation.  This is saved as an AuditorSetting entry underneath the hood, and could itself probably be improved.

https://github.com/Netflix/security_monkey/blob/master/security_monkey/datastore.py#L144"
