### ISSUE TITLE
dart bug: folder structure changed and dead "packages" pointer

### ISSUE THREAD

**Issue by westlifezs** [Netflix/security_monkey#300]
Hello,

It seems like dart changed the build folder structure for version 1.12.2
In the tutorial under session " Compile the web-app from the Dart code:"

There is one cmd: "sudo /bin/cp -R /usr/local/src/security_monkey/dart/build/web/* /usr/local/src/security_monkey/security_monkey/static/".

The cmd will fail because "/usr/local/src/security_monkey/dart/build/web/" is no longer exist.
the new web folder is at "/usr/local/src/security_monkey/dart/web".

However, you cannot directly copy the new web folder as it contains a pointer "packages" pointing to one level above , i.e. "../packages". If we directly copy this folder, the packages within web will become a dead pointer.

One possible solution is to copy the "/usr/local/src/security_monkey/dart/build/web/" to "/usr/local/src/security_monkey/security_monkey/static/" and fix the "packages" pointer.

I am not very familiar with dart. If anyone could look into this issue, then it will be great. 
I am more than happy to work with the team to resolve this issue.

**Comment by westlifezs** [comment]
I can work around this issue by wget "sudo wget https://github.com/Netflix/security_monkey/releases/download/v0.4.1/static.tar.gz".
And uncompress static.tar.gz into "/usr/local/src/security_monkey/security_monkey".
However, a fix will be needed in order to have a local compiled version to be installed.

**Comment by monkeysecurity** [comment]
I still get a build and web folder:

```
~ ❯❯❯ dart --version
Dart VM version: 1.12.2 (Wed Oct 21 06:56:12 2015) on "macos_x64"

~ ❯❯❯ git clone git@github.com:Netflix/security_monkey.git
Cloning into 'security_monkey'...
remote: Counting objects: 4742, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 4742 (delta 20), reused 0 (delta 0), pack-reused 4709
Receiving objects: 100% (4742/4742), 8.24 MiB | 7.79 MiB/s, done.
Resolving deltas: 100% (2504/2504), done.
Checking connectivity... done.

~ ❯❯❯ cd security_monkey/dart

~/d/s/dart ❯❯❯ pub get
Resolving dependencies...
Downloading aws_policy_expander_minimizer 0.0.5...
Got dependencies!
Precompiling dependencies...
Loading source assets...
...
[Info from Dart2JS]:
Took 0:00:23.686300 to compile security_monkey|web/main.dart.
Built 318 files to "build".

~/d/s/dart ❯❯❯ ls
build        lib          packages     pubspec.lock pubspec.yaml web

~/d/s/dart ❯❯❯ cd build

~/d/s/d/build ❯❯❯ ls
web
```

I'm not sure why your directory structure would be different.

**Comment by westlifezs** [comment]
I tried it just now on my ubuntu box. But it still does not work for me.
I cannot see the directory. 
Here is part of my screenshot:
su@ubuntu:/usr/local/src/security_monkey/dart$ sudo /usr/lib/dart/bin/pub get
Resolving dependencies... (4.1s) 
Downloading angular 1.1.0...
Downloading analyzer 0.22.4...
Downloading angular_ui 0.6.8...

.......
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
Got dependencies!
Precompiling dependencies... 
Loading source assets... 
Loading dart_to_js_script_rewriter, di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformers... (4.4s) 
Loading angular transformers... (1.0s) 
Precompiled angular_ui, dart_to_js_script_rewriter, di, initialize, smoke and web_components.
Precompiling executables... 
Loading source assets... 
Loading di/module_transformer and smoke/src/default_transformer transformers... 
Precompiled angular:pub_build.
Precompiled angular:parser_generator_for_spec.
Precompiled angular:template_cache_generator.
Precompiled angular:expression_extractor.
su@ubuntu:/usr/local/src/security_monkey/dart$ sudo /usr/lib/dart/bin/pub build
Loading source assets... 
Loading dart_to_js_script_rewriter, di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformers... 
Loading angular transformers... (1.5s) 
Building security_monkey... (29.1s) su@ubuntu:/usr/local/src/security_monkey/dart$ ls build/
su@ubuntu:/usr/local/src/security_monkey/dart$ ls build/
su@ubuntu:/usr/local/src/security_monkey/dart$ dart --version
Dart VM version: 1.12.2 (Wed Oct 21 14:13:58 2015) on "linux_x64"

**Comment by westlifezs** [comment]
I tried again on a fresh AWS ubuntu box. the result is the same.

**Comment by westlifezs** [comment]
After I script the whole process, I am no longer hitting this error. thanks for your answers
