### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by cstewart87** [Netflix/security_monkey#304]
When is the next release planned for?  Looking forward to the updates from #301 :+1:

**Comment by monkeysecurity** [comment]
Yeah that's a good one if you have an account with LOTS of IAM roles.

If I have some time tomorrow, I'll consider putting a release together.  Otherwise it'll be next week.

**Comment by cstewart87** [comment]
Any updates on a new release?

**Comment by monkeysecurity** [comment]
Hey @cstewart87 .  This performed pretty well in my test cluster the last two weeks.  I'm running the dev branch in our main cluster now where it's looking at a lot more accounts.  I'll push a release as soon as I'm comfortable that it's not going to cause anyone headaches.

**Comment by cstewart87** [comment]
Awesome!  Thanks for the update :+1:

**Comment by monkeysecurity** [comment]
This week.  We'll have v0.5.0 out by Friday.

HOPEFULLY we'll have @ollytheninja's #317 (RBAC) and #318 (APScheduler v3).
