### ISSUE TITLE
Invalid JSON - SecurityMonkeyReadOnly

### ISSUE THREAD

**Issue by subbu05** [Netflix/security_monkey#311]
The JSON content that is showed in the document - http://securitymonkey.readthedocs.org/en/latest/quickstart.html, section 
Paste in this JSON with the name “SecurityMonkeyReadOnly”:
"es:Describe*,

Expected 
"es:Describe*",

**Comment by mikegrima** [comment]
Hello @subbu05 - This has been fixed in the develop branch. We are currently working on some additional bug fixes before merging the fix into the master branch.
