### ISSUE TITLE
scheduler stalled after unclean shutdown

### ISSUE THREAD

**Issue by pdbogen** [Netflix/security_monkey#315]
I'm supposing I killed scheduler in the middle of a transaction. C'est la vie. The service should be able to recover on subsequent launch:

```
2016-04-16 00:18:16,188 WARNING: Database Exception in Datastore::get_all_ctype_filtered. Sleeping for a few seconds. Attempt 1. [in /src/security_monkey/datastore.py:251]
2016-04-16 00:18:16,188 DEBUG: Exception: Can't reconnect until invalid transaction is rolled back (original cause: InvalidRequestError: Can't reconnect until invalid transaction is rolled back) u'SELECT item.id AS item_id, item.cloud AS item_cloud, item.region AS item_region, item.name AS item_name, item.tech_id AS item_tech_id, item.account_id AS item_account_id, item.latest_revision_id AS item_latest_revision_id \nFROM item JOIN technology ON item.tech_id = technology.id JOIN account ON item.account_id = account.id \nWHERE technology.name = %(name_1)s AND account.name = %(name_2)s' [immutabledict({})] [in /src/security_monkey/datastore.py:252]
```

**Comment by pdbogen** [comment]
Hmm, I may have misdiagnosed the cause of this. Possibly it's because Scheduler started before/while PostgreSQL was starting; restarting scheduler resolved the errors. (Making these errors fatal means that my code would have restarted it automatically, so perhaps that's a sufficient fix.)

**Comment by monkeysecurity** [comment]
Yeah it looks like the code will try 5 times and then raise the exception up and let the scheduler (or supervisor?) restart it all.

https://github.com/Netflix/security_monkey/blob/master/security_monkey/datastore.py#L257

So I think the code is good as is?  Is that your assessment @pdbogen ?

**Comment by pdbogen** [comment]
Ah, that'd be fine, except the scheduler itself didn't terminate. I guess apscheduler ends up eating that exception for some reason. I don't know nearly enough about those bits to recommend a fix.

(I had to manually kill scheduler and let it get restarted.)

For the sake of clarity, I've attached a more detailed [logs.txt](https://github.com/Netflix/security_monkey/files/222085/logs.txt)
. There are a few key times to notice:
* From 2016-04-16 00:17:37,535 until just before 2016-04-16 00:17:39,865, Postgres was still starting up, and so was not responsive on TCP.
* With the run beginning on 2016-04-16 00:17:39,865, Postgres responds to TCP but is apparently not in a "ready" state
, starting at one attempt while Postgres was still non-responsive.
* At 2016-04-16 00:18:16,188 we see the first database exception
* At 2016-04-16 00:18:41,219 it raises an exception after 5 failed attempts (as you point out) 

The very last line of the log is where I kill the scheduler so it gets restarted.

**Comment by monkeysecurity** [comment]
Is it possible that #316 corrects this?  I just merged that into develop today .

**Comment by pdbogen** [comment]
I'll test if I can repro. It'll take me a bit, end-to-end build process ain't exactly quick.

**Comment by pdbogen** [comment]
Hmm, I wasn't able to repro easily, and unfortunately since security monkey is humming along nicely now I don't have a lot of free time to try to get it. This is a pretty race-y issue anyway.

The issue _does_ look similar and I expect raising fewer exceptions to apscheduler and cleaning up better will help the issue I observed here, as well.

As far as I'm concerned, you can close this out; if I do run into it again in the future I can reopen and/or open a new bug. Plus in a few weeks I should have more time to allocate here.
