### ISSUE TITLE
Report  customization

### ISSUE THREAD

**Issue by skdubey** [Netflix/security_monkey#32]
Hi,

Is it possible to send Monthly report instead of Daily ?

**Comment by monkeysecurity** [comment]
Woa this is old.  Closing as this isn't in the current roadmap.

I believe it would be a simple change to this line though:

https://github.com/Netflix/security_monkey/blob/develop/security_monkey/scheduler.py#L142

```
            if auditors:
                scheduler.add_cron_job(_audit_changes, hour=10, day_of_week="mon-fri", args=[account, auditors, True])
```
