### ISSUE TITLE
404 files not found.

### ISSUE THREAD

**Issue by Psyered** [Netflix/security_monkey#320]
Hi,
Installed security monkey following Quick Start Guide.

Chrome developer tools console log:

Refused to load the stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700' because it violates the following Content Security Policy directive: "style-src 'self' https://fonts.googleapis.com".
http://secmonkey/packages/angular_ui/css/angular.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://secmonkey/packages/browser/dart.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://secmonkey/packages/angular_ui/css/angular.css Failed to load resource: the server responded with a status of 404 (Not Found)

I really cant find this files. Web UI doesn't work as expected.
Installed on Centos 7.

**Comment by monkeysecurity** [comment]
Which CSP policy did you use?

You should have something similar to this in your nginx config:

```
add_header Content-Security-Policy "default-src 'self'; font-src 'self' https://fonts.gstatic.com; script-src 'self' https://ajax.googleapis.com; style-src 'self' https://fonts.googleapis.com;
```

That would alleviate the first problem.

The 404's will be another issue.  Your nginx config should have a route to your static files:

```
location / {
        root SOMEPATH/securitymonkey/security_monkey/static;
        index ui.html;
    }
```

Navigate to that folder and ensure the files are actually there.

If not, please follow the instructions to build the web UI:
http://securitymonkey.readthedocs.org/en/latest/quickstart.html#clone-the-security-monkey-repo

**Comment by Psyered** [comment]
I need to build web UI.
Getting error - 
[Error from InjectorGenerator on security_monkey|web/main.dart]:
Unable to resolve asset ID for "dart:core"

**Comment by monkeysecurity** [comment]
Hey @psyered - You'll need to pin to dart 1.12.1 or earlier.  There's a breaking change that we haven't worked out yet.

If you're on OS X - you can download from here: https://www.dartlang.org/downloads/archive/

If you're on Ubuntu:

```
sudo curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
sudo curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list
sudo apt-get update
sudo apt-get install dart=1.12.2-1
```
( from https://github.com/Netflix/security_monkey/blob/master/docs/dev_setup_ubuntu.rst )
