### ISSUE TITLE
Authentication via REST API

### ISSUE THREAD

**Issue by cstewart87** [Netflix/security_monkey#326]
Is there a way to do this?  If so, would someone add an example to the documentation?

**Comment by monkeysecurity** [comment]
Duplicate of #87.

Answer is no.  Flask-Security is suppose to support this, but it's implementation is pretty bad, imho.  Would gladly take a PR following the design from #87:

> have a UI where each user can create/disable/delete an API key and save that in the User field. Then, extend AuthenticatedResource to check for a authentication_token header. Admin users would be able to disable/delete any users' tokens.
