### ISSUE TITLE
Not able to launch the application

### ISSUE THREAD

**Issue by santoshpatha12** [Netflix/security_monkey#346]
Hi Team,

I have setup the security monkey in Ubuntu and done all the configuration as per the below link. I am not able to launch the application. Please help me to resolve the same. Thank you.

**Link: http://securitymonkey.readthedocs.io/en/latest/quickstart.html**

Regards,
Santosh

**Comment by mikegrima** [comment]
Hi @santoshpatha12 : 

Can you paste in the errors you are receiving?

Thank You

**Comment by santoshpatha12** [comment]
Thank you for assisting. Please find the below error

It is throwing page not found. In web page, it is showing the below.
Webpage Error: 404 not found ( nginx/1.4.6(ubuntu)

**/var/log/security_monkey/security_monkey.access.log:**
10.181.0.45 - - [16/May/2016:07:38:32 +0000] "GET / HTTP/1.1" 200 5228 "-" "Wget/1.15 (linux-gnu)"
10.181.0.45 - - [16/May/2016:07:38:51 +0000] "GET /index.html HTTP/1.1" 404 151 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
10.181.0.45 - - [16/May/2016:07:38:52 +0000] "GET /favicon.ico HTTP/1.1" 404 151 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
10.181.0.45 - - [16/May/2016:07:38:52 +0000] "GET /favicon.ico HTTP/1.1" 404 151 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
10.181.0.45 - - [16/May/2016:09:06:39 +0000] "GET /favicon.ico HTTP/1.1" 404 151 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
10.181.0.45 - - [16/May/2016:23:32:33 +0000] "GET /index.html HTTP/1.1" 404 151 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"

**security_monkey.error.log**

2016/05/16 07:38:52 [error] 23734#0: *11 open() "/usr/local/src/security_monkey/security_monkey/static/favicon.ico" failed (2: No such file or directory), client: 10.181.0.45, server: , request: "GET /favicon.ico HTTP/1.1", host: "10.181.0.45"
2016/05/16 07:38:52 [error] 23734#0: *11 open() "/usr/local/src/security_monkey/security_monkey/static/favicon.ico" failed (2: No such file or directory), client: 10.181.0.45, server: , request: "GET /favicon.ico HTTP/1.1", host: "10.181.0.45"
2016/05/16 09:06:39 [error] 23734#0: *12 open() "/usr/local/src/security_monkey/security_monkey/static/favicon.ico" failed (2: No such file or directory), client: 10.181.0.45, server: , request: "GET /favicon.ico HTTP/1.1", host: "10.181.0.45"
2016/05/16 23:32:33 [error] 1564#0: *1 open() "/usr/local/src/security_monkey/security_monkey/static/index.html" failed (2: No such file or directory), client: 10.181.0.45, server: , request: "GET /index.html HTTP/1.1", host: "10.181.0.45"


Please help me to resolve the same.

Thank you,
Santosh

**Comment by mikegrima** [comment]
Hello:

Can you paste in the output of the command: 
```ls -l /usr/local/src/security_monkey/security_monkey/static/index.html```

If the file is there, check to make sure that the file has world readable permissions. If the file is not present, please paste in the output of the Dart compilation in this section: http://securitymonkey.readthedocs.io/en/latest/quickstart.html#clone-the-security-monkey-repo

Thank You

**Comment by santoshpatha12** [comment]
ls -l /usr/local/src/security_monkey/security_monkey/static/index.html
ls: cannot access /usr/local/src/security_monkey/security_monkey/static/index.html: No such file or directory

The file not exist.

**Comment by mikegrima** [comment]
Can you re-perform the Dart installation steps, and paste in the output?

**Comment by monkeysecurity** [comment]
You can also download the dart output:

https://github.com/Netflix/security_monkey/releases/download/v0.5.0/static.tar.gz

Just extract that to `/usr/local/src/security_monkey/security_monkey/static/`

**Comment by santoshpatha12** [comment]
@mikegrima  -- Done the reconfiguration and still we are facing the same issue


@monkeysecurity   -- We have copied and the zip file you have provided, there is no file with index.html file

We still facing same issue. Please assist to resolve the same.

**Comment by monkeysecurity** [comment]
There is no index.html.

There is, however, a ui.html.

The nginx config sets that as the default:

```
    location / {
        root /usr/local/src/security_monkey/security_monkey/static;
        index ui.html;
    }
```

**Comment by santoshpatha12** [comment]
the specified configuration is available in the nginx config file. Please see the below and assist on the same

    location /static {
        rewrite ^/static/(.*)$ /$1 break;
        root /usr/local/src/security_monkey/security_monkey/static;
        index ui.html;
    }

    location / {
        root /usr/local/src/security_monkey/security_monkey/static;
        index ui.html;
    }

}

root@pocz1msm01:~# ls -l /usr/local/src/security_monkey/security_monkey/static/ui.html
-rw-r--r-- 1 root root 5228 Apr 26 00:34 /usr/local/src/security_monkey/security_monkey/static/ui.html
root@pocz1msm01:~#

**Comment by santoshpatha12** [comment]
could you please provide some contact no so that i will call you and fix my issues.

**Comment by mikegrima** [comment]
Hello @santoshpatha12 , please send me an email (see my GitHub profile), and we can arrange a time to chat.

Thank you

**Comment by santoshpatha12** [comment]
I have mailed you.

**Comment by mikegrima** [comment]
With regards to the development instructions, there is an issue where it instructs users to run the command:
```
pip install -r requirements.txt
```

The command should be: 
```
python setup.py develop
```
This is present here: https://github.com/Netflix/security_monkey/blob/master/docs/dev_setup_ubuntu.rst and here: https://github.com/Netflix/security_monkey/blob/master/docs/dev_setup_osx.rst

However, the initial instructions that @santoshpatha12 followed have the correct command listed. I will further investigate.

**Comment by mikegrima** [comment]
Going through the main instructions... Making some small edits to make copying and pasting easier.

**Comment by mikegrima** [comment]
Made a PR to help address the issues.

@santoshpatha12 : I have gone through the instructions that you initially linked.  I have made some changes and tweaks to them to make it a bit more clear and easier to copy and paste.  To see them right now, please go here: https://github.com/mikegrima/security_monkey/blob/issue346/docs/quickstart.rst

Following those instructions, I was successfully able to get Security Monkey working.  Please try them again with a fresh VM, and let me know if you have any issues.

Thank You

**Comment by mikegrima** [comment]
The fixes have been merged. 🍌

**Comment by santoshpatha12** [comment]
Hi Mike,

After long time i got a chance work on this. I tried to validate updates in new system, I am not able to access the application in browser.

Can we have a call and close the same.

Please share your no i will call you.

Regards,
Santosh

**Comment by tiwari85aman** [comment]
i have setup the security monkey succesfully, but still i am not able to launch the dashboard of it
by entering the DNS id of my aws instance, how to fix it?

**Comment by tiwari85aman** [comment]
I have set up the security monkey succesfully, but still, i am not able to launch the dashboard of it
by entering the DNS id of my AWS instance, how to fix it?
