### ISSUE TITLE
 Need step by step process to configure jonitor monkey in RHEL instance

### ISSUE THREAD

**Issue by santoshpatha12** [Netflix/security_monkey#347]
Hi,

Could you please anybody provide step by step process to install and configure jonitor monkey in Redhat Linux aws instance.

And also provide how to use the same to tool to Retrieve/Manage the AWS Resources.

Regards,
Santosh

**Comment by santoshpatha12** [comment]
I have gone through the below link not able to configure
https://github.com/Netflix/SimianArmy/wiki/Janitor-Home

Please help me to complete my setup.

Regards,
Santosh

**Comment by mikegrima** [comment]
Hello @santoshpatha12 : Janitor Monkey is a separate project.  

Please refer to the following GitHub project: https://github.com/Netflix/SimianArmy

Thank You
