### ISSUE TITLE
security monkey authentication mechanism

### ISSUE THREAD

**Issue by westlifezs** [Netflix/security_monkey#359]
Hello there,

I am just wondering if I can opt security monkey auth to ldap or SAML?
I did some search but could not find anything related.
Could you provide some suggestions?
It appears to me that currently security monkey relies on local auth or oauth2 (correct me if I am wrong).

thank you very much!

Su

**Comment by westlifezs** [comment]
it looks like I can config ldap auth with nginx. Could anyone share with me some knowledge regarding how I can remove security monkey auth afterward? In that case I will only rely on ldap auth with nginx.

**Comment by monkeysecurity** [comment]
Hey Su,

https://github.com/Netflix/security_monkey/pull/354

SSO integration was recently merged to work with Ping or Google using idp/oauth2.  I'd certainly take a PR for SAML support, but have no need for it in my deployment and no way to test it.

You could disable user registration by setting `SECURITY_REGISTERABLE = False`.
