### ISSUE TITLE
new installation won't run under the www-data account

### ISSUE THREAD

**Issue by panik77** [Netflix/security_monkey#367]
Hi

I have just completed a new installation of Security Monkey, using the quick start instructions: https://securitymonkey.readthedocs.io/en/latest/quickstart.html

I am able to start the Scheduler and API Server services using the root account, but they are not running under the "www-data" account.

When I open the Security Monkey site I get the following error: "Error loading resource from API. Error: 502 Bad Gateway"
![error01](https://cloud.githubusercontent.com/assets/5741704/16025993/7383c322-320e-11e6-8052-b7cf5cb1045e.PNG)

Checking the status of the services returns:
`
ubuntu@ip-10-101-5-9:~$ sudo supervisorctl
securitymonkey                   FATAL      Exited too quickly (process log may have details)
securitymonkeyscheduler          FATAL      Exited too quickly (process log may have details)
`

The security monkey error log contains the following entries:
`
2016/06/08 06:54:33 [error] 1077#0: *253 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: , request: "GET /api/1/items?accounts=&count=25&names=&page=1&regions=&technologies= HTTP/1.1", upstream: "http://127.0.0.1:5000/api/1/items?accounts=&count=25&names=&page=1&regions=&technologies=", host: "securitymonkey.example.com", referrer: "https://securitymonkey.example.com/"
2016/06/08 06:55:03 [error] 1077#0: *253 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.0.1, server: , request: "GET /api/1/items?accounts=&count=25&names=&page=1&regions=&technologies= HTTP/1.1", upstream: "http://127.0.0.1:5000/api/1/items?accounts=&count=25&names=&page=1&regions=&technologies=", host: "securitymonkey.example.com", referrer: "https://securitymonkey.example.com/"
`

I am using a separate PostgreSQL RDS instance to host the Security Monkey database

I have gone through the setup guide to confirm I have followed all the steps.

**Comment by panik77** [comment]
Resolved this issue.

First we changed the home directory for www-data user to /home/www-data and rebooted.

sudo mkdir /home/www-data
sudo chown -R www-data:www-data www-data
sudo usermod -d /home/www-data -m www-data

Added SECURITY_MONKEY_SETTINGS as environment variable, made sure it's available as global.
https://securitymonkey.readthedocs.io/en/latest/quickstart.html#security-monkey-settings

**Comment by reuvenharrison** [comment]
Hi panik77,
I am experiencing the same problem.

2016/09/26 18:24:03 [error] 1087#0: *29 connect() failed (111: Connection refused) while connecting to upstream, client: 82.80.60.178, server: , request: "GET /api/1/auditorsettings HTTP/1.1", upstream: "http://127.0.0.1:5000/api/1/auditorsettings", host: "ec2-52-209-127-18.eu-west-1.compute.amazonaws.com", referrer: "https://ec2-52-209-127-18.eu-west-1.compute.amazonaws.com/"

Followed your instructions above but to no avail...
There is no process listening on port 5000.
Also, I have no idea what 82.80.60.178 is (not my ip).
Any ideas?

Thanks,
Joe

**Comment by LazyGetter** [comment]
Just had a similar issue. Along with the above steps , I had to change permissions / users for the log files under /var/log/security_monkey/..  for some reason the process was not able to write to the securitymonkey.log file and hence was failing to start. 

Another issue I faced was compiler failure of dart. The process would abruptly get "killed". I compiled it separately on a different Ubuntu instance and copied it over.

**Comment by Kerri-Mak-hs** [comment]
Agree with @LazyGetter. In the log file "/var/log/supervisor/securitymonkey-stderr---*.log", there is the error msg 
`ValueError: Unable to configure handler 'file': [Errno 13] Permission denied: '/var/log/security_monkey/securitymonkey.log'`

I then changed the permission - "chmod 643 /var/log/security_monkey/securitymonkey.log" -> restart securitymonkey in supervisor -> restart nginx. Now gunicorn is running, as shown in the logs.

`2017-04-06 05:53:51 [5108] [INFO] Starting gunicorn 18.0
2017-04-06 05:53:51 [5108] [INFO] Listening at: http://127.0.0.1:5000 (5108)
2017-04-06 05:53:51 [5108] [INFO] Using worker: sync
2017-04-06 05:53:51 [5115] [INFO] Booting worker with pid: 5115
2017-04-06 05:53:51 [5116] [INFO] Booting worker with pid: 5116
2017-04-06 05:53:51 [5117] [INFO] Booting worker with pid: 5117
2017-04-06 05:53:51 [5118] [INFO] Booting worker with pid: 5118
2017-04-06 05:53:51 [5119] [INFO] Booting worker with pid: 5119
2017-04-06 05:53:51 [5120] [INFO] Booting worker with pid: 5120
/usr/local/lib/python2.7/dist-packages/Flask_Security_Fork-1.8.2-py2.7.egg/flask_security/forms.py:213: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  super(LoginForm, self).__init__(*args, **kwargs)
/usr/local/lib/python2.7/dist-packages/Flask_Security_Fork-1.8.2-py2.7.egg/flask_security/forms.py:213: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
  super(LoginForm, self).__init__(*args, **kwargs)
/usr/local/lib/python2.7/dist-packages/Flask_Security_Fork-1.8.2-py2.7.egg/flask_security/utils.py:166: DeprecationWarning: the method passlib.context.CryptContext.encrypt() is deprecated as of Passlib 1.7, and will be removed in Passlib 2.0, use CryptContext.hash() instead.
  return _pwd_context.encrypt(signed)`

**Comment by erick2k1995** [comment]
I have the same problem as I can solve it I tried to give back the permission chown www-data, without any success 

![image](https://user-images.githubusercontent.com/52808488/61606837-c91c3000-ac11-11e9-9abe-45ddc89a60ab.png)
