### ISSUE TITLE
security monkey 0.41 auth component

### ISSUE THREAD

**Issue by westlifezs** [Netflix/security_monkey#369]
Hello,

I am planing to use shibboleth + apache + flask_sso to handle SAML based SSO for security monkey.
My work is based at commit "e9ce8816f6f85ce886b9f0c01a1a7104289b8ff9" of security monkey 0.41.
Could you let me know in the code where authentication is processed?
I though it was at https://github.com/Netflix/security_monkey/blob/master/security_monkey/__init__.py#L71

However, I could not see my break point stop within the function during my login.
I think 0.41 does not have auth folder yet. But I really need to know where the auth happens in order to move forward. Could you point me where the auth code is?

thanks

**Comment by monkeysecurity** [comment]
Hey Su - Any interest in rebasing this to be based on the latest from the dev branch?

Currently Flask-Security handles password based logins and the PING sso view endoint handles idp based logins:

https://github.com/Netflix/security_monkey/blob/develop/security_monkey/sso/views.py#L135
