### ISSUE TITLE
BUG: First Seen column broken

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#377]
On the item table, there is a First Seen and a Last Modified column.  The First Seen column should show the date the item was first seen by security_monkey.  That should be the date of the oldest revision.  It seems to be displaying the same date as the Last Modified column and ignoring the other revisions.

**Comment by aebie** [comment]
@monkeysecurity we just did a fix for this. I will start the submission process.

**Comment by monkeysecurity** [comment]
Much appreciated.

I was thinking the `Item` table should probably have a SQLAlchemy hybrid property for the latest revision.  Maybe it would make sense to create one for the date of the oldest revision as well.

Hybrids seem to make the code a little cleaner, but I'd like to see if that impacts performance negatively.  

It's totally okay if this isn't implemented with hybrids. (either way)

**Comment by monkeysecurity** [comment]
Fixed and merged in #446.
