### ISSUE TITLE
Task: Add AWS accounts for new Mumbai region

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#378]
https://aws.amazon.com/about-aws/whats-new/2016/06/announcing-the-aws-asia-pacific-mumbai-region/

I believe @bunjiboys has done this update in the past.

File to update:
https://github.com/Netflix/security_monkey/blob/master/data/aws_accounts.json

**Comment by bunjiboys** [comment]
I can take a look at this later today, but yeah its fairly straight forward to update.
