### ISSUE TITLE
Scaling security monkey

### ISSUE THREAD

**Issue by pklanka** [Netflix/security_monkey#393]
Can we have a section in the documentation on how to scale security monkey in the production environment? Has there been any testing performed to check to see how well the tool performs in each category.

Examples of architectures we can probably investigate - 
**- Architecture# 1** (probably worst case scenario and would definitely work): create separate instances of security monkey and rds databases for every couple of dozens of accounts (depending on the load)

- .
- . (many models in between)
- .

**- Architecture# N** (probably best case scenario and need to research this from various angles): think of scheduler and web as micro instances. Run web on less number of nodes with Security monkey and scheduler on the nodes given the # of AWS accounts that scales based on the instance utilization

**Comment by monkeysecurity** [comment]
Hey @pklanka,

@ollytheninja did some incredible work in this area: #318 

The ApScheduler v3 *should* allow us to have a cluster of security_monkeys each running separate tasks.  The tasks would be persisted in an RDS datastore.  As you can see, I haven't had time to merge that in yet.  For the current architecture, I feel that is the way it must go.  This is very similar to your "**Architecture # N**".  If anyone has the skills and the time, I'd love to see contributions here.

We're working on a complete re-architecture that should eliminate scaling problems.  lambda functions are triggered by eventrule cloudtrail changes.  The re-architecture is mostly server-less except for the web UI.  Polling the AWS API's will mostly be eliminated.  We don't have a release date for that yet.  The new architecture may not work in environments where lambda isn't approved.  (I don't think gov-cloud has lambda, and I'm not sure if healthcare organizations can use it either. -- I should find someone and verify.)
