### ISSUE TITLE
Dart XHR requests are cached

### ISSUE THREAD

**Issue by AlexCline** [Netflix/security_monkey#403]
After upgrading to 0.6.0, I was still seeing the client interface from 0.5.0. No ARN search, no export, etc. Force refreshing didn't work. After digging into the inspector, I noticed that main.dart.js makes several ajax requests for partials that make up the client interface.

![cached requests](https://cloud.githubusercontent.com/assets/400773/18173444/97fe2f3c-7037-11e6-9db9-1b55b09278a9.png)

When in incognito mode in Chrome, the client interface is rendered correctly. This is because the requests for partials aren't cached.

Instead of requiring a full browser cache clear, it would be useful if cache busting is used when requesting the partials so that if they're updated, the updates are correctly retrieved. Requesting something like this:

```
search_bar_component.html?v=0.6.0
```

**Comment by monkeysecurity** [comment]
Hey @AlexCline.  Yeah I noticed that was a problem.  I'm not sure exactly how to fix it.  On my machine I opened the developer tools (opt-cmd-i) and then right clicked on the refresh and selected "empty cache and hard reload".

I'm not sure how to convince AngularDart to append a version to the requests.

I see the requests already contain some no-cache headers:

```
GET /packages/security_monkey/component/username_component/username_component.html HTTP/1.1
Host: securitymonkey.mgmt.netflix.net
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

Any ideas for how to implement?  I haven't spent too much time google-ing it yet.

**Comment by AlexCline** [comment]
Doing a little research makes it seem like this won't be straight forward.

Adding a query parameter to the component's templateUrl breaks dart's client-side processing. Not sure why this is, but it seems like expected behavior.

It is possible to change the URL in dart.main.js after performing a production build, so the file could be modified to grab the templates with a version query parameter. This would be hacky.

I believe the best way to fix this would be to cache the templates using the [template cache transformer](https://github.com/angular/angular.dart/issues/1646). This is supposedly easy to do using `generate_template_cache: true` as an optional angular configuration. I tried enabling this, but wasn't able to get it to correctly generate the template cache and present templates using it instead of the client retrieving them using Ajax requests after performing a `pub build`.

Getting the template cache working would have an added benefit of improving performance as well as potentially fixing this edge case.
