### ISSUE TITLE
No details after upgrade

### ISSUE THREAD

**Issue by mugzy** [Netflix/security_monkey#429]
After upgrading to the latest version, the detail pages are blank.  The jumplist still has dates, but they are disabled.

Also, reports just hang on loading.  I don't see anything useful in the logs under /var/log...   Where else can I check for errors that may point to the issue?

I followed these steps for the upgrade: https://github.com/Netflix/security_monkey/issues/205

Here is a screenshot
![image](https://cloud.githubusercontent.com/assets/3887497/19457797/a3b910ce-948d-11e6-9359-8cd95581b759.png)

**Comment by monkeysecurity** [comment]
Hey @mugzy - Did you recompile the web UI (or download the static.tar.gz attached to the release?)

Could you open the Chrome inspector and then right click on the refresh icon and click on "Empty Cache and Hard Reload" ?

Are there any errors in the Javascript console?

**Comment by mugzy** [comment]
Thanks!  The "Empty Cache and Hard Reload" did the trick.  Thanks!
