### ISSUE TITLE
Auditor check items already registered that have not been modified

### ISSUE THREAD

**Issue by echinengk** [Netflix/security_monkey#434]
Hello!
I wonder if there is any way to invoke audit check on items that are already added in SecurityMonkey because every time I create a new auditor have to re-register the AWS account so that it delete all the items and recreate only back this way again auditor to checking the items that exist, the problem to do that I have to justify all the items I had already justified.

I know SecurityMonkey only invokes the auditor when a new item is added or modified, is there any way to clean the database only the items I want to be checked again?

**Comment by monkeysecurity** [comment]
Hey @echiang - Sorry it took so long to respond.

For future questions, it's sometimes easier to hop on the gitter.im chat room.

The manage.py now has a command to delete unjustified issues:

`python manage.py delete_unjustified_issues -a myaccountname -m iamrole,iamuser`

You can also re-run the auditors:

`python manage.py audit_changes -a myaccountname -m iamrole,iamuser`
