### ISSUE TITLE
New Dart (Version: 1.20.1-1) breaks build again

### ISSUE THREAD

**Issue by KevinHock** [Netflix/security_monkey#465]
Similar to https://github.com/Netflix/security_monkey/issues/259, 1.20.1-1 gives

``who@foo:/usr/local/src/security_monkey/dart$ sudo /usr/lib/dart/bin/pub get
Resolving dependencies...
Got dependencies!
Precompiling dependencies...
Loading source assets...
Loading dart_to_js_script_rewriter, di/module_transformer, initialize/build/loader_replacer, smoke/src/default_transformer and initialize transformers...
Loading angular transformers...
Unable to spawn isolate: Unhandled exception:
Could not import "package:async/async.dart" from "package:$pub/serialize.dart": Failure getting http://localhost:35312/packages/async/async.dart:
  404 Not Found
null
dart:isolate-patch/isolate_patch.dart      Isolate.spawnUri.<async>
dart:async-patch/async_patch.dart 34       _asyncErrorWrapperHelper.<fn>
dart:async/zone.dart 1410                  _RootZone.runBinary
dart:async/future_impl.dart 146            _FutureListener.handleError
dart:async/future_impl.dart 649            _Future._propagateToListeners.handleError
dart:async/future_impl.dart 671            _Future._propagateToListeners
dart:async/future_impl.dart 485            _Future._completeError
dart:async/future_impl.dart 56             _SyncCompleter._completeError
dart:async/future_impl.dart 27             _Completer.completeError
dart:isolate-patch/isolate_patch.dart 438  Isolate._spawnCommon.<fn>
dart:isolate-patch/isolate_patch.dart 148  _RawReceivePortImpl._handleMessage
``

The fix was to use `sudo apt-get install -y dart=1.12.2-1` like before https://github.com/Netflix/security_monkey/commit/e7ab85e30d26a7886d45855867e540908acb6944 but ideally we can figure out how to make the latest work.

**Comment by monkeysecurity** [comment]
```
$ apt-cache show dart | head
Package: dart
Version: 1.20.1-1
```

```
$ sudo apt-get install --upgrade dart
Reading package lists... Done
Building dependency tree
Reading state information... Done
dart is already the newest version.
```

```
$ dart --version
Dart VM version: 1.20.1 (Wed Oct 12 22:00:54 2016) on "linux_x64"
```

```
$ pub get
...
Got dependencies!
```

It appears to work for me.  I'll leave this open so anyone else can chime in.  I'm not sure why it would work for me but not for you.  Are you on the `master` or `develop` branch?

**Comment by KevinHock** [comment]
This was an error on my side, sorry @monkeysecurity. Thanks for making this great OSS tool, this and the Threat Response tools are the best AWS OSS tools.
