### ISSUE TITLE
S3 watcher KeyError: 'Region'

### ISSUE THREAD

**Issue by cstewart87** [Netflix/security_monkey#506]
It appears that the S3 watcher is not properly handling exceptions.  If, for whatever reason, SM doesn't have all required access for a single bucket, the `from_slurp` method throws an exception:

```
security_monkey/watchers/s3.py", line 84, in from_slurp
    region=bucket['Region'],
KeyError: 'Region'
```

It appears that on L60 of watchers/s3.py, when a bucket is processed, if SM doesn't have necessary access `bucket` is set to a dict with the error message (e.g. `{'Error': 'Unauthorized'}`

**Comment by mikegrima** [comment]
Hmm... I wonder if this is caused if a bucket has a deny all policy...

**Comment by monkeysecurity** [comment]
Or an empty ACL.  I think the point is that SM should be able to handle it.

**Comment by mikegrima** [comment]
Will have the fix read in 5 minutes ;)

**Comment by monkeysecurity** [comment]
🆒🕶️
