### ISSUE TITLE
Removing the need for the Google Plus API when using Google oauth

### ISSUE THREAD

**Issue by ChristopherGAndrews** [Netflix/security_monkey#508]
The current version of Security Monkey, v0.8.0, requires you to configure Google Plus API access when setting up the Google API Project to use Google Oauth SSO.  The email lookup API call after the token call can be changed from using the Google Plus API to using a userinfo lookup that requires no extra APIs to be added to your Google API Project.  Both the Google Plus API and the userinfo API return a json object with an email value. This change needs to be made in security_monkey/sso/views.py line 178

From:

people_api_url = 'https://www.googleapis.com/plus/v1/people/me/openIdConnect'

To: 

people_api_url = 'https://www.googleapis.com/userinfo/v2/me'

Currently if you do not have the Google Plus API added to your Google API Project you will see this when trying to authenticate with Google:

{"status": 500, "message": "Internal Server Error"}

And get this in the security monkey logs (/var/log/supervisor/securitymonkey-stdout---supervisor-ZZZZZ.log):

2017-01-25 23:33:06,222 ERROR: Internal Error [in /usr/local/lib/python2.7/dist-packages/Flask_RESTful-0.3.3-py2.7.egg/flask_restful/__init__.py:299]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/Flask_RESTful-0.3.3-py2.7.egg/flask_restful/__init__.py", line 462, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Flask_RESTful-0.3.3-py2.7.egg/flask_restful/__init__.py", line 572, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/src/security_monkey/security_monkey/sso/views.py", line 155, in get
    return self.post()
  File "/usr/local/src/security_monkey/security_monkey/sso/views.py", line 227, in post
    user = User.query.filter(User.email == profile['email']).first()
KeyError: 'email'

If you dump the response you get:

{u'error': {u'code': 403, u'message': u'Access Not Configured. Google+ API has not been used in project XXXXXXXXXXXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus/overview?project=XXXXXXXXXXXXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.', u'errors': [{u'domain': u'usageLimits', u'message': u'Access Not Configured. Google+ API has not been used in project XXXXXXXXXXXXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus/overview?project=XXXXXXXXXXXXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.', u'reason': u'accessNotConfigured', u'extendedHelp': u'https://console.developers.google.com/apis/api/plus/overview?project=XXXXXXXXXXXXXXX'}]}}

You have to add the Google Plus API, or change the people_api_url to resolve this issue.

**Comment by monkeysecurity** [comment]
Hey @crruthe ^

IIRC, @crruthe wrote the google sso code.

**Comment by crruthe** [comment]
Sorry, I just did the OneLogin SSO. Think this one was you @monkeysecurity  :)
https://github.com/Netflix/security_monkey/pull/354

**Comment by ChristopherGAndrews** [comment]
I can take a stab at updating it.  I have some ideas on using Google Groups to set user permissions.

**Comment by monkeysecurity** [comment]
Darn.  That's embarrassing!

Thanks @ChristopherGAndrews .

**Comment by monkeysecurity** [comment]
+ @llange and @AlexClineBB 
https://github.com/Netflix/security_monkey/pull/412
