### ISSUE TITLE
Feature Request: Add support for Application Load Balancers

### ISSUE THREAD

**Issue by nevins-b** [Netflix/security_monkey#509]
Currently security monkey only appears to know about ELBs, not ALBs.

**Comment by monkeysecurity** [comment]
I'd love a PR, preferably to [CloudAux](https://github.com/Netflix-Skunkworks/cloudaux).

Should be pretty similar to the existing ELB watcher.

**Comment by monkeysecurity** [comment]
ALB supported was added to CloudAux. A security_monkey watcher was created for ALBs. A security_monkey auditor was added as well.  I think we can close this ticket now.
