### ISSUE TITLE
Ignor List - Cannot ignore un-attached policies from audit report

### ISSUE THREAD

**Issue by fanemsm** [Netflix/security_monkey#517]
Hi all,

Is there any way I can set Security Monkey to ignore all the policies that are not attached to any security group, user or role even if they provide high privileges?
I have tried the following setup but is not working:
Prefix: attachment_count": 0
Technology: policy

Disabling them from "Auditor Settings" is not an option also.

In addition is there any way to set Security Monkey to ignore specific regions (The ones I know that are not in used)

Best regards,

Stefan Magda

**Comment by monkeysecurity** [comment]
The prefix for managed policy can be either the ARN or the Name.  It does not work on the JSON body of the policy.

https://github.com/Netflix/security_monkey/blob/develop/security_monkey/watchers/iam/managed_policy.py#L65

If you'd like to ignore AWS-created managed policies you can create this prefix entry:

Prefix: arn:aws:iam::aws:policy
Notes: Ignoring AWS owned managed policies
Type: Policy

There's not currently a way to disable a region.

**Comment by fanemsm** [comment]
Hi,

Thank you for your suggestion. It seams that adding your suggestion to the Ignore list stills displays the policies and the score is still the same.

What I'm trying to do is to set the score to 0 for the un-attached policies. Is there any easy way to do this?

Thank you for your time!

PS: If I'm modifying the code just for testing what do I have to rebuild so my changes will apply?

Best regards,
Stefan

**Comment by monkeysecurity** [comment]
Hey Stefan,

If you modify the file `auditors/iam/policy.py`, you'll just need to restart security_monkey and run the auditor again.

`sudo supervisorctl` `restart securitymonkeyscheduler` `CTRL-D` `python manage.py audit_changes -m policy`

**Comment by fanemsm** [comment]
Hi,

Thanks for your support!
I have added the following lines before line #71 in /security_monkey/watchers/iam/managed_policy.py: 
if policy.attachment_count == 0:
                    continue

Thus if a Managed policy is not attached then the score will be 0.

Best regards, 
Stefan M.

**Comment by monkeysecurity** [comment]
Pretty cool.
