### ISSUE TITLE
Unable to register auditor using new Plugin API

### ISSUE THREAD

**Issue by mariusgrigaitis** [Netflix/security_monkey#520]
#504 

I tried creating an auditor `class MyAuditor(Auditor)` in separate python package

Module gets loaded (I see message):
```
DEBUG: Loading plugin plugin_name [in /usr/local/src/security_monkey/security_monkey/common/utils.py:173]
```

But auditor does not get loaded, because it does not pass this condition:
https://github.com/Netflix/security_monkey/blob/develop/security_monkey/auditor.py#L42

Is there any specific reason to load auditors using find_module?

**Comment by mariusgrigaitis** [comment]
Workaround:

* Create own find_module method which loads auditors in entrypoint

Not sure if that's appropriate way to go, but works

**Comment by monkeysecurity** [comment]
Hey @mariusgrigaitis 

I don't understand the question.  Could you provide an example of what you had to do?  Why did your auditor fail the condition from line #42?

**Comment by redixin** [comment]
@monkeysecurity this is line 45 in current version. Please take a look: https://github.com/Netflix/security_monkey/blob/1acf2744397258f4adee47e7332123100efa6aff/security_monkey/auditor.py#L44-L45

**Comment by mariusgrigaitis** [comment]
@monkeysecurity @redixin seems to be correct.

I was trying to write custom auditor in separate python package which would then be used. But this implementation / loading of Auditors assumes that all auditors are bundled together with security_monkey by checking include path.

What I ended up doing is writing my own find_modules implementation that loads auditors in separate python package using imp.load_source

**Comment by monkeysecurity** [comment]
Should we be adopting your find_modules implementation?

**Comment by mariusgrigaitis** [comment]
find_modules is basically the same as in security_monkey.

I guess proper solution would be that find_modules would not be needed at all.

It's currently needed only because of that check in https://github.com/Netflix/security_monkey/blob/1acf2744397258f4adee47e7332123100efa6aff/security_monkey/auditor.py#L44-L45

**Comment by monkeysecurity** [comment]
Hey @mariusgrigaitis - I think you now have more experience with custom auditors than I do.

Would you be willing to submit a PR that makes this flow easier?

**Comment by mariusgrigaitis** [comment]
Don't really have time for this ATM.
