### ISSUE TITLE
GOOGLE_HOSTED_DOMAIN is not documented

### ISSUE THREAD

**Issue by mariusgrigaitis** [Netflix/security_monkey#526]
GOOGLE_HOSTED_DOMAIN is implemented but not documented anywhere. Only exists in code.

**Comment by monkeysecurity** [comment]
See @llange's comment on his commit:

**Comment by mariusgrigaitis** [comment]
I understand the usage and stuff but sso should be documented somewhere, at least in sample config or wherever because now you have to find commit message/search through code to find out that such config variable exists
