### ISSUE TITLE
Ignore unattached/unused AWS-managed policies during audits

### ISSUE THREAD

**Issue by cstewart87** [Netflix/security_monkey#542]
AWS-managed policies cause a lot of noise and somewhat distort the overall security scores.  What's the level of interest in ignoring unattached AWS-managed policies during relevant audit checks?

Benefit of this over ignoring the policies is that when ignoring, you may be left unaware of policy security hygiene if it's ever attached to one of your resources, whereas with this feature you can cut down on the noise *until* it's attached to one of your own resources.

Thoughts/suggestions welcome :)

**Comment by fanemsm** [comment]
#517 
Hi Please see the mentioned issue. This is the way I solved it.

Best regards,
Stefan M.

**Comment by monkeysecurity** [comment]
I think that's reasonable.

**Comment by cstewart87** [comment]
@monkeysecurity - it doesn't look like this is included in the Netflix/develop codebase.  Would this, or something similar, be something you would accept as a PR?

**Comment by monkeysecurity** [comment]
sure - let me know if there's still time.

**Comment by monkeysecurity** [comment]
PR merged
