### ISSUE TITLE
Metrics logger

### ISSUE THREAD

**Issue by cstewart87** [Netflix/security_monkey#543]
Any interest in adding a metrics logger to help track long-running methods/actions?  This can prove to be useful when using any sort of centralized logging tool.

**Comment by monkeysecurity** [comment]
I've always wanted a dashboard view that would show how long each watcher in each account is taking. Is that what you had in mind?

**Comment by monkeysecurity** [comment]
The `Reporter::run()` method use to time the runs and log them out.
```
time2 = time.time()
app.logger.info('Run Account %s took %0.1f s' % (account, (time2-time1)))
```

I see that #528 removed that. It sounds like you're describing this exact feature.

Better than just logging it out would be if it were put into a db table.  Preferably with some sort of TTL so we could remove old performance data similar to how we remove old exceptionlogs from the DB.

I guess RRD would also be an option.

**Comment by cstewart87** [comment]
Ah, that PR certainly did remove those.  That was likely by mistake.  If you want to add those lines back in the meantime, go for it.

**Comment by monkeysecurity** [comment]
#562 to put the log statements back into `reporter.py`.
