### ISSUE TITLE
DB query for drop down on search page slow

### ISSUE THREAD

**Issue by aebie** [Netflix/security_monkey#548]
Once a large number of issues are in the DB, the drop downs for account, tech, etc gets painfully slow to populate. I am pretty sure this has to do with the many joins followed by the 'like()' method calls in the query from security_monkey/views/distinct.py. Believe the 'like' is causing it to do a table scan. I have had luck in similar circumstances by breaking these into two queries, first query the smaller tables (account, account_type and technology) with a like() to get a list of matching id's, then do the main query where you are matching the id, not a partial string. If I have time before moving off of this contract I will implement it, but wanted to record it in case I don't.

        query = Item.query
        query = query.join((Account, Account.id == Item.account_id)).join(
            (AccountType, AccountType.id == Account.account_type_id))
        query = query.join((Technology, Technology.id == Item.tech_id))
        query = query.join((ItemRevision, Item.latest_revision_id == ItemRevision.id))
        if 'regions' in args and key_id != 'region':
            regions = args['regions'].split(',')
            query = query.filter(Item.region.in_(regions))
        if 'accounts' in args and key_id != 'account':
            accounts = args['accounts'].split(',')
            query = query.filter(Account.name.in_(accounts))
        if 'accounttypes' in args and key_id != 'accounttype':
            accounttypes = args['accounttypes'].split(',')
            query = query.filter(AccountType.name.in_(accounttypes))
        if 'technologies' in args and key_id != 'tech':
            technologies = args['technologies'].split(',')
            query = query.filter(Technology.name.in_(technologies))
        if 'names' in args and key_id != 'name':
            names = args['names'].split(',')
            query = query.filter(Item.name.in_(names))
        if 'arns' in args and key_id != 'arn':
            names = args['arns'].split(',')
            query = query.filter(Item.arn.in_(names))
        if 'active' in args:
            active = args['active'].lower() == "true"
            query = query.filter(ItemRevision.active == active)

        if key_id == 'tech':
            if select2:
                query = query.distinct(Technology.name).filter(func.lower(Technology.name).like('%' + q + '%'))
            else:
                query = query.distinct(Technology.name)
        elif key_id == 'accounttype':
            if select2:
                query = query.distinct(AccountType.name).filter(func.lower(AccountType.name).like('%' + q + '%'))
            else:
                query = query.distinct(AccountType.name)
        elif key_id == 'account':
            if select2:
                query = query.filter(Account.third_party == False)
                query = query.distinct(Account.name).filter(func.lower(Account.name).like('%' + q + '%'))
            else:
                query = query.distinct(Account.name)

**Comment by monkeysecurity** [comment]
Neat.

It always bothers me when the region dropdown takes a noticeable amount of time...

**Comment by monkeysecurity** [comment]
Hey @aebie - I found a couple ways to speed these dropdowns up.  See #613.

- I moved some of the loads so they only occur if necessary.
- I modified Item.issue_count to be deferred.  (It's a column_property, which triggers a subquery)
- I added a unique constraint and index to Technology.name.

10x-30x speed increase depending on the field.

**Comment by monkeysecurity** [comment]
Fixed in #613.
