### ISSUE TITLE
elasticsearch_service watcher should use ES regions, not EC2 regions

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#551]
https://github.com/Netflix/security_monkey/blob/develop/security_monkey/watchers/elasticsearch_service.py#L30

Currently the elasticsearch_service watcher is iterating over EC2 regions.

```
from boto.ec2 import regions
...
for region in regions():
```

We should instead only interate over elasticsearch regions.  This will stop exceptions for regions like eu-west-2 that don't yet support elasticsearch.

```
boto3.session.Session().get_available_regions(service_name="es")
['ap-northeast-1', 'ap-northeast-2', 'ap-south-1', 'ap-southeast-1', 'ap-southeast-2', 'eu-central-1', 'eu-west-1', 'sa-east-1', 'us-east-1', 'us-east-2', 'us-west-1', 'us-west-2']
```

**Comment by mikegrima** [comment]
In addition to the above, there is also a bug where if the ES cluster has an empty policy, it will raise an exception.

**Comment by mikegrima** [comment]
Submitted PR #553 to address.
