### ISSUE TITLE
PR's failing on travis-ci

### ISSUE THREAD

**Issue by aebie** [Netflix/security_monkey#556]
The cause is that the test_reporter class needs to be updated to remove account fields deprecated by:

https://github.com/Netflix/security_monkey/commit/c666a012ec65a4ffcb878d148e2af33022c42afd

When I change line 104+ to this:

        account = Account(identifier="012345678910", name="TEST_ACCOUNT",
                          account_type_id=account_type_result.id, notes="TEST_ACCOUNT",
                          third_party=False, active=True)

the tests work.

**Comment by monkeysecurity** [comment]
Should be fixed by #552.  I'll reopen this issue if not.
