### ISSUE TITLE
[question]Performance in S3 outage

### ISSUE THREAD

**Issue by KevinHock** [Netflix/security_monkey#578]
During today's S3 outage, I thought Security monkey didn't use S3 for the most part (it uses RDS), I thought it made a ton of API calls every 15 minutes. Persisted that data to PostgreSQL. Did a bunch of logic. Sent some alerts via SES. Went to sleep for 15 minutes. But, it seems that most changes didn't get added to the web UI today either for some reason? I know SES was giving 500 errors to SecurityMonkey when I tail'd the logs but I didn't see anything that would mess even the web UI up e.g. I made a bad security group and it didn't show up 🤔

**Comment by monkeysecurity** [comment]
Are you running off of the latest develop commit or from an actual release?

The reporter should save the changes to the DB before it ever sends out emails.
-https://github.com/Netflix/security_monkey/blob/develop/security_monkey/reporter.py#L54

**Comment by KevinHock** [comment]
Yeah, I think RDS was having issues yesterday, so I don't think there's anything we can do.
