### ISSUE TITLE
No login page

### ISSUE THREAD

**Issue by tunkaflux** [Netflix/security_monkey#581]
Hi,

After installing Security Monkey following the Quick Start guide, I don't get the Login page, but I get overview and apparently I'm logged in as Anonymous?
Trying to Sign In does not work, i.e. I still don't get the login page.

Surfing as an Anonymous user regularly shows:

`"Error loading resource from API. Error: <HTTP 502: <html> <head><title>502 Bad Gateway</title></head> <body bgcolor="white"> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.10.0 (Ubuntu)</center> </body> </html> > "`

I also see the following error message in security_monkey.error.log:

2017/03/02 18:42:29 [error] 15143#15143: *15 connect() failed (111: Connection refused) while connecting to upstream, client: IPADDRESS, server: , request: "GET /api/1/items?accounts=&arns=&count=25&names=&page=1&regions=&technologies= HTTP/1.1", upstream: "http://127.0.0.1:5000/api/1/items?accounts=&arns=&count=25&names=&page=1&regions=&technologies=", host: "HOSTNAME.amazonaws.com", referrer: "https://HOSTNAME.compute-1.amazonaws.com/"

**Comment by tunkaflux** [comment]
Hmmm, I think I found the problem, the following from the Quick Start Guide:

```
sudo mkdir /var/log/security_monkey
sudo chown www-data /var/log/security_monkey
sudo mkdir /var/www
sudo chown www-data /var/www
sudo touch /var/log/security_monkey/security_monkey.error.log
sudo touch /var/log/security_monkey/security_monkey.access.log
sudo touch /var/log/security_monkey/security_monkey-deploy.log
sudo chown www-data /var/log/security_monkey/security_monkey-deploy.log
```
Don't we need to add this as well:
```
sudo chown www-data /var/log/security_monkey/security_monkey.error.log
sudo chown www-data /var/log/security_monkey/security_monkey.access.log
```

**Comment by tunkaflux** [comment]
Sorry for replying to my own comment, but I did _something_ and now it works... I have no idea which action specifically made this work.

**Comment by tunkaflux** [comment]
I believe I have found the issue. All log files under /var/log/security_monkey need to be chown'd www-data. After that, everything works.

**Comment by eshiferax** [comment]
^This helped a lot, had no idea what my issue was for a while. Think this should be added to the quick-start guide for sure.

**Comment by hobbits49** [comment]
@tunkaflux I have the same problem as yours, and I also try to chown all log files to www-data, but it still doesn't work. May I know what else you did to fix the problem? Thank you.

**Comment by tunkaflux** [comment]
@hobbits49 So, I chown'd the logs under /var/log/security_monkey to www-data and then ran these commands again:

```
export SECURITY_MONKEY_SETTINGS=/usr/local/src/security_monkey/env-config/config-deploy.py
sudo service supervisor restart
sudo supervisorctl &
sudo service nginx restart
```
After this, everything worked for me.

**Comment by hobbits49** [comment]
@tunkaflux Thank you for your reply. It's still not working on my environment. There seems to be different problems for me.

**Comment by monkeysecurity** [comment]
It seems to me that you have nginx up serving the static content, but that there's a problem with gunicorn.  (Nginx proxies connections to gunicorn)

Check the status:
```
sudo supervisorctl
> status
> CTRL-D
```
Hopefully securitymonkeyscheduler is running.  If it has a very short uptime, it's probably running into a problem on start.  If so, I'd stop the scheduler check log permissions, and try to run it manually.

**Comment by hobbits49** [comment]
Hi @monkeysecurity , I already figured this out, although I don't know how did I fix it... Thank you for the help!

**Comment by bhai840** [comment]
I had the same problem and restart of supervisor did the trick 
sudo service supervisor restart

**Comment by davinerd** [comment]
Just to add my experience for future readers, since I've spent almost 2 days trying to figure out what was going on.

There are multiple reasons why the login page doesn't show up, here are what I found (also thanks to the people who wrote on this thread):

- Ownership on `/var/log/security_monkey/securitymonkey.log`. Ensure that the owner is `www-data` both user and group.
- API port change. If you change the `API_PORT` in `venv-config/config.py` be also sure to edit the file `/etc/nginx/sites-available/security_monkey.conf`, specifically the `proxy_pass` directive (it's hardcoded the value `5000`)
- Another service binding on the same port of the API. That was actually my issue. So if you have a service listening on the same port, it prevents the API server to run. Restarting supervisor sometimes help due to the fact that SecurityMonkey may lock the port before the other service does (but in this case you'll have a service who is not working because the port is bound by SecurityMonkey).

Hope it helps.

**Comment by mikegrima** [comment]
@davinerd : Are there specific areas in the documentation that is lacking this information?

If so, can you please submit a pull request to address? I have not experienced the above errors when going through the quickstart guide the last few times I attempted to set up an environment.
