### ISSUE TITLE
Pub Build, Exhausted heap space Probelm

### ISSUE THREAD

**Issue by hobbits49** [Netflix/security_monkey#583]
I am following exactly the Quick Start Guide. When it moved to sudo /usr/lib/dart/bin/pub build, I met the Exhausted heap space problem, the result is like the following:

#Exhausted heap space, trying to allocate 2208 bytes.

Is there anyone know how to figure this out. I already tried all the possible methods I could find online.

Thank you.

**Comment by hobbits49** [comment]
The detailed information I got is like the following:
> Cubuntu@ip-10-31-64-54:/usr/local/src/security_monkey/dart$ sudo /usr/lib/dart/bin/pub build
> Loading source assets... 
> Loading dart_to_js_script_rewriter, di/module_transformer, initialize/build/loader_replacer, observe, smoke/src/default_transformer and initialize transformers... 
> Loading angular transformers... (2.5s)
> Building security_monkey... (17.0s)
> [Info from Dart2JS]:
> Compiling security_monkey|web/main.dart...
> [Warning from Dart2JS on security_monkey|web/main.dart]:
> web/packages/angular/core/annotation_src.dart:3:44:
> Library 'package:di/di.dart' doesn't export a 'Visibility' declaration.
> Try removing 'Visibility' from the 'show' clause.
> import "package:di/di.dart" show Injector, Visibility, Factory;
>                                            ^^^^^^^^^^
> [Warning from Dart2JS on security_monkey|web/main.dart]:
> web/packages/angular/core/annotation_src.dart:3:56:
> Library 'package:di/di.dart' doesn't export a 'Factory' declaration.
> Try removing 'Factory' from the 'show' clause.
> import "package:di/di.dart" show Injector, Visibility, Factory;
>                                                        ^^^^^^^
> [Warning from Dart2JS on security_monkey|web/main.dart]:
> web/packages/angular/core/annotation.dart:11:5:
> Library 'package:angular/core/annotation_src.dart' doesn't export a 'ShadowRootAware' declaration.
> Try removing 'ShadowRootAware' from the 'show' clause.
>     ShadowRootAware,
>     ^^^^^^^^^^^^^^^
> [Warning from Dart2JS on security_monkey|web/main.dart]:
> web/packages/angular/core/module.dart:70:5:
> Library 'package:angular/core/module_internal.dart' doesn't export a 'CacheStats' declaration.
> Try removing 'CacheStats' from the 'show' clause.
>     CacheStats,
>     ^^^^^^^^^^
> [Warning from Dart2JS on security_monkey|web/main.dart]:
> web/packages/angular/core/module.dart:71:5:
> Library 'package:angular/core/module_internal.dart' doesn't export a 'ComponentCssRewriter' declaration.
> Try removing 'ComponentCssRewriter' from the 'show' clause.
>     ComponentCssRewriter,
>     ^^^^^^^^^^^^^^^^^^^^
> [Warning from Dart2JS on security_monkey|web/main.dart]:
> web/packages/angular/core/module.dart:50:5:
> Library 'package:angular/core_dom/module_internal.dart' doesn't export a 'NgAnimate' declaration.
> Try removing 'NgAnimate' from the 'show' clause.
>     NgAnimate,
>     ^^^^^^^^^
> [Warning from Dart2JS on security_monkey|web/main.dart]:
> web/packages/angular/core/module.dart:54:5:
> Library 'package:angular/core_dom/module_internal.dart' doesn't export a 'PendingAsync' declaration.
> Try removing 'PendingAsync' from the 'show' clause.
>     PendingAsync,
>     ^^^^^^^^^^^^
> [Dart2JS]:
> web/main.dart:
> 
> ****************************************************************
> * WARNING: dart:mirrors support in dart2js is experimental,
> *          and not recommended.
> *          This implementation of mirrors is incomplete,
> *          and often greatly increases the size of the generated
> *          JavaScript code.
> *
> * Your app imports dart:mirrors via:
> *   main.dart => package:security_monkey/security_monkey.dart => package:security_monkey/model/hammock_config.dart => dart:mirrors
> *   main.dart => main_generated_type_factory_maps.dart => package:security_monkey/security_monkey.dart => package:security_monkey/model/hammock_config.dart => dart:mirrors
> *   main.dart => main_static_metadata.dart => package:security_monkey/security_monkey.dart => package:security_monkey/model/hammock_config.dart => dart:mirrors
> *   main.dart => main_static_type_to_uri_mapper.dart => package:security_monkey/security_monkey.dart => package:security_monkey/model/hammock_config.dart => dart:mirrors
> *
> * You can disable this message by using the --enable-experimental-mirrors
> * command-line flag.
> *
> * To learn what to do next, please visit:
> *    http://dartlang.org/dart2js-reflection
> ****************************************************************
> 
> [Warning from Dart2JS on security_monkey|web/main.dart]:
> web/main_generated_type_factory_maps.dart:368:58:
> Additional argument.
>   import_44.Rect: (a1, a2, a3, a4) => new import_44.Rect(a1, a2, a3, a4),
>                                                          ^^
> [Info from Dart2JS on security_monkey|web/main.dart]:
> web/packages/angular_ui/utils/position.dart:100:3:
> This is the method declaration.
>   Rect({this.left:0, this.top:0, this.width:0, this.height:0});
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [Warning from Dart2JS on security_monkey|web/main.dart]:
> web/main_generated_type_factory_maps.dart:368:62:
> Additional argument.
>   import_44.Rect: (a1, a2, a3, a4) => new import_44.Rect(a1, a2, a3, a4),
>                                                              ^^
> [Info from Dart2JS on security_monkey|web/main.dart]:
> web/packages/angular_ui/utils/position.dart:100:3:
> This is the method declaration.
>   Rect({this.left:0, this.top:0, this.width:0, this.height:0});
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [Warning from Dart2JS on security_monkey|web/main.dart]:
> web/main_generated_type_factory_maps.dart:368:66:
> Additional argument.
>   import_44.Rect: (a1, a2, a3, a4) => new import_44.Rect(a1, a2, a3, a4),
>                                                                  ^^
> [Info from Dart2JS on security_monkey|web/main.dart]:
> web/packages/angular_ui/utils/position.dart:100:3:
> This is the method declaration.
>   Rect({this.left:0, this.top:0, this.width:0, this.height:0});
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [Warning from Dart2JS on security_monkey|web/main.dart]:
> web/main_generated_type_factory_maps.dart:368:70:
> Additional argument.
>   import_44.Rect: (a1, a2, a3, a4) => new import_44.Rect(a1, a2, a3, a4),
>                                                                      ^^
> [Info from Dart2JS on security_monkey|web/main.dart]:
> web/packages/angular_ui/utils/position.dart:100:3:
> This is the method declaration.
>   Rect({this.left:0, this.top:0, this.width:0, this.height:0});
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [Dart2JS on security_monkey|web/main.dart]:
> 4 warning(s) and 1 hint(s) suppressed in package:security_monkey.
> [Dart2JS on security_monkey|web/main.dart]:
> 4 warning(s) suppressed in package:angular.
> Exhausted heap space, trying to allocate 672 bytes.
> Exhausted heap space, trying to allocate 80 bytes.

**Comment by hobbits49** [comment]
The detailed information is like the following:
```
/usr/local/src/security_monkey/dart$ sudo /usr/lib/dart/bin/pub build
Loading source assets... 
Loading dart_to_js_script_rewriter, di/module_transformer, initialize/build/loader_replacer, observe, smoke/src/default_transformer and initialize transformers... 
Loading angular transformers... (2.5s)
Building security_monkey... (17.0s)
[Info from Dart2JS]:
Compiling security_monkey|web/main.dart...
[Warning from Dart2JS on security_monkey|web/main.dart]:
web/packages/angular/core/annotation_src.dart:3:44:
Library 'package:di/di.dart' doesn't export a 'Visibility' declaration.
Try removing 'Visibility' from the 'show' clause.
import "package:di/di.dart" show Injector, Visibility, Factory;
                                           ^^^^^^^^^^
[Warning from Dart2JS on security_monkey|web/main.dart]:
web/packages/angular/core/annotation_src.dart:3:56:
Library 'package:di/di.dart' doesn't export a 'Factory' declaration.
Try removing 'Factory' from the 'show' clause.
import "package:di/di.dart" show Injector, Visibility, Factory;
                                                       ^^^^^^^
[Warning from Dart2JS on security_monkey|web/main.dart]:
web/packages/angular/core/annotation.dart:11:5:
Library 'package:angular/core/annotation_src.dart' doesn't export a 'ShadowRootAware' declaration.
Try removing 'ShadowRootAware' from the 'show' clause.
    ShadowRootAware,
    ^^^^^^^^^^^^^^^
[Warning from Dart2JS on security_monkey|web/main.dart]:
web/packages/angular/core/module.dart:70:5:
Library 'package:angular/core/module_internal.dart' doesn't export a 'CacheStats' declaration.
Try removing 'CacheStats' from the 'show' clause.
    CacheStats,
    ^^^^^^^^^^
[Warning from Dart2JS on security_monkey|web/main.dart]:
web/packages/angular/core/module.dart:71:5:
Library 'package:angular/core/module_internal.dart' doesn't export a 'ComponentCssRewriter' declaration.
Try removing 'ComponentCssRewriter' from the 'show' clause.
    ComponentCssRewriter,
    ^^^^^^^^^^^^^^^^^^^^
[Warning from Dart2JS on security_monkey|web/main.dart]:
web/packages/angular/core/module.dart:50:5:
Library 'package:angular/core_dom/module_internal.dart' doesn't export a 'NgAnimate' declaration.
Try removing 'NgAnimate' from the 'show' clause.
    NgAnimate,
    ^^^^^^^^^
[Warning from Dart2JS on security_monkey|web/main.dart]:
web/packages/angular/core/module.dart:54:5:
Library 'package:angular/core_dom/module_internal.dart' doesn't export a 'PendingAsync' declaration.
Try removing 'PendingAsync' from the 'show' clause.
    PendingAsync,
    ^^^^^^^^^^^^
[Dart2JS]:
web/main.dart:

****************************************************************
* WARNING: dart:mirrors support in dart2js is experimental,
*          and not recommended.
*          This implementation of mirrors is incomplete,
*          and often greatly increases the size of the generated
*          JavaScript code.
*
* Your app imports dart:mirrors via:
*   main.dart => package:security_monkey/security_monkey.dart => package:security_monkey/model/hammock_config.dart => dart:mirrors
*   main.dart => main_generated_type_factory_maps.dart => package:security_monkey/security_monkey.dart => package:security_monkey/model/hammock_config.dart => dart:mirrors
*   main.dart => main_static_metadata.dart => package:security_monkey/security_monkey.dart => package:security_monkey/model/hammock_config.dart => dart:mirrors
*   main.dart => main_static_type_to_uri_mapper.dart => package:security_monkey/security_monkey.dart => package:security_monkey/model/hammock_config.dart => dart:mirrors
*
* You can disable this message by using the --enable-experimental-mirrors
* command-line flag.
*
* To learn what to do next, please visit:
*    http://dartlang.org/dart2js-reflection
****************************************************************

[Warning from Dart2JS on security_monkey|web/main.dart]:
web/main_generated_type_factory_maps.dart:368:58:
Additional argument.
  import_44.Rect: (a1, a2, a3, a4) => new import_44.Rect(a1, a2, a3, a4),
                                                         ^^
[Info from Dart2JS on security_monkey|web/main.dart]:
web/packages/angular_ui/utils/position.dart:100:3:
This is the method declaration.
  Rect({this.left:0, this.top:0, this.width:0, this.height:0});
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Warning from Dart2JS on security_monkey|web/main.dart]:
web/main_generated_type_factory_maps.dart:368:62:
Additional argument.
  import_44.Rect: (a1, a2, a3, a4) => new import_44.Rect(a1, a2, a3, a4),
                                                             ^^
[Info from Dart2JS on security_monkey|web/main.dart]:
web/packages/angular_ui/utils/position.dart:100:3:
This is the method declaration.
  Rect({this.left:0, this.top:0, this.width:0, this.height:0});
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Warning from Dart2JS on security_monkey|web/main.dart]:
web/main_generated_type_factory_maps.dart:368:66:
Additional argument.
  import_44.Rect: (a1, a2, a3, a4) => new import_44.Rect(a1, a2, a3, a4),
                                                                 ^^
[Info from Dart2JS on security_monkey|web/main.dart]:
web/packages/angular_ui/utils/position.dart:100:3:
This is the method declaration.
  Rect({this.left:0, this.top:0, this.width:0, this.height:0});
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Warning from Dart2JS on security_monkey|web/main.dart]:
web/main_generated_type_factory_maps.dart:368:70:
Additional argument.
  import_44.Rect: (a1, a2, a3, a4) => new import_44.Rect(a1, a2, a3, a4),
                                                                     ^^
[Info from Dart2JS on security_monkey|web/main.dart]:
web/packages/angular_ui/utils/position.dart:100:3:
This is the method declaration.
  Rect({this.left:0, this.top:0, this.width:0, this.height:0});
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Dart2JS on security_monkey|web/main.dart]:
4 warning(s) and 1 hint(s) suppressed in package:security_monkey.
[Dart2JS on security_monkey|web/main.dart]:
4 warning(s) suppressed in package:angular.
Exhausted heap space, trying to allocate 672 bytes.
Exhausted heap space, trying to allocate 80 bytes.
```

**Comment by monkeysecurity** [comment]
Are you on a `t1.micro` or something?

**Comment by monkeysecurity** [comment]
You can download the compiled javascript from the latest release:

https://github.com/Netflix/security_monkey/releases/tag/v0.8.0

Grab the `static.tar.gz` and extract it into the security_monkey package.

**Comment by hobbits49** [comment]
@monkeysecurity Thank you for the reply. I'm using t2.micro, and another guy in our company successfully used this to set up the security monkey. Btw, it's really a nice tool, thank you for the contributions and your suggestions!

**Comment by monkeysecurity** [comment]
Hey @hobbits49 - Thanks for the complement.

I've heard from someone else that the t2.micro doesn't have the memory to compile the dart.  Options are to pull the tar file from the last release, or compile the dart into JS on a machine with more memory and scp the files to your micro.

#60 has a comment towards the end about the micro.

**Comment by hobbits49** [comment]
That make sense. Thanks a lot!
