### ISSUE TITLE
Docker secmonkey-nginx doesn't start.

### ISSUE THREAD

**Issue by tunkaflux** [Netflix/security_monkey#589]
Hello,

I've installed Security Monkey via docker locally to check it out. I can get all containers to run except the secmonkey-nginx one. It fails with:

```
Wed Mar  8 00:58:45 UTC 2017 Error: Missing files required for SSL
sed: cannot rename /etc/nginx/conf.d/securitymonkey.conf: Device or resource busy
2017/03/08 00:58:45 [emerg] 1#1: PEM_read_bio_X509_AUX("/etc/nginx/ssl/server.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] PEM_read_bio_X509_AUX("/etc/nginx/ssl/server.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
Wed Mar  8 01:00:45 UTC 2017 Error: Missing files required for SSL
sed: cannot rename /etc/nginx/conf.d/securitymonkey.conf: Device or resource busy
2017/03/08 01:00:45 [emerg] 1#1: PEM_read_bio_X509_AUX("/etc/nginx/ssl/server.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] PEM_read_bio_X509_AUX("/etc/nginx/ssl/server.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
Wed Mar  8 01:05:56 UTC 2017 Error: Missing files required for SSL
sed: cannot rename /etc/nginx/conf.d/securitymonkey.conf: Device or resource busy
2017/03/08 01:05:56 [emerg] 1#1: PEM_read_bio_X509_AUX("/etc/nginx/ssl/server.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] PEM_read_bio_X509_AUX("/etc/nginx/ssl/server.crt") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
```
Any idea how I can fix this?

**Comment by monkeysecurity** [comment]
Hey @tunkaflux - I'm hoping @jnbnyc can help out on this one.

Looking at the nginx config, it looks like SSL has not been disabled.  Nginx will be looking for an SSL cert.
https://github.com/Netflix/security_monkey/blob/develop/docker/nginx/securitymonkey.conf#L9

However, the line in the dockerfile that copies your SSL cert over is commented out.
https://github.com/Netflix/security_monkey/blame/develop/docker/nginx/Dockerfile#L48

The easiest thing may be to uncomment line 48 in the dockerfile and provide a `server.crt` and a `server.key`.  If you're just using this for dev, you can reuse the self signed certs here:
https://github.com/Netflix-Skunkworks/zerotodocker/tree/master/security_monkey/0.3.4/security_monkey-nginx

For any real-world use, you'll need to get a real certificate.

**Comment by jnbnyc** [comment]
Hi @tunkaflux, for local development I used the insecure certs provided by Netflix-Skunkworks.
You don't want add certs in your container during your build, these should be provided with a volume. 

Place your `server.crt` and `server.key` as specified in the docker-compose.yml here:
https://github.com/Netflix/security_monkey/blob/develop/docker-compose.yml#L50

CC @monkeysecurity
