### ISSUE TITLE
CSRF protection on SSO API

### ISSUE THREAD

**Issue by crruthe** [Netflix/security_monkey#593]
Looks like OneLogin sends its response SAML token as a POST request.

This is being blocked by the CSRF protection and returning 
```
{"status": 400, "message": "Bad Request"}
```

You can solve this by adding a CSRF exempt for the SSO blueprint. E.g.

```
from security_monkey import db, rbac, csrf

mod = Blueprint('sso', __name__)
csrf.exempt(mod)
```

Given that the requests are authenticated and signed, I don't see a big issue with a CSRF exempt on SSO.

**Comment by crruthe** [comment]
Sorry no PR, I don't have an environment setup for this at the moment :(

**Comment by monkeysecurity** [comment]
PR Merged.
