### ISSUE TITLE
Cloudtrail Integration 

### ISSUE THREAD

**Issue by jefe78** [Netflix/security_monkey#599]
In the announcement post, there is mention of of Cloudtrail integration as another source of informaiton for items. http://techblog.netflix.com/2014/06/announcing-security-monkey-aws-security.html - Open Items and Future Plans. Is this still an intended feature? Is there an ETA? Thanks!

**Comment by monkeysecurity** [comment]
Yes.  It's part of the event driven architecture we're hoping to have out this summer.

We have a working beta and it's great.

**Comment by jefe78** [comment]
Great to hear! Is it safe to assume this is in the dev branch?

**Comment by monkeysecurity** [comment]
The DB tables have already been modified to support CloudTrail, but the event driven architecture is in a separate private repo.

**Comment by monkeysecurity** [comment]
http://techblog.netflix.com/2017/03/netflix-security-monkey-on-google-cloud.html

^Updated techblog post.

CloudTrail is a part of the Event Driven future of SM.

**Comment by jefe78** [comment]
This is great stuff. We're just starting to role out SM after testing custom solutions and Scout2 and are really excited about this announcement. Thanks again!

**Comment by jefe78** [comment]
I was wondering what the state of this was? We're looking to use this feature and would be happy to beta test.
