### ISSUE TITLE
Dart problem

### ISSUE THREAD

**Issue by JaguarSecurity** [Netflix/security_monkey#60]
This is the error I am getting.

/usr/lib/dart$ Could not find a file named "pubspec.yaml" in "/usr/lib/dart".

**Comment by rishikv** [comment]
I am trying to do the dart pub build on ubuntu (in the /usr/local/src/security_monkey/dart directory), it is hanging without completion. Tried all the options specified on the net for the issue (like changing the DEFAULT_CACHE_SIZE...). I tried dart 1.13.0 and 1.14.0-dev.1.0. If anybody has a similar issue please post the resolution. Thanks for your help.

**Comment by zoechi** [comment]
@rishikv you could try `--trace` or `--verbose` to get more information about the cause.

**Comment by rishikv** [comment]
Thanks i tried those options i see bunch of warnings and it hangs

[Warning from Dart2JS on security_monkey|web/main.dart]:

packages/angular/core/module.dart:54:5:

Library 'package:angular/core_dom/module_internal.dart' doesn't export a
'PendingAsync' declaration.

Try removing 'PendingAsync' from the 'show' clause.

    PendingAsync,

    ^^^^^^^^^^^^

[Dart2JS]:

web/main.dart:


****************************************************************

* WARNING: dart:mirrors support in dart2js is experimental,

*          and not recommended.

*          This implementation of mirrors is incomplete,

*          and often greatly increases the size of the generated

*          JavaScript code.

*

* Your app imports dart:mirrors via:

*   main.dart => package:security_monkey/security_monkey.dart =>
package:security_monkey/model/hammock_config.dart => dart:mirrors

*   main.dart => main_generated_type_factory_maps.dart =>
package:security_monkey/security_monkey.dart =>
package:security_monkey/model/hammock_config.dart => dart:mirrors

*   main.dart => main_static_metadata.dart =>
package:security_monkey/security_monkey.dart =>
package:security_monkey/model/hammock_config.dart => dart:mirrors

*   main.dart => main_static_type_to_uri_mapper.dart =>
package:security_monkey/security_monkey.dart =>
package:security_monkey/model/hammock_config.dart => dart:mirrors

*

* You can disable this message by using the --enable-experimental-mirrors

* command-line flag.

*

* To learn what to do next, please visit:

*    http://dartlang.org/dart2js-reflection

****************************************************************

**Comment by zoechi** [comment]
These messages don't indicate real issues. There is a redundant `PendingAsync` in the `show` clause, but it seems not to be used anyway.
The mirrors warning is shown for all applications using mirrors.
That's no real progress :(

**Comment by rishikv** [comment]
yeah, i suppressed the warning by adding commandLineOptions in yaml file.
Not sure what else i can try

**Comment by zoechi** [comment]
Just a wild guess. I don't know if this is still used at all, but might be worth a try:

`export DART_VM_OPTIONS=--old_gen_heap_size=2048` 
(maybe with bigger values) 

before you run `pub build`.

**Comment by monkeysecurity** [comment]
Hey @rishikv - The latest dart breaks the build.

See #259. Solution is to pin to v1.12.2-1.

**Comment by zoechi** [comment]
Similar issue reported at 
- https://github.com/dart-lang/code_transformers/issues/23#issuecomment-158359783
- https://github.com/dart-lang/sdk/issues/25009

**Comment by rishikv** [comment]
I tried 1.12.2-1 but i see the build hangs after printing this on the console. Any other suggestions? (tried increasing the old_gen_heap_size)

FINE: [Fine from InjectorGenerator on security_monkey|web/main.dart]:
    | Took 8.7s (8.3s awaiting secondary inputs).

**Comment by monkeysecurity** [comment]
You aren't on like a t1.micro or something are you?  I've seen a lack of memory cause problems with the dart build phase.

**Comment by monkeysecurity** [comment]
You can always download the complied JS from the releases page:
https://github.com/Netflix/security_monkey/releases

**Comment by rishikv** [comment]
Excellent point sir. Thanks for your insight. I am on t1.micro. didn't realize that t1.micro cause memory problems
