### ISSUE TITLE
Outdated docker instructions

### ISSUE THREAD

**Issue by kpcyrd** [Netflix/security_monkey#603]
I was following the [quickstart][1] and clicked the first docker link in `Before we start, consider following the docker instructions .`, which sent me to this document:

https://github.com/Netflix-Skunkworks/zerotodocker/wiki/Security-Monkey

This seems to be a very old document, as it was last updated in 2014 and references 0.2.0 and a latest folder in that repo, which is also used to build the [docker images][2], is 0.3.4. Also the `postgres:9.3.5` image referenced  doesn't exist anymore.

The [second link][3] in the docker paragraph seems to be more up to date and uses docker-compose.

Please consider updating [this document][4] according to the latest docker instructions available :)

[1]: http://securitymonkey.readthedocs.io/en/latest/quickstart.html
[2]: https://hub.docker.com/r/netflixoss/security_monkey-api/
[3]: http://securitymonkey.readthedocs.io/en/latest/docker.html
[4]: https://github.com/Netflix/security_monkey/blob/aaeab01a762b2f5fe22a9ca4cea99eeba05e512b/docs/quickstart.rst#docker-images

**Comment by monkeysecurity** [comment]
Thanks - I'll remove the reference to the zerotodocker repo.

**Comment by monkeysecurity** [comment]
Fixed in #639
