### ISSUE TITLE
Users created with CLI have plaintext passwords 😱

### ISSUE THREAD

**Issue by mikegrima** [Netflix/security_monkey#618]
There is a bug in the `manage.py` script where users created via the CLI have plaintext passwords stored in the database.

**NOTE**:
- This **DOES NOT** affect users created via the web UI
- This **DOES NOT** affect users that use SSO for login
- This **ONLY** affects users that were created via the command line's `manage.py` command.

**Comment by mikegrima** [comment]
Addressed in #619 .

Note: This makes an _**ASSUMPTION**_ that users are using `bcrypt` as configured in their config file, which is the default value.

**Comment by monkeysecurity** [comment]
Merged #619
