### ISSUE TITLE
Login page fails to load CSS and images

### ISSUE THREAD

**Issue by ivanlei** [Netflix/security_monkey#63]
Working on OS X, doing initial setup.

The page loads from ```http://127.0.0.1:5000/login``` but CSS and images don't load.
The dart console shows:
```
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
  http://127.0.0.1:5000/static/css/bootstrap.min.css
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
  http://127.0.0.1:5000/static/css/main.css
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
  http://127.0.0.1:5000/static/css/signin.css
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
  http://127.0.0.1:5000/static/js/bootstrap.min.js
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
  http://127.0.0.1:5000/static/images/securitymonkeyHead.png
```

**Comment by challanuk202** [comment]
But, I have created static folder, not getting Register button in UI.

**Comment by mstair** [comment]
Verify permissions are correct, ie.

`sudo chgrp -R www-data /usr/local/src/security_monkey`

**Comment by challanuk202** [comment]
again facing below error:- 
"GET /api/1/auth/providers HTTP/1.1" 200 2 "http://myserver:443/login?next=http%3A%2F%2F35.205.44.219%3A443%2F" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

**Comment by mstair** [comment]
Hmm, can you try https vs http?

**Comment by challanuk202** [comment]
http only # https not working in my machine

**Comment by mstair** [comment]
Did you change your nginx config to disable ssl?

`/etc/nginx/sites-enabled/security_monkey.conf`

**Comment by challanuk202** [comment]
server {
   listen      0.0.0.0:443;
   ssl_certificate /etc/ssl/certs/server.crt;
   ssl_certificate_key /etc/ssl/private/server.key;
   access_log  /var/log/security_monkey/security_monkey.access.log;
   error_log   /var/log/security_monkey/security_monkey.error.log;

   location ~* ^/(reset|confirm|healthcheck|register|login|logout|api) {
        proxy_read_timeout 1800;
        proxy_pass  http://127.0.0.1:5000;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header        Host            $http_host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static {
        rewrite ^/static/(.*)$ /$1 break;
        root /usr/local/src/security_monkey/security_monkey/static;
        index ui.html;
    }

    location / {
        root /usr/local/src/security_monkey/security_monkey/static;
        index ui.html;
    }

}

**Comment by mstair** [comment]
Ok, so no ssl. Let me try to configure one of my instances with http

**Comment by challanuk202** [comment]
if i add ssl , i am getting below error: Error loading resource from API. Error: <HTTP 400: <html>
 <head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
 <body bgcolor="white">
 <center><h1>400 Bad Request</h1></center>
 <center>The plain HTTP request was sent to HTTPS port</center>
 <hr><center>nginx/1.4.6 (Ubuntu)</center>
 </body>
 </html>
 
 
 
 
 
 
 >

**Comment by mstair** [comment]
You have to then use https vs http in the URL. I get a "Bad Request" error for the CSRF session token when I try http, you may need to setup https.

**Comment by challanuk202** [comment]
while connecting https hitting  to 404[](url)

**Comment by challanuk202** [comment]
![api_error](https://user-images.githubusercontent.com/30466456/32783365-7713476e-c971-11e7-94b5-82f5abe88022.PNG)

**Comment by mstair** [comment]
Ping me on Gitter and see if we can debug more. Looks like your API server is down.
