### ISSUE TITLE
Send Alerts from a specific AWS account to the corresponding team/email DL

### ISSUE THREAD

**Issue by fanemsm** [Netflix/security_monkey#635]
Hi all,

I would like to know if it is possible to set Security Monkey to send the alerts corresponding to an AWS account to a specific email DL which corresponds to the owner/ technical team for the specific account.

Another possible feature/ request is to link the Security Monkey to a specific AWS account so it will be able to view, comment, justify issues only to the mentioned account.

Example: 3 AWS accounts X,Y,Z and 4 users: 1,2,3,4
user 1 would receive alerts, view and comment only for account X
user 2 would receive alerts, view and comment only for account Y
user 3,4 as they offer support and SOC would receive alerts, view and comment only for accounts X,Y,Z

Best regards,

Stefan Magda.

**Comment by mikegrima** [comment]
Hello @fanemsm .

You should be able to perform all of the items requested.

If you require assistance, please reach out to us on our Gitter channel.
