### ISSUE TITLE
S3 Auditor Needs Source VPC Exemption

### ISSUE THREAD

**Issue by mikegrima** [Netflix/security_monkey#641]
If you have an S3 policy that looks like this:
```
        "Effect": "Allow",
        "Action": "s3:GetObject",
        "Resource": [
          "arn:aws:s3:::some-bucket/*"
        ],
        "Condition": {
          "StringEquals": {
            "aws:sourceVpc": "vpc-01234567"
          }
        },
        "Principal": "*"
      }
```

The Auditor will flag this as the bucket being wide open.  The Auditor needs to check for the `aws:sourceVpc` condition.

Also, the Auditor thinks CloudFront ARNs are unknown cross-account access. - Will need some logic to parse out the CloudFront ARN and ignore that (or at the very least, raise an issue that is not rated 10).

**Comment by monkeysecurity** [comment]
Fixed in #757
