### ISSUE TITLE
Save account in the UI not working

### ISSUE THREAD

**Issue by BobPeterson1881** [Netflix/security_monkey#647]
Saving an account in the UI does is erroring out.

I was seeing error "TypeError: update() got multiple values for keyword argument 'custom_fields'"

security_monkey/views/account.py is passing an extra parameter "account_id" 

        account = account_manager.update(account_id, account_type, name, active,
                    third_party, notes, identifier, custom_fields=custom_fields)

The update function in security_monkey/account_manager.py is not expecting the account_id

    def update(self, account_type, name, active, third_party, notes, identifier, custom_fields=None):

I am not sure which is the best place to fix the issue.  I changed account.py on my system and it worked, but I am not sure if it would be better to change account_manager.py to accept the account_id parameter?  Not sure if there is future plans/needs for the account_id by account_manager?

**Comment by monkeysecurity** [comment]
I believe @mikegrima removed the `account_id` parameter in PR #624.

https://github.com/Netflix/security_monkey/pull/624/files#diff-b00f8d4ff9c319f6ff3905c71dc4a02fL71

**Comment by BobPeterson1881** [comment]
Yep, I failed to look at the history on account_manager.py.  I just saw the change that removed the account_id.

**Comment by mikegrima** [comment]
Found the bug -- working on a fix now.

**Comment by mikegrima** [comment]
Submitted PR for fix.  Confirmed that it worked when testing locally.

**Comment by mikegrima** [comment]
Merged.
