### ISSUE TITLE
track configuration changed user

### ISSUE THREAD

**Issue by hifx-jeffin** [Netflix/security_monkey#649]
Hi Team,

I am working on getting a prof of concept set up, and SM tracks configuration changes pretty well.

While evaluating this, I had a though about to track the configuration changed user details, What I mean was we had more than 100 users (admin users) who authorised to change the configurations. 

Suppose if one of our user changed the securitygroup and I need to track who ( which iam user ) done the changes. Is it possible to track this with security_monkey?

This is the a sample output from SM,

```
{
    "name": "stag-xxxxxxxxxxxxx-xxxxxx-xxxx",
    "rules": [
        {
            "rule_type": "ingress",
            "from_port": null,
            "ip_protocol": "-1",
            "to_port": null,
            "owner_id": "########",
            "group_id": "sg-362a0a53",
            "cidr_ip": null,
            "name": null
        },
        {
            "rule_type": "ingress",
            "from_port": null,
            "ip_protocol": "-1",
            "to_port": null,
            "owner_id": "#######",
            "group_id": "sg-6b472b0d",
            "cidr_ip": null,
            "name": null
        },
        {
            "rule_type": "ingress",
            "from_port": null,
            "ip_protocol": "-1",
            "to_port": null,
            "owner_id": "#######",
            "group_id": "sg-d65272b0",
            "cidr_ip": null,
            "name": null
        },
        {
            "rule_type": "ingress",
            "from_port": "80",
            "ip_protocol": "tcp",
            "to_port": "80",
            "owner_id": "#######",
            "group_id": "sg-a2846edb",
            "cidr_ip": null,
            "name": null
        },
        {
            "rule_type": "ingress",
            "from_port": "80",
            "ip_protocol": "tcp",
            "to_port": "80",
            "owner_id": "#######",
            "group_id": "sg-c8866cb1",
            "cidr_ip": null,
            "name": null
        },
        {
            "rule_type": "egress",
            "from_port": null,
            "ip_protocol": "-1",
            "to_port": null,
            "owner_id": null,
            "group_id": null,
            "cidr_ip": "0.0.0.0/0",
            "name": null
        },
        {
            "rule_type": "ingress",
            "from_port": null,
            "ip_protocol": "-1",
            "to_port": null,
            "owner_id": null,
            "group_id": null,
            "cidr_ip": "172.16.5.0/24",
            "name": null
        },
        {
            "rule_type": "ingress",
            "from_port": null,
            "ip_protocol": "-1",
            "to_port": null,
            "owner_id": "############################",
            "group_id": "sg-800c28e5",
            "cidr_ip": null,
            "name": null
        }
    ],
    "description": "stag-XXXX-XXXXX-XXXX",
    "vpc_id": "XXX-XXXXXX",
    "assigned_to": [
        {
            "PROJECT": "STAG-XXX",
            "instance_id": "i-xxxxxxxxxxxxxxxxx",
            "Name": "stag-XXX-xxxx-xxxx",
            "User": "ec2-user"
        },
        {
            "PROJECT": "STAG-XXX",
            "instance_id": "i-xxxxxxxxxxxxxxxxxxxxxxxx",
            "Name": "stag-XXX-xxxxxxxxxxxxxx-xxx",
            "User": "ec2-user"
        }
    ],
    "region": "eu-west-1",
    "id": "sg-4c9a7035",
    "arn": "arn:aws:ec2:eu-west-1:XXXXXXXXXXXXXX:security-group/sg-4c9a7035",
    "owner_id": "XXXXXXXXXXXXXXXX"
}

```

Please let me know if we can track the iam user from this or is it possible to track the user details?

Thanks in Advance

**Comment by mikegrima** [comment]
Hello @hifx-jeffin :  IAM Users are tracked in Security Monkey as well.

Are you not able to get them tracked properly?

**Comment by hifx-jeffin** [comment]
Yes, I am able to track IAM user properly, but what I need to know is, is it possible to track the user who done the configuration changes in any technology,

Suppose my collage changed the security group to allow all traffic from his IP. I am security_monkey admin and I got the alert that sg-4c9a7035 is changed and that's works well, but I need to know who done this change, I mean which IAM user done the configuration changes.

**Comment by mikegrima** [comment]
Ah yes, I understand now.

We are working on making changes to Security Monkey to capture CloudTrail data (via CloudWatch Events). We have made the necessary changes to the Security Monkey database to store this. In the UI, you should see `CloudTrail` on an item (currently grayed out).

We have an internal concept that triggers a lambda upon CloudTrail -> CloudWatch Events that will capture the CloudTrail data, as well as store details about the change that occurred. However, it isn't quite ready to be OSS'd yet. But, we'll certainly let you know when that is available!

**Comment by hifx-jeffin** [comment]
@mikegrima Thanks
