### ISSUE TITLE
Item Table should display unjustified score, not total score.

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#654]
Item Table should display unjustified score, not total score.

Brought up by @mirkatson_twitter in gitter.

Should be a simple change.

Alternatively, we could add a new column to the item table, so it could display the totalScore in one column and the unjustified score in another.

**Comment by mcolatosti** [comment]
Two recommendations:  
Add "Exempt" in addition to  Justified.
"Exempt" - indicates a confirmed non-issue, ie. there is no risk.  but not worth the user creating a "global" exception rule?  This would result in risk being completely removed from justified or unjustified scoring.

A separate display feature that would allow for display of score based on all findings (like today) and a filter that would subtract the scores of those marked "Justified".  

The later would be such an incredible feature in terms of risk management.  The former would make the need for creating very specific exception rules no longer needed and is a nice to have.

**Comment by monkeysecurity** [comment]
Dashboard should also be updated to show the unjustified account score.

**Comment by monkeysecurity** [comment]
May be fixed in #825 - testing now
