### ISSUE TITLE
1 instance to monitor both GCP and AWS

### ISSUE THREAD

**Issue by cplvic** [Netflix/security_monkey#678]
Just wondering if a single instance can be setup to monitor both GCE and AWS?
Thanks

**Comment by monkeysecurity** [comment]
Yes.  That's totally possible.

# Monitoring AWS from GCP:
If your instance is in GCP, you will need to login to the AWS console and create an IAM user with an access key and a secret key (with the ability to assume role into SecurityMonkey in your AWS accounts.)  This access key and secret key will need to be placed in a file as described here:
- http://boto.cloudhackers.com/en/latest/boto_config_tut.html#details

Example:
`/etc/boto.cfg`: 
```
[Credentials]
aws_access_key_id = <your_access_key_here>
aws_secret_access_key = <your_secret_key_here>
```

# Monitoring GCP from AWS:
You'll need to create a GCP service account and download a private key in JSON format:
https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md

When you add the GCP account to security_monkey, you'll need to tell security_monkey where on disk it can find that JSON file.
