### ISSUE TITLE
Unable to edit account names

### ISSUE THREAD

**Issue by blakestoddard** [Netflix/security_monkey#680]
If you create an account to be monitored (doesn't matter if it's an AWS or GCP account) and then go back, edit the name, and click "Save" you get the following error in the UI:
```
Error loading resource from API. Error: <HTTP 404: {"status": "error. Account ID not found."}>
```
and the following error in `securitymonkey.log`, where \<account name\> is the **new** account name:
```
2017-04-18 13:51:10,965 ERROR: Account with name <account name> does not exist [in /usr/local/src/security_monkey/security_monkey/account_manager.py:79]
```

**Comment by monkeysecurity** [comment]
confirmed bug

**Comment by monkeysecurity** [comment]
Looks like #624 broke this with an update to `AccountManager::update()`

https://github.com/Netflix/security_monkey/pull/624/files#diff-b00f8d4ff9c319f6ff3905c71dc4a02fL71

It use to query based on `account.id`, but now queries based on `account.name`, which doesn't work when you're updating an account to change the name.

**Comment by mikegrima** [comment]
Trying to recall why I did that...

**Comment by mikegrima** [comment]
Going to make a PR to test and address.
