### ISSUE TITLE
security_monkey should easily allow selecting which auditor checks to run

### ISSUE THREAD

**Issue by ivanlei** [Netflix/security_monkey#69]
Here at Yelp, we secure our AWS deployments differently than Netflix does. Makes sense that we'll want different auditor checks. There's no easy way to do that today.

Maybe the solution is some UI that lets us enable/disable auditor checks.

**Comment by monkeysecurity** [comment]
@ivanlei fixed this issue long ago with the Auditor Settings tab.

Closing issue.
