### ISSUE TITLE
Using the public Google SMTP relay in flask mailer

### ISSUE THREAD

**Issue by phillycheeze** [Netflix/security_monkey#700]
Is it possible to use the `smtp-relay.gmail.com` smtp endpoint in security monkey? It doesn't use credentials (IP authentication) and I have tried the following:

1. Remove the `MAIL_USERNAME` and `MAIL_USERNAME` config variables in config.py
2. Simple set those variables to empty strings
3. Used ports 25, 465, and 587. 

The errors I get are below:
```
2017-04-26 13:08:47,657 WARNING: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/security_monkey-0.9.0-py2.7.egg/security_monkey/common/utils.py", line 77, in send_email
    mail.send(msg)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Mail-0.9.0-py2.7.egg/flask_mail.py", line 415, in send
    with self.connect() as connection:
  File "/usr/local/lib/python2.7/dist-packages/Flask_Mail-0.9.0-py2.7.egg/flask_mail.py", line 123, in __enter__
    self.host = self.configure_host()
  File "/usr/local/lib/python2.7/dist-packages/Flask_Mail-0.9.0-py2.7.egg/flask_mail.py", line 144, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "/usr/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (454, '4.7.0 Too many login attempts, please try again later. q16sm2426776qke.0 - gsmtp')
 [in /usr/local/lib/python2.7/dist-packages/security_monkey-0.9.0-py2.7.egg/security_monkey/common/utils.py:82]
2017-04-26 13:08:47,659 INFO: Job "run_change_reporter (trigger: interval[1:00:00], next run at: 2017-04-26 13:56:19.678224)" executed successfully [in build/bdist.linux-x86_64/egg/apscheduler/scheduler.py:527]
```

Clearly seems like SM tries to send credentials regardless if they are provided in the config. 

More info: [GApps SMTP Relay](https://support.google.com/a/answer/176600?hl=en)

**Comment by monkeysecurity** [comment]
Good question for the Flask-Mail project:

This example seems to indicate that credentials are important.
http://flask.pocoo.org/snippets/85/

**Comment by phillycheeze** [comment]
Should have expanded a bit more. I am using AWS and this is simply for email notifications. 

At the bottom I have provided an example flask configuration that works with the SMTP relay. If you don't provide the `MAIL_USERNAME` and `MAIL_PASSWORD` parameters to the config initialization, flask-mail won't attempt to authenticate.

The issue is that it seems security monkey is adding these parameters even when they are not provided in the `config.py` file. 

I might play around and try to fix this myself and submit a PR if I find out anything :)

Example app:
```
from flask import Flask
from flask.ext.mail import Mail, Message

app = Flask(__name__)

app.config.update(
    DEBUG=True,
    MAIL_SERVER='smtp-relay.gmail.com',
    MAIL_PORT=465,
    MAIL_USE_TLS=True,
)

mail = Mail(app)

def sendmail():
    msg = Message(
        'Subject',
        sender='cat@example.com',
        recipients=['meow@example.com'])
    msg.body = "Body here"
    mail.send(msg)
```

**Comment by phillycheeze** [comment]
Okay, well the problem was mostly user error. I needed to run the setup python script in the virtual environment again after editing the config. I also switched `MAIL_USE_SSL` to `MAIL_USE_TLS`.

In case anyone else has a similar problem, what I ran after changing the config:
```
virtualenv venv
source venv/bin/activate
pip install --upgrade setuptools
pip install --upgrade pip
pip install --upgrade urllib3[secure]
python setup.py install
```
