### ISSUE TITLE
Errors while running monkey add_account

### ISSUE THREAD

**Issue by subbu05** [Netflix/security_monkey#704]
https://github.com/Netflix/security_monkey/blob/v0.9.1/docs/docker.md

configured account, name and ran command

`monkey add_account_aws --number $account --name $name -r SecurityMonkey`
```
monkey add_account_aws --number $account --name $name -r SecurityMonkey
2017-04-26 18:27:48,968 INFO: Started thread pool with 25 core threads and 30 maximum threads [in build/bdist.linux-x86_64/egg/apscheduler/threadpool.py:52]
usage: monkey add_account_aws [-h] -n NAME [--thirdparty] [--active]
                              [--notes NOTES] --id IDENTIFIER
                              [--update-existing]
                              [--canonical_id CANONICAL_ID]
                              [--s3_name S3_NAME] [--role_name ROLE_NAME]
monkey add_account_aws: error: argument --id is required
```

**Comment by tunkaflux** [comment]
"monkey add_account_aws: error: argument --id is required" means you didn't specify an id...

**Comment by subbu05** [comment]
what id I must provide?
 According to install steps, id was not mentioned in the command.

**Comment by tunkaflux** [comment]
Oh I see, I think "--number" needed to be "--id" in the command above :)
I think it should be `monkey add_account_aws --id $account --name $name -r SecurityMonkey`

**Comment by monkeysecurity** [comment]
FYI - AWS calls them identifiers and not numbers:

http://docs.aws.amazon.com/general/latest/gr/acct-identifiers.html
