### ISSUE TITLE
SECURITY_MONKEY_POSTGRES_PORT wrong type

### ISSUE THREAD

**Issue by corest** [Netflix/security_monkey#707]
In file https://github.com/Netflix/security_monkey/blob/develop/env-config/config-docker.py there is sql alchemy database uri construction:

```
SQLALCHEMY_DATABASE_URI = 'postgresql://%s:%s@%s:%d/%s' % (
    os.getenv('SECURITY_MONKEY_POSTGRES_USER', 'postgres'),
    os.getenv('SECURITY_MONKEY_POSTGRES_PASSWORD', 'securitymonkeypassword'),
    os.getenv('SECURITY_MONKEY_POSTGRES_HOST', 'localhost'),
    os.getenv('SECURITY_MONKEY_POSTGRES_PORT', 5432),
    os.getenv('SECURITY_MONKEY_POSTGRES_DATABASE', 'secmonkey')
)
```

While you are not overriding _port_ - it works fine. But if you define environment variable like this `SECURITY_MONKEY_POSTGRES_PORT=5432` - there will be error `TypeError: %d format: a number is required, not str` due to wrong port field type.

**Comment by monkeysecurity** [comment]
Do you want to send us a PR that replaces that `%d` with a `%s`

And also casts the default to a str:
`os.getenv('SECURITY_MONKEY_POSTGRES_PORT', str(5432)),`

?

**Comment by corest** [comment]
@monkeysecurity 
There is PR https://github.com/Netflix/security_monkey/pull/708 already. I'm not sure about duplicating casting

**Comment by monkeysecurity** [comment]
PR merged.
