### ISSUE TITLE
Error getting favicon on the login page

### ISSUE THREAD

**Issue by kaelad02** [Netflix/security_monkey#712]
I setup Security Monkey from the develop branch late last week. I took a look at the security_monkey.error.log file and came across the following message. _Note:_ I changed addresses from what's actually in the log.

`2017/04/27 20:36:53 [error] 1493#1493: *2609 open() "/usr/local/src/security_monkey/security_monkey/static/assets/ico/favicon.ico" failed (2: No such file or directory), client: 256.256.256.256, server: , request: "GET /assets/ico/favicon.ico HTTP/1.1", host: "ec2-256-256-256-256.us-west-2.compute.amazonaws.com", referrer: "https://ec2-256-256-256-256.us-west-2.compute.amazonaws.com/login?next=https%3A%2F%2Fec2-256-256-256-256.us-west-2.compute.amazonaws.com%2F"`

It can confirm that on the login page, I do not see a favicon. After I login, I see the favicon on the other pages.

**Comment by monkeysecurity** [comment]
Fixed in #713.
