### ISSUE TITLE
Not authorized to perform `sts:AssumeRole`

### ISSUE THREAD

**Issue by JayeshP** [Netflix/security_monkey#732]
Hey,

I have provided aws admin's access key id and secret key, but still i am getting following error.

```2017-05-22 16:24:47,006 INFO: 'Problem Connecting to flowlog/CloudTrail Logs (ap-south-1)/eu-central-1:\nAn error occurred (AccessDenied) when calling the AssumeRole operation: Not authorized to perform sts:AssumeRole' [in /usr/local/lib/python2.7/dist-packages/security_monkey-0.9.1-py2.7.egg/security_monkey/exceptions.py:68]```

Please let me know what am i missing. (I am new to AWS IAM).

Note - I have done setup in Docker.

**Comment by monkeysecurity** [comment]
Couple odd things:
- Do you have an account called `CloudTrail Logs (ap-south-1)`?  (The region mismatch `ap-south-1 vs eu-central-1` in that statement is odd.)
- Typically you wouldn't run as admin.

If you have CloudTrail setup, it might be worth looking for any sts access denieds for the IAM User.  The requestParameters or response may contain more information.

It may be worth reviewing the IAM setup instructions:
https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md

Couple things I would check:
- Does your IAM User have an inline policy allowing `sts:AssumeRole`?  Does the resource section of that policy map.
- Does the SecurityMonkey IAM Role in the destination account have a trust policy (aka Assume Role Policy Document) that explicitly allows your IAM User?

**Comment by monkeysecurity** [comment]
Also, where on disk have you placed your access key and secret key?

Someone recently had this same problem and it was fixed by moving their credentials to `/etc/boto.cfg`.  They had previously been attempting to use `~/.aws/credentials`.

**Comment by JayeshP** [comment]
Hey, Thanks for the reply.  I have followed following things to get this resolved.

> Do you have an account called CloudTrail Logs (ap-south-1)? (The region mismatch ap-south-1 vs eu-central-1 in that statement is odd.)

I have disabled everything from accounts and just kept one for RDS (ap-southeast-1).

> Typically you wouldn't run as admin.

Agreed. 

Since I am doing setup on docker locally so creating AWS roles won't be useful. So i have created new user `security_monkey` on AWS IAM assigning `SecurityMonkeyLaunchPerms` and `SecurityMonkeyReadOnly` policies as mentioned on https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md#allow-securitymonkeyinstanceprofile-to-assumerole-to-securitymonkey

except [Allow SecurityMonkeyInstanceProfile to AssumeRole to SecurityMonkey](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md#allow-securitymonkeyinstanceprofile-to-assumerole-to-securitymonkey), as IAM user don't have such option, also I am not sure if this is required in case of IAM user.

After doing above steps, I am getting following error in security scheduler.

> 2017-05-23 11:04:17,376 INFO: 'Problem Connecting to cloudtrail/RDS (ap-southeast-1)/us-east-1:\nAn error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam::123456789012:user/security_monkey is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123456789012:role/SecurityMonkey' [in /usr/local/lib/python2.7/dist-packages/security_monkey-0.9.1-py2.7.egg/security_monkey/exceptions.py:68]


SecurityMonkeyLaunchPerms is as follow
```json{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ses:SendEmail"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::*:role/SecurityMonkey"
        }
    ]
}
```


Any help on this.

**Comment by mikegrima** [comment]
@JayeshP : You will need to alter the `SecurityMonkey` IAM role's Assume Role Policy Document.

See the directions here: https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md#allow-securitymonkeyinstanceprofile-to-assume-to-the-securitymonkey-role

You will essentially do the same, but instead of an ARN to an IAM role, you will supply the ARN of your IAM User (per your comment):
```
{
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<YOUR ACCOUNTID GOES HERE>:user/security_monkey"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

**Comment by mikegrima** [comment]
Please re-open this issue if you continue to experience problems.
