### ISSUE TITLE
Aging Issues - Issues still show in list after being resolved

### ISSUE THREAD

**Issue by playqdrew** [Netflix/security_monkey#739]
In my Aging Issues list I saw:

![image](https://user-images.githubusercontent.com/19480476/26905649-58f9cc8c-4b9d-11e7-93e1-d199a249e9c6.png)

I deleted the role and Security Monkey recognized this, as seen here:

![image](https://user-images.githubusercontent.com/19480476/26905687-91db1a60-4b9d-11e7-89b9-a2d6f1985ffa.png)

However, the issue still exists in the Aging Issues list.

How can I get this issue to be 'resolved'?

Thanks!

**Comment by monkeysecurity** [comment]
I'm now using #788 to track this issue. Closing this issue as a duplicate.
