### ISSUE TITLE
Investigate AWS Config async notification of changes to replace scheduled watchers.

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#74]
AWS Lambda was just announced today.

https://aws.amazon.com/blogs/aws/run-code-cloud/

"With Lambda, you simply create a Lambda function, give it permission to access specific AWS resources, and then connect the function to your AWS resources. Lambda will automatically run code in response to modifications to objects uploaded to Amazon Simple Storage Service (S3) buckets, messages arriving in Amazon Kinesis streams, or table updates in Amazon DynamoDB."

This may be better than the current polling infrastructure.

**Comment by monkeysecurity** [comment]
https://aws.amazon.com/about-aws/whats-new/2015/03/aws-config-sends-email-friendly-notifications-about-changes-to-your-aws-resources/

Looks like AWS Config now supports SNS notifications for changes.  This may be a better solution than Lambda.

The watchers would need to run on first install to get a baseline of your current environment.  All future change events would rely on AWS Config SNS notifications.  The python scheduler could be removed.  Security Monkey would then be capable of scaling up to a much larger number of accounts and technologies.

**Comment by mikegrima** [comment]
I will investigate using CloudTrail alerts to provide the alerting for changes: https://blogs.aws.amazon.com/security/post/TxASQFTVGZ5HMT/How-to-Receive-Alerts-When-Your-IAM-Configuration-Changes

**Comment by monkeysecurity** [comment]
We investigated AWS Config but think it's way too limited to be useful.  We are instead exploring a new architecture that is triggered by Event Rules.  Lots of internal work going on to explore this.  Closing ticket.
