### ISSUE TITLE
Error extracting issuer from certificate, maybe due to wildcard

### ISSUE THREAD

**Issue by kaelad02** [Netflix/security_monkey#741]
I'm getting the following error in my securitymonkey.log file.

`2017-06-15 21:12:45,923 ERROR: Unable to get issuer! list index out of range [in /usr/local/src/security_monkey/security_monkey/watchers/iam/iam_ssl.py:63]`

I looked at the line and it's the cert_get_issuer method to get the issuer. I looked in Security Monkey and found an issue "Could not extract valid certificate issuer" for one iamssl certificate. I copied the body into a file to look at the issuer. It appears to be a self-signed certificate with a wildcard. Both the subject "cn" and issuer "cn" are `*.elasticbeanstalk.com`.

Security Monkey doesn't seem to have a problem extracting the subject, only the issuer. I suspect that the wildcard is what's throwing it off.

**Comment by monkeysecurity** [comment]
Hey @kaelad02 ,

Looking at that method:
https://github.com/Netflix/security_monkey/blob/efac2d44d1095d43729934c0a7eca6158d626037/security_monkey/watchers/iam/iam_ssl.py#L49

And the place from where it is invoked:
https://github.com/Netflix/security_monkey/blob/efac2d44d1095d43729934c0a7eca6158d626037/security_monkey/watchers/iam/iam_ssl.py#L169

It doesn't seem like this should be a problem.  It logs the error, but should set the issuer as "ERROR_EXTRACTING_ISSUER" and continue operating.

**Comment by kaelad02** [comment]
You're right, it returns "ERROR_EXTRACTING_ISSUER" and continue operating. It's not stopping/killing the watcher.

Looking at the method again, cert_get_issuer is trying to extract the organization name from the issuer. In the case of this particular self-signed cert, the issuer only has the common name filled out. It doesn't have an organization name, which leads to the "index out of range" error.

Is that the point of cert_get_issuer? Is it supposed to get the organization name and if it doesn't exist, raise the "Could not extract valid certificate issuer" issue? If so, then could we at least change the log level from error to warning since it's an expected possible exception?

**Comment by monkeysecurity** [comment]
I'm okay with changing the log level.  Would you like to PR it over?
