### ISSUE TITLE
No Register option in the UI

### ISSUE THREAD

**Issue by rkdavuluri** [Netflix/security_monkey#750]
Hello, 

I was following the instructions for deploying security monkey on AWS. I have set it up and configured it to run. But when I access the UI page I don't see the option to register a new user. I've attached my screenshot. 

Also how can I get the "monkey" command to work. When I try the following steps I get an error. 

cd /usr/local/src/security_monkey/
monkey db upgrade

monkey: command not found

I am unable to use the "monkey add_account_aws" and create user options as well. 

I've installed Security monkey on AWS EC2 : UBUNTU 16.04.2 LTS (Xenial Xerus). 

Is there any additional details that I can provide?

Thanks

![image](https://user-images.githubusercontent.com/17715140/27756167-3d723516-5dc3-11e7-912d-3162586df14b.png)

# update

I am now able to create users using the "monkey create_user "you@youremail.com" "Admin"" option. I was also able to add the AWS account. But I am still unable to login to the UI using the created user. There are no errors in the /var/log/supervisor and /var/log/security_monkey either. 

I still have the same screen without the option to register. Any help?

**Comment by dorsegal** [comment]
please add this to your env
SECURITY_MONKEY_SECURITY_REGISTERABLE=true

if you are using docker add it to secmonkey.env file and recreate containers

**Comment by rkdavuluri** [comment]
Hello dorsegal, 

Thank you for the update. I am now able create user and login. But I am unable to get the UI to populate my data. I have setup my account but still there is no data. 

![image](https://user-images.githubusercontent.com/17715140/27775549-1f3e6704-5f71-11e7-933a-ebc4a052a4d8.png)

Any idea on how to get the data to show up?

**Comment by rkdavuluri** [comment]
Yes, I have the active checked. Here is the image. 

![image](https://user-images.githubusercontent.com/17715140/27795687-0e15136a-5fd5-11e7-9523-5a91addf48ed.png)

The identifier here is the 12 digit AWS account ID. Am I correct? 

![image](https://user-images.githubusercontent.com/17715140/27795746-3c47700c-5fd5-11e7-9ad9-9d1773969a12.png)
both security monkey and the scheduler are running. 

Yes. I created the "SecurityMonkeyInstanceProfile " and "SecurityMonkey" roles as per the documentation and added trust relationships. 

Is there anything else I could've missed?

**Comment by rkdavuluri** [comment]
I was able to fix the issue. I tried troubleshooting the IAM policies and at the end it worked out. 

Thank you very much for your help @dorsegal  :)
