### ISSUE TITLE
Documentation errors and improvements proposals

### ISSUE THREAD

**Issue by falcoris** [Netflix/security_monkey#758]
Hi

After struggling to make it work, I wanted to give a feedback on the documentation.

Here are all the problems and blurred instructions I have noted so far :
- In the RDS creation section, there is no mention of the required security policy between the EC2 instance and the RDS instance. I know that it is not related to security monkey but maybe it would be worth adding/mentioning it.
- There is not minimum spec indicated for the creation of the EC2 instance. I ended up figuring out that 1GB of RAM was not enough because I had an out of memory error during the installation. Since the "types" in the screenshot are obsolete, it could be relevant to replace it by a simple minimum RAM requirements
- There are some errors while installing the application ::
```
Installed /usr/local/src/security_monkey/venv/lib/python2.7/site-packages/SQLAlchemy-0.9.2-py2.7-linux-x86_64.egg
Searching for Jinja2>=2.8.1
Reading https://pypi.python.org/simple/Jinja2/
Downloading https://pypi.python.org/packages/90/61/f820ff0076a2599dd39406dcb858ecb239438c02ce706c8e91131ab9c7f1/Jinja2-2.9.6.tar.gz#md5=6411537324b4dba0956aaa8109f3c77b
Best match: Jinja2 2.9.6
Processing Jinja2-2.9.6.tar.gz
Writing /tmp/easy_install-ZmZ9Z8/Jinja2-2.9.6/setup.cfg
Running Jinja2-2.9.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ZmZ9Z8/Jinja2-2.9.6/egg-dist-tmp-4jgOmN
warning: no files found matching 'run-tests.py'
warning: no files found matching '*' under directory 'custom_fixers'
warning: no files found matching '*' under directory 'jinja2/testsuite/res'
warning: no previously-included files matching '*' found under directory 'docs/_build'
warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
  File "build/bdist.linux-x86_64/egg/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/jinja2/asyncsupport.py", line 22
    async def concat_async(async_gen):
            ^
SyntaxError: invalid syntax

creating /usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Jinja2-2.9.6-py2.7.egg
Extracting Jinja2-2.9.6-py2.7.egg to /usr/local/src/security_monkey/venv/lib/python2.7/site-packages
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Jinja2-2.9.6-py2.7.egg/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax

  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/Jinja2-2.9.6-py2.7.egg/jinja2/asyncsupport.py", line 22
    async def concat_async(async_gen):
            ^
SyntaxError: invalid syntax
```
- Still during the installation, the first set of commands leaves us in a (venv). There is no instruction as to what to do with that when the first block is done so I assumed it was still needed and it seems to be. But if the installation catches an error that needs to be fixed and the timeout occurs, you lose that venv and the only way that i found to proceed was to toss everything out and start again.
- The command monkey add_account_aws keeps asking for an --id argument even when I provide it. The information in the documentation is a bit vague as to what is that ID exactly, i figured that it is the 12 digits one but if it is, it doesn't work.
- There are problems with the provided **add_header Content-Security-Policy** configuration : 
`Content Security Policy: The page’s settings blocked the loading of a resource at self`
- Globally the userguide page seems to be out to date. For instance, the first instruction reads : 

> Here you will see a list of the accounts Security Monkey is monitoring. (It should be empty.)

But there are already dozens of items, no idea what they are or where they come from
The account creation (where is that account going to be created exactly, and what is its purpose ? I can't really understand)
Then the fields on the account creation screenshots are out to date as well.

Somehow all. that works after a 2nd installation but I have no idea how in detail.

**Comment by mikegrima** [comment]
Hello @falcoris !

With regards to RDS, I have recently ran through a from-scratch installation of security monkey, and agree that there could be additional instructions for the RDS page.  Namely, there needs to be the following:

1. Security group for Security Monkey: `securitymonkey`
1. Security group for the RDS instance: `securitymonkey-rds`

You will need to add an ingress rule on `securitymonkey-rds` to permit `securitymonkey` on TCP port `5432` to communicate with it. 

The RDS instance needs to be located within the same region, and either in the same VPC, or in a different VPC that is peered (including cross-account).

**Comment by mikegrima** [comment]
With regards to the installation errors you were seeing... Not sure what caused them. Do you recall the commands you ran?

For me, running all of these commands in this exact order (as shown on the quickstart guide) worked:
```
pip install --upgrade setuptools
pip install --upgrade pip
pip install --upgrade urllib3[secure]   # to prevent InsecurePlatformWarning
pip install google-compute-engine  # Only required on GCP
pip install cloudaux\[gcp\]
python setup.py develop
```

**Comment by mikegrima** [comment]
@falcoris Can you please clarify:
> But if the installation catches an error that needs to be fixed and the timeout occurs you lose that venv and the only way that i found to proceed was to toss everything out and start again.

Not sure what you mean by `timeout`. The `venv` should not timeout. Are you referring to your SSH connection to the instance timing out? 

You must remain in the `venv` as this provides the shell the proper paths to the Security Monkey Python environment. If you exit the `venv` you can simply get back in by navigating to the Security Monkey directory and running `source venv/bin/activate`.

**Comment by mikegrima** [comment]
> The command monkey add_account_aws keeps asking for an --id argument even when I provide it. The information in the documentation is a bit vague as to what is that ID exactly, i figured that it is the 12 digits one but if it is, it doesn't work.

The ID is the 12 digit AWS account ID.  What is the error that you are seeing?

> Globally the userguide page seems to be out to date. For instance, the first instruction reads :
Here you will see a list of the accounts Security Monkey is monitoring. (It should be empty.)
But there are already dozens of items, no idea what they are or where they come from
Yes, so these accounts you are seeing are AWS managed accounts that are used for specific services. These accounts would be given access to your resources if you utilize those resources. This prevents Security Monkey from raising issues that there is unknown cross-account access, as the access is from a "friendly", Amazon service related account. 

These accounts are added when you run the `monkey amazon_accounts` command.  Agree that the userguide should be updated to reflect this.

> The account creation (where is that account going to be created exactly, and what is its purpose ? I can't really understand)
Then the fields on the account creation screenshots are out to date as well.
The "account creation" adds the AWS (or GCP) account to Security Monkey's DB such that it can be monitored.

**Comment by mikegrima** [comment]
```
There are problems with the provided add_header Content-Security-Policy configuration :
Content Security Policy: The page’s settings blocked the loading of a resource at self
```
I'll let @monkeysecurity answer this one :)

**Comment by falcoris** [comment]
- RDS Security Group : Thank you for confirming, I did add the rule when I had the connection error. Since the whole guide describes each tasks, i reckon that these steps should be in it.
- Specs : Yes, I had seen that but the only free tier is 1G so I still tried 1G since there was no spec saying it wouldn’t work with less.
- Syntax error : I have this error while running python setup.py develop
- venv timeout : Yes, I was talking about the SSH, that complain shouldn’t be as it’s not security monkey related so I’ll withdraw it =) Thx for the tip though
- aws_id : The error i get is the following, ofc i'm using a real name and serie of 12 digits, just in case you wonder =) :
```
(venv)ubuntu@ip-172-31-35-86:/usr/local/src/security_monkey$ monkey add_account_aws -n myaccountname -id the12digitthingy
2017-07-14 00:21:55,664 INFO: Started thread pool with 25 core threads and 30 maximum threads [in build/bdist.linux-x86_64/egg/apscheduler/threadpool.py:52]
usage: monkey add_account_aws [-h] -n NAME [--thirdparty] [--active]
                              [--notes NOTES] --id IDENTIFIER
                              [--update-existing]
                              [--canonical_id CANONICAL_ID]
                              [--s3_name S3_NAME] [--role_name ROLE_NAME]
monkey add_account_aws: error: argument --id is required
```

Thank you for the quick feedback on my feedback @mikegrima !

**Comment by mikegrima** [comment]
For when you encountered the syntax error, did you run all of the other commands before? These commands must be run before `setup.py`:
```
pip install --upgrade setuptools
pip install --upgrade pip
pip install --upgrade urllib3[secure]   # to prevent InsecurePlatformWarning
pip install google-compute-engine  # Only required on GCP
pip install cloudaux\[gcp\]
```

**Comment by mikegrima** [comment]
The `id` is failing because you need to specify 2 dashes `--` before `id` so it says: `--id the12digitthingy` vs. `-id the12digitthingy`.

**Comment by falcoris** [comment]
- Syntax error : Yes, I did. Can reproduce the error at will here.
- id : I feel extremely ashamed and I have no excuse on that one. Brb whipping myself with a mouse cord.

**Comment by mikegrima** [comment]
#770 should address documentation flaws.
