### ISSUE TITLE
disabling auditor reports

### ISSUE THREAD

**Issue by utsav2307** [Netflix/security_monkey#761]
I am getting auditor reports daily, how can i disable the audit reports

**Comment by monkeysecurity** [comment]
Hey @utsav2307 - Under settings, uncheck "Daily Email" and hit save.

Also, you may want to remove your email address from this line of the config:

```python
# This address gets all change notifications (i.e. 'securityteam@example.com')
SECURITY_TEAM_EMAIL = []
```
