### ISSUE TITLE
can't get mail sent

### ISSUE THREAD

**Issue by falcoris** [Netflix/security_monkey#762]
Hi

I can't seem to get a mail sent for either a new critical item, or the daily one. 

The logs don't show anything helpful on that topic.

Would appreciate any possible help, 

Running the last develop version if that matters

Thanks in advance.

**Comment by Chris-Pr** [comment]
I just configured this, are you using SES? Has your SES domain been setup, authorized and working previously? 

have you configured MAIL_DEFAULT_SENDER = using an address with the same confirmed SES domain you have setup?

To test configure your email address in SECURITY_TEAM_EMAIL = , then go and create new IAM access codes, and run the "monkey find_changes -a "awsaccountname" . This will detect new access codes  and send an email. no logs seem to show ses sending difficulty.

**Comment by monkeysecurity** [comment]
I'd recommend not using SMTP:

```python
EMAILS_USE_SMTP = False
SES_REGION = 'us-east-1'
```

And then no need for these:
```python
MAIL_SERVER = 'smtp.example.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = 'username'
MAIL_PASSWORD = 'password'
```

**Comment by falcoris** [comment]
My domain has been approved a few hours ago on SES and I've tried to make it work but no way to get mails. Is there a way to activate some debug logs or something to figure that out ? Trigger a mail sending somehow ?

**Comment by monkeysecurity** [comment]
Hey @falcoris - I'd love a PR.  Sometimes people have SES trouble and so something like that would be very helpful.
