### ISSUE TITLE
Mail sending don't go to accounts which request them

### ISSUE THREAD

**Issue by falcoris** [Netflix/security_monkey#777]
It would seem that the only way to receive mails is to set the variable SECURITY_TEAM_EMAIL to an address.

I cannot get any emails sent to other accounts despite the fact that I can see the mail settings in the user section of the web interface

**Comment by monkeysecurity** [comment]
For the Daily, it should be combining `SECURITY_TEAM_EMAIL` with any users with `daily_audit_email` set to `True` for the specified account.

In settings, make sure the `Daily Email` box is checked and that the `Notify` column for the specified account is checked and press the `Save` button.

https://github.com/Netflix/security_monkey/blob/c5b3da1f7c1a339113c09565608d81b7fda8061e/security_monkey/auditor.py#L89
```python
        if type(self.team_emails) in (str, unicode):
            self.emails.append(self.team_emails)
        elif type(self.team_emails) in (list, tuple):
            self.emails.extend(self.team_emails)
        else:
            app.logger.info("Auditor: SECURITY_TEAM_EMAIL contains an invalid type")

        for account in self.accounts:
            users = User.query.filter(User.daily_audit_email==True).filter(User.accounts.any(name=account)).all()
            self.emails.extend([user.email for user in users])
```

Test with `monkey audit_changes -r`, optionally filtered by account and tech.
https://github.com/Netflix/security_monkey/blob/develop/security_monkey/manage.py#L83

`monkey audit_changes -m s3 -a myaccount`.

**Comment by falcoris** [comment]
I didn't notice the notify column, that was what was missing. It works fine. I'll upload the mail documentation that has just been merged to add that part
