### ISSUE TITLE
Enabling google SSO

### ISSUE THREAD

**Issue by utsav2307** [Netflix/security_monkey#780]
How can i enable google SSO? There is no proper documentation? I entered google client id and secret in config.py but nothing works. What exactly will be the value of GOOGLE_AUTH_ENDPOINT and GOOGLE_HOSTED_DOMAIN?
I also entered provider as:
ACTIVE_PROVIDERS = 'google'

**Comment by monkeysecurity** [comment]
You have ACTIVE_PROVIDERS as a string.  I believe it's looking for a list.

```python
ACTIVE_PROVIDERS  = ['google']
```

Looks like these are the required fields for google:

```python
GOOGLE_CLIENT_ID
GOOGLE_AUTH_ENDPOINT 
GOOGLE_SECRET
GOOGLE_HOSTED_DOMAIN  # optional. If provided, this is used to verify the token was issued for the given domain. (Recommended)
GOOGLE_DEFAULT_ROLE  # defaults to "View"
```

An example AUTH_ENDPOINT would be something like `'https://AUTH.mycompany.com/as/authorization.oauth2'`

^ I took that sample from our Netflix config, but we use a different SSO than Google, so yours might be different.  A quick google search brings up this:

`GOOGLE_AUTH_ENDPOINT = 'https://accounts.google.com/o/oauth2/auth'. `

Please let me know if this helps.

**Comment by utsav2307** [comment]
Apparantely the issue was, changes had to be made in config-docker.py instead of config.py
