### ISSUE TITLE
Unable to pull data from GCP project

### ISSUE THREAD

**Issue by cplvic** [Netflix/security_monkey#781]
HI SM team,

I don't seem to be pulling data form my GCP project. AWS works fine.
I matched the name and the project ID, created and placed the credentials file in a readable spot and restarted the scheduler. The Accounts page has the correct entry/

Does the credentials file need to be in a specific folder/directory? It currently has 660 and is owned by ubuntu:www-data. I am using the json format.

What is the best way to debug this? 

My Setup -
SecurityMonkey Front end in AWS
SecurityMonkey Postgresql in AWS on separate back end

**Comment by cplvic** [comment]
cplvic gathering valuables to burn as an offering to the gods for wisdom

**Comment by carise** [comment]
Do you have any errors in any of the /var/log/securitymonkey/*.log files?

I think I had some issues with my SM installation when I last tried it, but this was back in March. (I also installed SM on GCP, not on AWS.) I ended up assigning the "Storage Object Viewer" IAM role to the service account before I could see the GCP buckets. Unfortunately, this was awhile ago, so I don't know if doing that will address your issue.

**Comment by cplvic** [comment]
HI @carise I don't actually see anything in the logs. Its very strange. I just got SSO working so I was concentrating on that last night. Now onto this GCP thing.

**Comment by carise** [comment]
I don't know if this is the case for you, but I had to change the permissions on /var/log/securitymonkey/*.log, you might need to chown them to www-data.

Also, I have in my notes that /usr/local/src/* had to have the owner as www-data... I don't know why though, so maybe don't do that yet, just the logs.

**Comment by cplvic** [comment]
the logs are working. I don't see anything (data) related to my GCP account after I added the account. I did make it active as well.  AWS is working just fine.

**Comment by carise** [comment]
What roles does your GCP service account have?

**Comment by cplvic** [comment]
Viewer and Security Viewer

**Comment by carise** [comment]
Ok. So I just ran through a fresh install of Security Monkey and added my GCP account through the UI.

My project id is not the project number.
Credentials are stored in home directory (probably could be a better place, but for now, just for testing purposes)
and checked the "Active" box. Then I restarted.

Is this similar to what you have?

**Comment by cplvic** [comment]
I matched the Name and Project ID. 
I made a dumb assumption but the Project ID is a string based on what is in the json file correct?
so if it is
"project_id": "mycompany-dev"
then I would input mycompany-dev in the Project ID field in the UI?

Thanks for your help @carise

**Comment by carise** [comment]
Yes, that is the correct project id. The name can be anything. My credential file permissions are 640 to ubuntu:www-data as well.

Hmm, I don't know :( That's really bizarre that you're not able to pull data still. I don't think I see any activity regarding GCP in the logs either...

**Comment by cplvic** [comment]
Hi @carise - I am running on AWS,
I installed gcloud sdk. Did you install that under the ubuntu profile or install it it at all?

**Comment by carise** [comment]
I haven't used the gcloud sdk on the ec2 instance where I installed SM. I don't think that should affect whether SM can auth your json key though.

The only thing I can think of that is affecting how SM can (or cannot) connect to GCP is through the service account configuration and perhaps the IAM API not being enabled. Assuming you followed [this guide](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_gcp.md), were you able also to enable the IAM API? (`gcloud service-management enable iam.googleapis.com` or via the IAM API page)

**Comment by cplvic** [comment]
yes. The admin confirmed the api is enabled as well.
I am going to setup a new staging instance  to see if I messed up on some install part

**Comment by carise** [comment]
Ok. I would recommend also seeing if creating a separate service account under your project, exporting that key, and creating a new SM GCP monitor with this new key, would happen to work.

**Comment by mikegrima** [comment]
@carise : Thank you so much for your assistance! :)

@cplvic : Have you been able to get this to work?

**Comment by cplvic** [comment]
I will have a new setup for this on Thursday or Friday. <jingle> after these messages, we'll be right back </jingle>
