### ISSUE TITLE
Add "active" flag to ItemIssues table

### ISSUE THREAD

**Issue by jseiser** [Netflix/security_monkey#788]
(Issue edited by project maintainer to turn it into a project goal)

As a result of PR #564, Security Monkey exhibits some interesting behavior regarding issues.  When an issue is fixed, Security Monkey no longer deletes the issue.  The idea is to preserve justifications after items are deleted and then re-created.  However, this has caused problems.

The solution should be to add a flag to issues (type: bool, name: active).  Fixed issues would have the active flag set to False while unifxed issues would have their flag set to True.  SM should never delete issues, but will only change the active flag.  As SM won't be deleting issues, the justifications will not get deleted.   The UI would need to be changed to only show active issues.

Original report by @jseiser follows:

I am getting email changes, and the current configurations appear to be updating fine in the webUI as well.  The changes are not clearing out or getting updated under "Issues'

Example in the attached image.  A VPN shows down, but you can see in the config that it is up.

![github](https://user-images.githubusercontent.com/4855527/29284434-bcf7f8fe-80f8-11e7-82d6-c361ca132e61.png)

I went through the quickstart today, so this is running the latest code that would get pulled from those commands.

**Comment by monkeysecurity** [comment]
Related tickets:

#802 
#795 
#739
