### ISSUE TITLE
Cloudtrail Issues Remain After Deleting Trail

### ISSUE THREAD

**Issue by kur3us** [Netflix/security_monkey#795]
I deleted a Cloudtrail that had a couple issues.

Then I ran:  

monkey find_changes -a 'AccountName' -m cloudtrail
and
monkey audit_changes -a 'AccountName' -m cloudtrail

The trail shows as deleted in the revisions, but the issues still appear.

![cloudtrail-sm-bug](https://user-images.githubusercontent.com/15004905/29543097-9b9697ce-8693-11e7-858f-eac6a5dcc70d.JPG)

**Comment by monkeysecurity** [comment]
Same as #802.

This is intended behavior to ensure that we don't lose justifications when an item is deleted and then re-created.

It seems to confuse lots of people though.

**Comment by kur3us** [comment]
Is it possible to keep the justifications but not show the issues as current issues? When we're looking for issues, these keep popping up and lead us to believe something is wrong when it isn't.

**Comment by monkeysecurity** [comment]
Yes, well, we need a PR to add the functionality, so it's not available yet.  Ideally we would add a flag to issues to mark them as active or inactive and we would never delete issues.  This would 1) preserve issues and 2) make the UI not confusing ( or incorrect.)

I would think it would be a simple PR, but I have some other PR's I'm working on.

I'll elevate this issue/PR to beer-basket worthy if someone is looking to help out on it.

**Comment by monkeysecurity** [comment]
I'm now using #788 to track this issue. Closing this issue as a duplicate.
