### ISSUE TITLE
Report Tab Does not Scroll on Safari or Chrome on Mac IOS

### ISSUE THREAD

**Issue by ekelson-bcove** [Netflix/security_monkey#800]
Report tab is longer than page and does not scroll.  Thus, the reports after first KMS entry are inaccessible.  To clarify, if you zoom your browser view out (smaller) you can see everything, however a better user experience would be to permit scrolling in the dropdown

![image](https://user-images.githubusercontent.com/20729707/29633197-7994f91e-8813-11e7-9e51-d0b231ac5fed.png)

**Comment by monkeysecurity** [comment]
This was refactored in #757. Original issue was #539.

This is already fixed.

**Comment by ekelson-bcove** [comment]
Thank!
