### ISSUE TITLE
Security Group deleted but alert showing up in an odd state in Security Monkey UI

### ISSUE THREAD

**Issue by markofu** [Netflix/security_monkey#802]
Hey @monkeysecurity @mikegrima,

We have this odd issue where a `security group` has been deleted but Security Monkey wasn't detecting it (due to the _open files_ issue) but after a restart and a manual slurp. It seems to have detected but the alert is still in the _Audit Issues_ UI and when you drill into, it says the `security group` is deleted but still thinks the issue is valid, which is pretty much presenting invalid data to our developers.

Any thoughts?

Thanks as always!

Mark

<img width="1383" alt="screen shot 2017-08-23 at 9 48 25 pm" src="https://user-images.githubusercontent.com/1702065/29650794-f688ae8c-8851-11e7-9f50-2d5c83222f40.png">

**Comment by Xeteskian** [comment]
I think this is intended but i could be wrong.  Basically, from an audit perspective, even though the group's been deleted, you still need to justify that there may have been a risk.
When this occurs to me, I tend to justify all issues with 'Remediated.  Item has been deleted'

That being said, if the item then gets re-created, the justification seems to remain in place...  Which I'm not too sure should happen

**Comment by markofu** [comment]
Yeah, maybe but I'm not sure because I don't think this is desirable behaviour at all. As Product Owner or Developer trying to assess the security posture of their account, visually they're going to be concerned with everything in red and, therefore, this is a false-positive because it's not actual risk or vulnerability. I really think the alert should disappear because it's no longer valid.

**Comment by Xeteskian** [comment]
I know what you mean, to deal with this on my config, I just set up a search filter that only shows active items with issues.  The URL contains the filter, so you can bookmark it for quick and easy daily checking

**Comment by Xeteskian** [comment]
But, that being said, if this is not the intended behaviour, then you're right, it may need to be filed as a bug

**Comment by markofu** [comment]
I chatted offline with @mikegrima and he feels it's a bug. I am not keen to modify filters or justify things in the UI because that feels like a temporary solution hiding an issue.

**Comment by monkeysecurity** [comment]
It's intended behavior, but behavior that we intend to modify.

The idea was to preserve justifications when items get deleted and come back.

**Comment by monkeysecurity** [comment]
I'm now using #788 to track this issue. Closing this issue as a duplicate.
