### ISSUE TITLE
Flag for Security Group usage

### ISSUE THREAD

**Issue by JaguarSecurity** [Netflix/security_monkey#81]
Could I request an enhancement to indicate if a Security Group is being utilized and to show what instance (by Instance ID) the security group is protecting.

**Comment by lucab** [comment]
@monkeysecurity do you really go down the paginating route? I was having a look at the [describe-instances comand](http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-DescribeInstances.html), and it seems you can filter by:
 * group-id/group-name (EC2 classic)
 * instance.group-id/instance.group-name

That will surely means that soon every watcher will end up querying on its own for instances, while maybe we should slurp that information once in the DB (same for tags, see `eip.py`). However, as a stop gap solution, querying with filters may be better than fighting with pagination IMHO.

**Comment by lucab** [comment]
A couple of notes:
 * I checked boto source and `get_only_instances()` seems to handle the pagination/markers/token internally
 * I still went the other way and did this with multiple filtered call. You can see it at the branch under lucab/security_monkey@df251800c732d0a5c0f5a9c7e76707aba1b15933

Please let me know your call on this, I can still revert to a single call with a sane `max_results` before sending a PR. Also, is it ok if I silence with score 0 all issues in non-assigned security groups?

**Comment by monkeysecurity** [comment]
Awesome.

Have you determined whether boto's pagination is more performant than using multiple filtered calls?

Regarding the silencing of empty security groups; I'm conflicted on this. Instead of silencing empty security groups, I'd like to add an issue identifying them as empty security groups.  Maybe it also makes sense to clear the score on the other issues, but I'd have to play with it.

Feel free to issue the PR however you'd like it to work.  I can't wait to see how this performs with our environment.

**Comment by lucab** [comment]
> Have you determined whether boto's pagination is more performant than using multiple filtered calls?

No, but I just did. My worst case account for this test had ~60 sgs, of which ~35 active, mostly in ap-southeast with my polling securitymonkey in Europe, and ~100 active instances. Results:
 * Single call with `max_result`=25: 0m24.801s
 * Multiple calls with group filter: 0m57.035s

Network latency is probably killing me here. On better testcases (smaller and Europe based) the difference is in couple of seconds, but always in favor of pagination. I'll go for that, and we can also further tweak the `max_result` down the road.

> Instead of silencing empty security groups, I'd like to add an issue identifying them as empty security groups. Maybe it also makes sense to clear the score on the other issues, but I'd have to play with it.

This was for filtering the noise of unused sg. Unfortunately I have so many on accounts I can't directly clean, it would be helpful to visually highlight only the active ones. Issues are still visible in webUI and mail reports if 0-scored.

**Comment by Blackbaud-FrankKurzawa** [comment]
I'm wondering if the more useful flag may be whether a particular security group is used by an instance with a public IP. For example, a 0.0.0.0/0 SG is definitely a 10 if it's facing a public IP, but maybe only a 5 if only instances with private IP's are attachted to that SG.

**Comment by monkeysecurity** [comment]
@Blackbaud-FrankKurzawa Good point.  In EC2-Classic I believe everything has a private and public IP.  That's definitely not the case in VPC.  Sounds like a great feature to add.

I just opened #143 to track this idea.

**Comment by monkeysecurity** [comment]
Closing as much of this has been merged with #103.
