### ISSUE TITLE
Removing "Unknown Cross Account Access"

### ISSUE THREAD

**Issue by 0xdabbad00** [Netflix/security_monkey#821]
For S3 buckets, I have a number of issues for "Unknown Cross Account Access" because Security Monkey doesn't seem to acknowledge the canonical IDs.  I've added the Canonical IDs manually and tried running `monkey fetch_aws_canonical_ids` and then run `monkey audit_changes -m s3`, but this doesn't remove the issues.  Is there a way to remove these issues once they've been created do I need to justify them manually?

**Comment by monkeysecurity** [comment]
Hey  @0xdabbad00 

Let me try and fix this.  I started debugging yesterday (though the problem has been around for a while.)

**Comment by monkeysecurity** [comment]
Could you pull the latest from develop and see if this issue is fixed for you?

**Comment by 0xdabbad00** [comment]
I'm on 0.9.2.  Is there any special steps for the upgrade path?  Do I just `git pull` and `supervisorctl restart all`?

**Comment by mikegrima** [comment]
@0xdabbad00 You should be able to do a git pull from the `develop` branch.

**Comment by monkeysecurity** [comment]
https://github.com/Netflix/security_monkey/blob/develop/docs/update.md

**Comment by monkeysecurity** [comment]
There are a number of steps to upgrade and they are detailed at the link I provided above.

Summarized:
- Backup config.
- Stop services
- Git pull
- Install new requirements (`python setup.py develop`)
- compile new web UI and put it in the static folder
- restore your config file
- perform DB migration ( `monkey db upgrade` )
- restart services

**Comment by monkeysecurity** [comment]
Presuming this has been fixed.  Closing ticket.
