### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by 0xdabbad00** [Netflix/security_monkey#826]
The instance I'm running Security Monkey becomes unresponsive every few days.  Looking in `/var/log/messages` I saw `oom-killer` messages every ~8 hours.  Running `sar` reports I was able to record regular system memory usage, and saw a classic memory leak chart.  It looks like every ~2 hours the memory usage jumps up.  Ultimately this get's to near 100% and the `oom-killer` steps in and kills `monkey`.  I suspect that sometimes so much memory is being used that not even `oom-killer` can run, which is why the system is unresponsive (that's my assumption).  

I further assume that perhaps the `monkey` process is getting so large because it is running every hour, and maybe one `watcher` is not finished by the time the next starts.  I have bumped up the interval of the `watcher`, but I'm unsure yet if this will resolve the issue and wondering if others have experienced this.  If this is the issue, it would be good to include some logic in Security Monkey to not starts new scans of an AWS account until the previous scan has finished.

**Comment by jleaniz** [comment]
@0xdabbad00 I experienced a similar issue. I bumped up my instance to a t2.medium and added some swap space. That seems to have mitigated the OOM problem and the systen hasn't locked up ever since.

**Comment by mikegrima** [comment]
@0xdabbad00 Not sure which instance type you are using, but in our quickstart guide for AWS, we do mention launching instances with at least 1.7GB RAM [here](https://github.com/Netflix/security_monkey/blob/develop/docs/instance_launch_aws.md).

**Comment by 0xdabbad00** [comment]
I'm running Security Monkey by itself on a t2.large (8GB of RAM) with the database running on an RDS.  Due to the memory usage suddenly increasing by a large amount every 2 hours and never dropping until oomkiller comes in, this appears to be a memory leak.  I'm wondering how I can go about debugging what is causing these memory issues.

**Comment by mikegrima** [comment]
Wow, that is odd.... 

I guess the main questions are: which watchers are you running, and how big is the AWS account in question (number of roles, security groups, etc.)?

**Comment by 0xdabbad00** [comment]
I'm not sure what you mean by which watchers.  It is only monitoring AWS (a few environments, one main one that I'd say is "medium" sized). I'm running the 0.9.2 release, installed two weeks ago.  I increased the schedule interval to 4 hours, with no improvement.  I turned on "debug" logging, but nothing relevant.  oom-killer is still whacking the `monkey` scheduler process periodically.

I don't know how to debug this.  Is there a way to say "don't slurp updates anymore" and "don't check anything anymore"?  And then start doing "only get updates on EC2" and then "only get updates on EC2 and S3", etc.  Maybe then I could start narrowing down where the memory leak is?  

I also don't know how to upgrade to any newer code. I had installed by starting with `git clone --depth 1 --branch v0.9.2 https://github.com/Netflix/security_monkey.git`

**Comment by 0xdabbad00** [comment]
I've tried using python's `memory_profiler` library with no luck on getting it to output anything, so any help there would also be appreciated.

**Comment by mstair** [comment]
> Is there a way to say "don't slurp updates anymore" 
In the UI, go to Settings->Watcher Configuration (where you probably set the interval to 4 hours) and you can enable/disable individual watchers.
v0.9.2 is latest stable release, newest functionality is on the develop branch.

**Comment by 0xdabbad00** [comment]
I added a `return` to the top of the `run_change_reporter` function in `security_monkey/scheduler.py` and this appears to have stopped the memory leak from exhibiting itself, so that at least narrows down where it is.  I'll continue commenting out code. :( I don't know of a better way of debugging this.

**Comment by mikegrima** [comment]
I also don't know of a better way to debug ;)

Here is what I think should be done:

1. Set the log level to DEBUG (modify ALL lines in your config file: https://github.com/Netflix/security_monkey/blob/develop/env-config/config.py#L17-L54) 
1. Disable the scheduler completely so NO watchers are running: 
    ```
    sudo supervisorctl
    stop securitymonkeyscheduler
    ```
1. Then, you will need to run the `monkey find_changes -m <TECHNOLOGY_HERE>` command. Do this one command at a time and keep note of which ones fail and which don't. If it does fail, keep note of where it's failing since the debug logs are very verbose. To get started, try these technologies first:
    - s3
    - securitygroup
    - iamrole
    - route53
    - vpc

Once you have that information, then we can do additional work to find the source of the issue. 

You are the first user I'm aware of that has encountered this issue, so debugging will be a bit more involved.

**Comment by 0xdabbad00** [comment]
So I had not updated Security Monkey, and didn't have time to get more involved with investigating this.  I did however disable everything related to one service that we are using very heavily (more heavily than anyone else is likely to encounter) and I am no longer seeing `oom` reapings.  I am closing this issue.

**Comment by karlgrz** [comment]
We experience this issue about every other day. We run security-monkey-scheduler on a c3.xlarge, colocated with some other services running as docker containers. 

We analyze a lot of AWS accounts (about 20), that get fairly high usage across them all. 

I'd be happy to help diagnose this, because it is most definitely affecting others. Just let me know what I can provide to be helpful.

**Comment by mikegrima** [comment]
@karlgrz : If you are having difficulty with one instance, you can have multiple instances/containers where they are dedicated to specific accounts and technologies.

We're actively working on event-driven models vs. polling, but it will be some time before that is complete.

**Comment by karlgrz** [comment]
@mikegrima good point, but that's annoying, too, heh.

I'll keep an eye on the event-driven models development.

**Comment by zpritcha** [comment]
We're seeing these same memory issues with ~60-70 accounts on a m4.xlarge instance. I'll run through the steps @mikegrima outlined above to see if we can track down what's eating all the memory -- some days it'll hit the 16GB limit in less than 24 hours, which in one case led to the DHCP client not having enough memory to renew leases.
