### ISSUE TITLE
res

### ISSUE THREAD

**Issue by mark-asapp** [Netflix/security_monkey#829]
Not sure this is an issue, but I am not able to get SM to scan AWS. I could just be doing something wrong. 
![image](https://user-images.githubusercontent.com/29580611/30654633-79d7ba3e-9dfc-11e7-8457-5db865dac84d.png)

If it matters at all I'm on 16.04:
```
ubuntu@ip-172-31-31-109:/var/log/security_monkey$ uname -a
Linux ip-172-31-31-109 4.4.0-1035-aws #44-Ubuntu SMP Tue Sep 12 17:27:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I'm using SM master

Only thing I see in the error log is 
```
ubuntu@ip-172-31-31-109:/var/log/security_monkey$ cat security_monkey.error.log
2017/09/19 18:58:35 [error] 1838#1838: *2 open() "/usr/local/src/security_monkey/security_monkey/static/ico/favicon.ico" failed (2: No such file or directory), client: {SOME IP} , server: , request: "GET /static/ico/favicon.ico HTTP/1.1", host: "ec2-{SOME IP}.compute-1.amazonaws.com", referrer: "https://ec2-{SOME IP}.compute-1.amazonaws.com/login?next=https%3A%2F%2Fec2-{SOME IP}.compute-1.amazonaws.com%2F"
```

**Comment by 0xdabbad00** [comment]
Check CloudTrail logs of the account to ensure SecurityMonkey is actually trying to scan it and not getting access denieds or not trying at all.  You'll want to look in the logs of the scheduler. Check your `supervisor` config to see where it's writing those logs (`/etc/supervisor/conf.d/securitymonkey.conf`).

**Comment by mikegrima** [comment]
Duplicate of #828
