### ISSUE TITLE
Where to set interval?

### ISSUE THREAD

**Issue by 0xdabbad00** [Netflix/security_monkey#830]
I want to only scan my accounts once every 2 hours at most.  This does not appear to be happening.  I set the `interval` in the `Watcher` class in `security_monkey/watcher.py` as described here: https://github.com/Netflix/security_monkey/blob/4a0850f45e4208e3f130dc59743105aab102841d/docs/misc.md

I set `import pdb; pdb.set_trace()` at https://github.com/Netflix/security_monkey/blob/99d231ace5c6150dc6244bf49557c7bd5da29f46/security_monkey/scheduler.py#L32

and when that hits and I run `p locals()` in `pdb` I see:
```
{'account': u'Prod', 'interval': 60, 'account_names': ...
```

Where is this interval being set, and how do I set it to 2 hours?

**Comment by mikegrima** [comment]
Intervals can be set in the UI under Settings > Watcher Configuration.

**Comment by 0xdabbad00** [comment]
That sets it on a per technology basis though, not a per account basis correct?

**Comment by mikegrima** [comment]
Correct.

**Comment by mikegrima** [comment]
If you would like a finer-grained level of control for this, you would need to have an external instance or docker container that runs the `find_changes` command for that given technology on its own schedule.
