### ISSUE TITLE
Unable to Send Email

### ISSUE THREAD

**Issue by ishangirdhar** [Netflix/security_monkey#831]
Hello Everyone,

I have configured Security Monkey a long time back and everything has been working just fine, I was initially receiving Emails but now I am getting the following error message in the logs:

/var/log/security_monkey/securitymonkey.log :

```
2017-09-21 11:41:45,205 WARNING: Failed to send failure message with subject: Password reset instructions
<type 'exceptions.Exception'> 'NoneType' object has no attribute 'send_email' [in /usr/local/src/security_monkey/venv/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/common/utils.py:100]
2017-09-21 11:41:45,205 WARNING: Traceback (most recent call last):
  File "/usr/local/src/security_monkey/venv/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/common/utils.py", line 96, in send_email
    ses.send_email(app.config.get('MAIL_DEFAULT_SENDER'), subject, html, email, format="html")
AttributeError: 'NoneType' object has no attribute 'send_email'
 [in /usr/local/src/security_monkey/venv/lib/python2.7/site-packages/security_monkey-0.9.3-py2.7.egg/security_monkey/common/utils.py:101]
```

Config.py:

```
# These are only required if using SMTP instead of SES
EMAILS_USE_SMTP = False     # Otherwise, Use SES
SES_REGION = 'eu-east-1'
MAIL_SERVER = 'email-smtp.eu-west-1.amazonaws.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = '<username>'
MAIL_PASSWORD = '<password>'
```
I have configured, Amazon SES credentials, SES creds are configured right, and I am able to send email using those credentials in another standalone python script to verify if SES creds and config are correct.

I have updated securitymonkey to latest version, all required flask packages are installed. Can't figure out what's wrong.

Any help would be appreciated!

-Ishan

**Comment by 0xdabbad00** [comment]
If you're using SES you don't need to set any of those values other than `SES_REGION` and `MAIL_DEFAULT_SENDER`.  Try checking your IAM Role policy for `ses` privileges.

**Comment by monkeysecurity** [comment]
Looking at the code, I don't understand how it would get to that line with `ses` variable being `None`.

https://github.com/Netflix/security_monkey/blob/develop/security_monkey/common/utils.py#L96

The `ses` variable is defined just a few lines above in a `try/except`.

If you're familiar with `pdb`, this may be a great time to step through the function and see what's going on.

`from pdb import set_trace; set_trace()`
