### ISSUE TITLE
Error loading resource from API

### ISSUE THREAD

**Issue by moonspell79** [Netflix/security_monkey#841]
Hi, 

I have set up an AWS EC2 instance with Security Monkey. Once I enter AWS account details, I am getting an error:

"Error loading resource from API. Error: <HTTP 500: {"status": 500, "message": "Internal Server Error"}> "
Both processes under supervisor are running:
```
supervisor> status
securitymonkey                   RUNNING   pid 13055, uptime 10:31:41
securitymonkeyscheduler          RUNNING   pid 17167, uptime 0:00:03
```
What might be an issue?

Thanks:
Michal

**Comment by monkeysecurity** [comment]
Hey @moonspell79  - The logs should provide more information on the 500 error.  Maybe you could take a look at those?

**Comment by moonspell79** [comment]
I found a problem. If you have AWSCLI configured on the server, then it is not using assigned IAM Role to EC2 and makesd this error.
