### ISSUE TITLE
Docker docs lack instructions to bring up interactive shell

### ISSUE THREAD

**Issue by injcristianrojas** [Netflix/security_monkey#842]
When reading the Docker setup wiki page (https://github.com/Netflix/security_monkey/blob/develop/docs/docker.md), I don't understand how can I access the `monkey` command. Is there a previous command to open a shell in some machine in which I can use that command?

**Comment by monkeysecurity** [comment]
There's definitely a way to bring up a shell in a docker container.  However, my docker-foo is rusty.  Hopefully someone more familiar can assist.

**Comment by arush0** [comment]
Further down there's a [more info](https://github.com/Netflix/security_monkey/blob/develop/docs/docker.md#more-info) section that describes how to accomplish this.
