### ISSUE TITLE
Feature request: Only report unjustified issues

### ISSUE THREAD

**Issue by 0xdabbad00** [Netflix/security_monkey#844]
I tried turning on emails reports, but these emails are filled with issues that have already been justified, which makes these reports far too noisy. I only want to be informed of unjustified issues so I can more easily identify and respond to new, unresolved issues.

This can be accomplished by simply changing the code here:
https://github.com/Netflix/security_monkey/blob/e261f7ce344a194616a42086957426e871f5871c/security_monkey/auditor.py#L721

This would be changed to:
```
for issue in item.db_item.issues:
    if not issue.justified:    # Added to avoid reporting previously justified issues
        item.totalscore = item.totalscore + issue.score
```

**Comment by monkeysecurity** [comment]
Good idea. Should add another if-statement as well:

`if not issue.justified and not issue.fixed:`

**Comment by monkeysecurity** [comment]
Hey @0xdabbad00  - Are you able to PR the fix for this or would you like me to take care of it?

**Comment by 0xdabbad00** [comment]
@monkeysecurity Probably easiest for you to PR it.  I've also noticed that I receive reports for issues for audit checks that I've disabled and will try to find how that is happening as well.  For example, the report emails include "Cert has expired" messages, but under Settings -> "Auditor Settings" I've disabled that check.

**Comment by 0xdabbad00** [comment]
That should work.  Thank you!
