### ISSUE TITLE
Bug: Emailed reports contain disabled audits

### ISSUE THREAD

**Issue by 0xdabbad00** [Netflix/security_monkey#846]
If you disable an issue type by going to Settings -> "Auditor Settings" and disabling the issue there.  You will still receive email reports containing these issues.  The reason is that only "override scores" are taken into consideration when determining whether a rule should be used or not, as shown in https://github.com/Netflix/security_monkey/blob/e261f7ce344a194616a42086957426e871f5871c/security_monkey/auditor.py#L559

In order to fully disable a rule then, you need to disable it additionally under Settings -> "Audit Issue Scores".

This is unexpected.  I've not yet figured out how to resolve this in the code, but my desired outcome is that when I've disabled a check under "Auditor Settings" that it is taken into account here when reports are generated.

**Comment by monkeysecurity** [comment]
Long term I want to deprecate AuditorSettings.

Short term, we could add another statement to PR #845 that will pull the issue.auditor_setting to determine if it is enabled.

Let me update that PR.

**Comment by monkeysecurity** [comment]
PR #845 merged.  I believe this issue is fixed. Closing issue.
