### ISSUE TITLE
Dependency issues with setup.py develop

### ISSUE THREAD

**Issue by challanuk202** [Netflix/security_monkey#847]
still getting an issue :-
File "/usr/local/src/security_monkey/venv/local/lib/python2.7/site-packages/pkg_resources/init.py", line 867, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'idna==2.5' distribution was not found and is required by security-monkey

**Comment by mikegrima** [comment]
Hello @challanuk202 .  What happens if you run `pip install idna==2.5` ?

**Comment by challanuk202** [comment]
still, it's not taking idna==2.5, I resolve it! the way re-install everything from the bottom. but still have an issue with Nginx webserver.

**Comment by mikegrima** [comment]
What issue are you having with nginx?
