### ISSUE TITLE
Settings Menu not visible in login dashboard

### ISSUE THREAD

**Issue by manikantakrishna** [Netflix/security_monkey#850]
I did security monkey setup and added users by command prompt. we are able to login the security monkey but i need to create users by Web UI.
In login dashboard of security monkey settings Menu is not visible, I checked configuration "SECURITY_REGISTERABLE = False" it is in false only.
![image](https://user-images.githubusercontent.com/33054743/31935190-cf09d85e-b8cb-11e7-9fe4-0f73ae439bd6.png)

**Comment by manikantakrishna** [comment]
I fix this issue, I changed to "Ture" and restart security monkey.
I'm able to register now.

**Comment by swethareddygalwa** [comment]
Hey even i faced the same issue thanks alot @manikantakrishna
