### ISSUE TITLE
getting login page not able to see register tab

### ISSUE THREAD

**Issue by challanuk202** [Netflix/security_monkey#851]
after crossed all signal successfully, but facing the issue in WebUI login page, not finding register page in Web UI.

**Comment by monkeysecurity** [comment]
To register in the UI, you'll need to set `SECURITY_REGISTERABLE = True` in your config.

We've set the default to False.
```
MAIL_DEFAULT_SENDER = 'securitymonkey@blah.com'
SECURITY_REGISTERABLE = True
SECURITY_CONFIRMABLE = True
SECURITY_RECOVERABLE = True
SECURITY_PASSWORD_HASH = 'bcrypt'
SECURITY_PASSWORD_SALT = 'xxxx'
SECURITY_TRACKABLE = True
```
