### ISSUE TITLE
OpenStackWatcher needs to set account_type

### ISSUE THREAD

**Issue by mstair** [Netflix/security_monkey#860]
OpenStackWatcher is a CloudAuxWatcher, but does not set the account_type to OpenStack. AWS instances are trying to run  OpenStackWatcher and throwing exceptions.

**Comment by monkeysecurity** [comment]
Hey Michael.

Want to send a quick PR or do you want me to update it?

**Comment by mstair** [comment]
Working on it now

**Comment by mstair** [comment]
Fixed the account_type also removed the OpenStackSecurityGroupAuditor as its import of from security_monkey.auditors.security_group import SecurityGroupAuditor was causing issues. I know I have run into this before, just not sure how to resolve.

**Comment by ekelson-bcove** [comment]
Additionally, you have to add the python-openstacksdk module manually, the develop setup routine does not add this

**Comment by mstair** [comment]
Ah yes, `pip install cloudaux\[openstack\]` is required (like \[gcp\]), will update the docs

**Comment by mstair** [comment]
PR addresses the 3 issues running against AWS (add account_type to the abstract OpenStackWatcher base class, removes the OpenStackSecurityGroupAuditor due to module load issues, and update docs for cloudaux[openstack] is required for the global watcher load). Apologies, I should have setup an AWS instance to verify prior to the original PR.

**Comment by monkeysecurity** [comment]
`pip install cloudaux\[openstack\]` is required, even if not monitoring openstack?

**Comment by mstair** [comment]
Appears, yes. In manage.py `find_modules('watchers')` loads every single watcher in the tree, which, for OpenStack, then imports from cloudaux, which is looking for the SDK. Same issue for GCP, but when you run `pip install cloudaux\[gcp\]` it installs the GCP dependencies, so the find_modules works on AWS. Am I reading that wrong?

**Comment by monkeysecurity** [comment]
I think  you're right.  I wonder what we could change so that you would only need to install gcp/openstack dependencies if you're actually using those.  I'm going to think on that.

**Comment by mstair** [comment]
Not sure of a great way. You could wrap the imp load in find_modules for ImportErrors, but could mask something else. You don't know the possible account type, unless you query maybe the directory path for hints (gcp/openstack), but still not great.

**Comment by mstair** [comment]
How about this?
```
modname = os.path.splitext(fname)[0]
try:
    module=imp.load_source(modname, os.path.join(root,fname))
except ImportError:
    app.logger.debug("Failed to load module %s from %s", modname, os.path.join(root,fname))
else:
    app.logger.debug("Loaded module %s from %s", modname, os.path.join(root,fname))
```

**Comment by monkeysecurity** [comment]
Would that go into `auditor.py` and `watcher.py` and `alerter.py` ?

I like it.  Maybe up the log from `debug`  to at least `info` ?

**Comment by mstair** [comment]
Its in common/utils.py
