### ISSUE TITLE
GCP and OpenStack Cloudaux extras should not be required for AWS installs

### ISSUE THREAD

**Issue by mstair** [Netflix/security_monkey#863]
The scheduler loads all of the modules (watchers/auditors), regardless of associated account_type, which means that GCP and OpenStack Cloudaux extras are required on AWS installs. This dependency should be removed with only the account_specific dependencies being required.

**Comment by mstair** [comment]
Regression tested this on both AWS and OpenStack 👍

**Comment by monkeysecurity** [comment]
Just merged in #865 - Closing
