### ISSUE TITLE
Taking more than 24 hours to pull environment data

### ISSUE THREAD

**Issue by ekmabrouk** [Netflix/security_monkey#866]
Hello,

I have followed the default installation instructions, and am beginning with just 3 AWS accounts to keep track of.

When I restarted the scheduler, it took more than a day for all of the results to show in the console.  Is this normal behavior, or is there something that I should change?

Also, I see that there are many regions that I don't need to be scanned; is it possible to filter this?

**Comment by mstair** [comment]
Regarding regions, there is no way to filter currently. The available regions for each service is queried from the boto client. 

I wonder if you disable a region for [STS](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html), if boto will not return that region.

**Comment by monkeysecurity** [comment]
It would be nice if you could configure SM to only track certain regions.

Would also be nice if SM could use a cluster of machines/containers to do lots more stuff in parallel.

Short term fix is to disable less important watchers (or lower their interval) in the "Watcher Config" section of the settings UI.

**Comment by mikegrima** [comment]
You **CAN** technically run SM with several other instances/containers in parallel. That would require you to dedicate a container/instance to specific account/technology pairs where you run specific `monkey find_changes` commands.

**Comment by mstair** [comment]
I also wonder if you could configure a Config->SQS->Lambda/EC2 pipeline to only find_changes on account/tech that had deltas.

**Comment by mikegrima** [comment]
@mstair We are actively working on this type of workflow and creating the underlying infrastructure to enable this behavior. This is still under heavy development, so nothing major to announce yet. Part of this effort is underway with our Netflix-Skunkworks/historical project.

**Comment by mikegrima** [comment]
@ekmabrouk I am going to close this ticket.

To help mitigate this, please spin up more instances that are dedicated Security Monkey workers that you can have focused on specific account and technology pairs.
