### ISSUE TITLE
SM item search should consider account status

### ISSUE THREAD

**Issue by monkeysecurity** [Netflix/security_monkey#872]
If you have an AWS account that you have deleted, you would tell SM not to track it by unsetting `Account.active`.

If someone was later searching with the Items table with `status == Active`, they would not expect items from deleted accounts to show up.

Right now, they will still show up unless you tell SM to delete all of these Items, which you may not want to do for forensic/historic value.

The `views/items.py` page should be updated to join on `Acccount.active = True` when `status=active/true`.

**Comment by monkeysecurity** [comment]
@kevgliss has asked about this a couple times, so I'm tracking it here now.

**Comment by naggappan** [comment]
Let me give a try on this ticket. Can you guys assign it to me. Also

**Comment by mikegrima** [comment]
Fixed in #1025
