### ISSUE TITLE
GCP Service Account Roles Incorrect

### ISSUE THREAD

**Issue by bryanCoteChang** [Netflix/security_monkey#876]
The GCP instructions set up the service account with the following roles:
- Project Viewer
- Security Viewer

These are not sufficient, the role it actually needs is:
- Project Owner

If possible, it would be incredibly useful if it would run with the lower permissions.  I don't give anything the Project Owner role in any of our environments.

**Comment by mikegrima** [comment]
Hmm. I do recall running through the instructions a few months ago, and only needed Project Viewer and Security Viewer to get Security Monkey working.

**Comment by mstair** [comment]
I believe it is this step, assigning ownership of the service account, https://github.com/Netflix/security_monkey/blob/develop/docs/images/add_user_to_service_account.png
