### ISSUE TITLE
GCP account not returning data

### ISSUE THREAD

**Issue by antoine-castex** [Netflix/security_monkey#898]
Hello

My service account is Project OWNER  ,so no IAM role problem
I have created an account to monitor the gcp project, but without --creds_file   because i don't what to make ? no information about this param in the guide

and how to check log to see what is the problem please ?

thanks

**Comment by mikegrima** [comment]
Hello!

You are correct that the docs don't outline this. We definitely need to add it (would love a PR!).

The credentials file needed for GCP is a JSON file. These docs outline what is required: https://cloud.google.com/storage/docs/authentication#service_accounts 

Effectively, you will need to create a key for your service account and select the JSON option. This file is needed by SM and the path to it is set when running the `monkey add_account_gcp` command (specifically the `--creds_file` parameter).

**Comment by mikegrima** [comment]
Just merged in #899 with additional clarification.
