### ISSUE TITLE
Automated docker builds

### ISSUE THREAD

**Issue by kpcyrd** [Netflix/security_monkey#917]
It seems the [automated docker builds][0] are out of date (last built 2 years ago), since the docker files are now properly included in this repo. I think the docker build needs to be updated to point to this repo instead. Hopefully, this is a trivial change. :) Thanks!

[0]: https://hub.docker.com/r/netflixoss/security_monkey-api/

**Comment by mikegrima** [comment]
I don't think we have a pipeline actively set up to post them.

At the moment, users are required to bake in the config. If we move to env vars, then we can add a task in Travis CI to do this.

I'll re-open #918 . I don't have any available cycles to work on it, however.

**Comment by mikegrima** [comment]
Closing until #918 get's done.
