### ISSUE TITLE
Decouple docker containers

### ISSUE THREAD

**Issue by kpcyrd** [Netflix/security_monkey#918]
I noticed the docker containers are currently very tightly coupled:

- everything is attached to the `secmonkey-data` container
- the entrypoints for each container are located inside a volume that is mounted from the repo into the data container
- `./env-config/config-docker.py` and `./data/aws_accounts.json` are required instead of environment variables.

I would recommend the following:
- remove the data container and use bind mounts only where it's really needed (ideally, nothing except the database needs persistent data).
- include the entry point into the image itself.
- use environment variables instead of configuration files so you don't need to manually edit persistent volumes.

This would make the docker deployment a lot easier to use! :)

**Comment by mikegrima** [comment]
Would love a PR.

**Comment by mikegrima** [comment]
Once this is done, we can reopen #917 , and get that pipeline back up and running.

**Comment by mikegrima** [comment]
The latest PR #933 may address some of this.

**Comment by mikegrima** [comment]
Closing this out as a number of changes have been made in 1.0 that may address many of this. It will also help avoid confusion as many changes have been made
