### ISSUE TITLE
SecurityMonkey Docker Installation Errors

### ISSUE THREAD

**Issue by SyCode7** [Netflix/security_monkey#933]
I am installing a local security monkey setup using the docker compose in the repository.
After executing ` monkey add_account_aws --id $account --name $name -r SecurityMonkey` , the following error are encountered:

`No command 'monkey' found, did you mean:
 Command 'donkey' from package 'donkey' (universe)
monkey: command not found`

Have i missed out some steps or I need to do something else. 
Thanks.

**Comment by mikegrima** [comment]
You need to ensure that you are in the Python virtual environment.

**Comment by SyCode7** [comment]
Unfortunately, `cd /usr/local/src/security_monkey` does not  exist on my system.
I am using Ubuntu 14.04.

**Comment by mikegrima** [comment]
@SyCode7 : I just merged in #937 , which should hopefully address the Docker issues.

Can you download the latest develop branch and try again?
