### ISSUE TITLE
wrong s3 region appearance 

### ISSUE THREAD

**Issue by roeera** [Netflix/security_monkey#936]
New user of secmonkey, very nice job !
We found a problem when searching for s3, all Regions in results are shown as us-east-1.

**Comment by mikegrima** [comment]
Hello @roeera !

I have not yet encountered this one.  Not to be dense, but are all your buckets in us-east-1?

**Comment by roeera** [comment]
Hi Mike !

Actually most of our buckets located in eu-west-1:) ... Sounds like a bug.

**Comment by mikegrima** [comment]
Which version of security monkey are you running?

**Comment by roeera** [comment]
Installed current master

**Comment by mikegrima** [comment]
I suspect the current master is a bit out of date.  I am planning on creating a new release after getting some documentation updated.

Can you try switching over to the latest develop branch?  Just make sure that you follow the Quickstart guide as there are breaking changes from master to the current develop.

Thanks

**Comment by roeera** [comment]
Sure, unfortunately there are some missing info in the current develop docs
(e.g. supervisord configuration steps that missing which changed from one
file into 3 etc...).

BTW I'm planning to install it over K8s, do you have some experience with
such case ?

**Comment by mikegrima** [comment]
Which info in the quickstart is missing?  The main changes are in the autostarting doc.

I don't have much experience with K8s, but I would imagine there shouldn't be too many issues.

**Comment by roeera** [comment]
Supervisord configuration is missing...
I'll try the installation of develop tomorrow and if everything will work,
will try to implement over K8s and update accordingly.

**Comment by mikegrima** [comment]
The supervisord configuration is included and documented in the autostarting doc.
