### ISSUE TITLE
Ambiguous documentation

### ISSUE THREAD

**Issue by johnclaus** [Netflix/security_monkey#949]
The following section of this [documentation](https://github.com/Netflix/security_monkey/blob/develop/docs/postgres_aws.md) is unclear:

"Create a new security group named securitymonkey-rds, and add an ingress rule on TCP 5432 to permit the securitymonkey (or whatever you named the security group that Security Monkey is launched with) security group access."

Exactly which security group am I supposed to use for the custom source on this inbound rule?

**Comment by mikegrima** [comment]
For RDS, you are going to create a security group named `securitymonkey-rds`, and ingress the `secuirtymonkey` group to it (assuming that Security Monkey is using a security group named `securitymonkey`).

**Comment by johnclaus** [comment]
@mikegrima Coming from the previous [IAM steps](https://github.com/Netflix/security_monkey/blob/develop/docs/iam_aws.md), there aren't any security groups created.  Where exactly is this `securitymonkey` security group being created in the Quickstart documentation?

**Comment by mikegrima** [comment]
It's under https://github.com/Netflix/security_monkey/blob/develop/docs/instance_launch_aws.md.

**Comment by mikegrima** [comment]
Oh I see... This is after the RDS instructions. I can see why that is ambiguous.

**Comment by mikegrima** [comment]
I would love a PR to the docs to update this. I think this would be good to get in for our official 1.0 release (still an RC -- want to make sure that these things are clarified before merging to master).

**Comment by johnclaus** [comment]
@mikegrima Understood and thank you very much for allaying my uncertainties.  I'd be happy to update the documentation and submit a PR to clear this up.

**Comment by johnclaus** [comment]
@mikegrima Per this thread, I created [PR-950](https://github.com/Netflix/security_monkey/pull/950).
