### ISSUE TITLE
static.tar.gz not available?

### ISSUE THREAD

**Issue by fstuck37** [Netflix/security_monkey#958]
[X] Review the [Quickstart guide](quickstart.md)
[X] Search for both open and closed issues regarding the problem you are experiencing
[X] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](iam_aws.md), [GCP](iam_gcp.md), [OpenStack](iam_openstack.md), [GitHub](github_setup.md#access-keys-and-permissions)

## Description of issue:
In the quick start guide it references downloading static.tar.gz and this file is no longer available on the site specified.
"If you're using the stable (master) branch, you have the option of downloading the web UI instead of compiling it. Visit the latest release https://github.com/Netflix/security_monkey/releases/latest and download static.tar.gz."

Looks like now only source code (v1.0.0.tar.gz) is available. 
Is the only deployment option to compile with dart?
If so, has anyone scripted this process on CentOS?

Thanks,
Fred

**Comment by mikegrima** [comment]
Oops

**Comment by fstuck37** [comment]
@mikegrima 
Assuming from your response you'll put it back.
Any chance there can be a permanent link to the static.tar.gz file itself?
For example: https://github.com/Netflix/security_monkey/releases/latest/static.tar.gz
This would be helpful for scripting.
Thanks,
Fred

**Comment by mikegrima** [comment]
I'll try to get this done later today.

**Comment by fstuck37** [comment]
Thanks for the quick response as always.
-Fred

**Comment by mikegrima** [comment]
Hello @fstuck37 . I just updated the release with the tarball. I'm not totally sure how @monkeysecurity generated this in the past as mine is 6x larger in size for some reason.

Please try it out and let me know if you experience any issues with it.

**Comment by mikegrima** [comment]
@fstuck37 I figured it out.  To generate this, I run the `env_tests/test_dart.sh` script -- only I removed `--mode=debug` from the `pub build` step.

I just updated the `static.tar.gz` file and it is now consistent with the previous releases.

**Comment by fstuck37** [comment]
@mikegrima 
Thanks for the help
Looks good.
-Fred
