### ISSUE TITLE
Docker build reliant on build host system umask

### ISSUE THREAD

**Issue by jcmcken** [Netflix/security_monkey#959]
My development system has a default umask of ``0007`` (a common security setting). When I ``git clone`` and build the Docker containers, the ``nginx`` service copies all of the files into the container with mode ``0440``, which causes various things to fail (e.g. ``nginx`` user inside container can't read any of the files because they're owned by ``root``).

Ideally, the Docker build should not rely the system umask, but should set its own, so that the build is reproducible.

**Comment by mikegrima** [comment]
Ah yes... the annoying umask "security" setting...

This is not a high priority for us to fix. Please submit a PR and I will merge it in.

**Comment by mikegrima** [comment]
Thanks for the PR! 👍
