### ISSUE TITLE
create_user cannot update password for existing users

### ISSUE THREAD

**Issue by senorcinco** [Netflix/security_monkey#966]
## Please make sure that you have checked the boxes: 

- [X] Review the [Quickstart guide](quickstart.md)
- [X] Search for both open and closed issues regarding the problem you are experiencing
- [X] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](iam_aws.md), [GCP](iam_gcp.md), [OpenStack](iam_openstack.md), [GitHub](github_setup.md#access-keys-and-permissions)

## Description of issue:

We need a way to change the password of existing users.  Through the gitter.im channel, I was told `monkey create_user <email> <role>` would update an existing user, but it doesn't appear to support this use case:

```
$ monkey create_user "user.name@example.com" "Admin"
[+] Updating existing user
$
```
It never displays the password prompts for setting a new password.

**Comment by mikegrima** [comment]
Fixed in #967 and #970
