### ISSUE TITLE
Worker is not running parallel 

### ISSUE THREAD

**Issue by geminiyeak** [Netflix/security_monkey#987]
## Please make sure that you have checked the boxes: 

- [ ✓] Review the [Quickstart guide](quickstart.md)
- [✓ ] Search for both open and closed issues regarding the problem you are experiencing
- [✓ ] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](iam_aws.md), [GCP](iam_gcp.md), [OpenStack](iam_openstack.md), [GitHub](github_setup.md#access-keys-and-permissions)

## Description of issue:

Hi, i had install 3 instances for Security Monkey in AWS
1 for UI
1 for Scheduler
1 for worker

and i have setup auto scaling group for worker as well but when AS launch the workers but the workload is distributing to other worker.
because i can see the CPU of the primary worker is reached 100% utilization but the rest of the worker is idle still.
do i need to configure the worker in Load Balance or it will automatically pick up the task.
below is my setup screen dump
![image](https://user-images.githubusercontent.com/23624395/37186974-0cd15488-2383-11e8-8185-02925fa17802.png)

Hope to have some advise.

**Comment by mikegrima** [comment]
Hello. Sorry for the late response.

At the surface, this sounds like the AMI that is in your ASG doesn't have the same exact configuration as the instance that is working. Did you make an AMI based off of the _current_ configuration of the working "worker" instance?  

If you made changes to that instance to get things working but didn't generate an AMI off of it, then the AMI that the ASG launched instances from lack the required configuration to function.  It can explain why the workers on the ASG aren't working.

**Comment by geminiyeak** [comment]
Many thanks for the feedback.
Yes, found out that minor configuration is different and after make changes all running perfectly.

Appreciated your feedback.
