### ISSUE TITLE
Flask-SQLAlchemy v1.0 is not Python 3 compatible

### ISSUE THREAD

**Issue by cclauss** [Netflix/security_monkey#996]
## Please make sure that you have checked the boxes: 

- [X] Review the [Quickstart guide](quickstart.md)
- [X] Search for both open and closed issues regarding the problem you are experiencing
- [X] **For permissions issues** (Access Denied and credential related errors), please refer to the requisite docs before submitting an issue:
[AWS](iam_aws.md), [GCP](iam_gcp.md), [OpenStack](iam_openstack.md), [GitHub](github_setup.md#access-keys-and-permissions)

## Description of issue:

Related to #994 and #995

We are currently [using Flask-SQLAlchemy 1.0](https://github.com/Netflix/security_monkey/blob/develop/setup.py#L58) which is not compatible with Python 3.  Attempts to upgrade to the [current Flask-SQLAlchemy 2.3.2](https://pypi.python.org/pypi/Flask-SQLAlchemy) (which _is_ Python 3 compatible) cause our Travis CI tests on Python 2 to fail.

Requirements that are __not__ yet upgraded:
* **Flask-Script** from `==0.6.3` to `==2.0.6`
* **Flask-SQLAlchemy** `==1.0` to `==2.3.2`
* **moto** from `==0.4.30` to `==1.2.0`

**Comment by mikegrima** [comment]
You should be able to upgrade moto to the latest version. We have a bunch of Python 3 projects that use it without issues.

**Comment by mikegrima** [comment]
I'll work on the moto upgrade.

**Comment by cclauss** [comment]
Actually upgrading __Flask-SQLAlchemy__ is most important because that version is not Python 3 compatible.  The other two are supposedly Python 3 compatible even in their current versions.
